//// -------------------------------------------------------------
//// 
//// File Name: C:\Users\Labhesh\OneDrive\Desktop\IIT Madras\Startup\FPGA\aLTITUDE_Controller\experimental_model\alpha3rd_order_filter.v
//// Created: 2026-06-11 23:44:57
//// 
//// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
//// 
//// 
//// -- -------------------------------------------------------------
//// -- Rate and Clocking Details
//// -- -------------------------------------------------------------
//// Model base rate: 0.004
//// Target subsystem base rate: 0.004
//// 
//// 
//// Clock Enable  Sample Time
//// -- -------------------------------------------------------------
//// ce_out        0.004
//// -- -------------------------------------------------------------
//// 
//// 
//// Output Signal                 Clock Enable  Sample Time
//// -- -------------------------------------------------------------
//// Z_est                         ce_out        0.004
//// V_est                         ce_out        0.004
//// -- -------------------------------------------------------------
//// 
//// -------------------------------------------------------------

//this time with variables introduced for the K constants- k bias, k vel and k pos 

// -------------------------------------------------------------
// 
// Module: alpha3rd_order_filter
// Source Path: experimental_model/3rd_order_filter
// Hierarchy Level: 0
// Model version: 4.36
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module alpha3rd_order_filter
          (clk,
           reset,
           clk_enable,
           barometer,
           angles_0,
           angles_1,
           accelrometer_0,
           accelrometer_1,
           accelrometer_2,
           K_bias_in,       // NEW GPIO INPUT
           K_vel_in,        // NEW GPIO INPUT
           K_pos_in,        // NEW GPIO INPUT
           ce_out,
           Z_est,
           V_est);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [23:0] barometer;  // sfix24_En16
  input   signed [23:0] angles_0;  // sfix24_En16
  input   signed [23:0] angles_1;  // sfix24_En16
  input   signed [23:0] accelrometer_0;  // sfix24_En16
  input   signed [23:0] accelrometer_1;  // sfix24_En16
  input   signed [23:0] accelrometer_2;  // sfix24_En16
  input   signed [23:0] K_bias_in;  // sfix24_En16
  input   signed [31:0] K_vel_in;   // sfix32_En20
  input   signed [23:0] K_pos_in;   // sfix24_En18
  output  ce_out;
  output  signed [23:0] Z_est;  // sfix24_En16
  output  signed [23:0] V_est;  // sfix24_En16


  wire enb;
  wire stateControl;
  reg  [6:0] delayMatch14_reg;  // ufix1 [7]
  wire stateControl_1;
  reg signed [23:0] delayMatch13_reg [0:6];  // sfix24 [7]
  reg signed [23:0] delayMatch13_reg_next [0:6];  // sfix24_En16 [7]
  reg signed [23:0] barometer_1;  // sfix24_En16
  wire stateControl_2;
  reg  [7:0] delayMatch5_reg;  // ufix1 [8]
  wire stateControl_3;
  reg signed [23:0] HwModeRegister2_reg [0:3];  // sfix24 [4]
  reg signed [23:0] HwModeRegister2_reg_next [0:3];  // sfix24_En16 [4]
  reg signed [23:0] accelrometer_1_1;  // sfix24_En16
  wire signed [23:0] angles [0:1];  // sfix24_En16 [2]
  reg signed [23:0] angles_2 [0:1];  // sfix24_En16 [2]
  wire signed [15:0] kconst;  // sfix16_En14
  reg signed [15:0] kconst_1;  // sfix16_En14
  wire signed [39:0] Gain_out1 [0:1];  // sfix40_En30 [2]
  reg signed [39:0] Gain_out1_1 [0:1];  // sfix40_En30 [2]
  wire signed [15:0] Gain_out1_2 [0:1];  // sfix16_En12 [2]
  wire signed [16:0] Sine_HDL_Optimized1_x;  // sfix17_En14
  reg signed [16:0] Sine_HDL_Optimized1_x_1;  // sfix17_En14
  wire signed [40:0] ay_sinphi_out1;  // sfix41_En30
  reg signed [40:0] ay_sinphi_out1_1;  // sfix41_En30
  wire signed [23:0] ay_sinphi_out1_2;  // sfix24_En18
  reg signed [23:0] ay_sinphi_out1_3;  // sfix24_En18
  wire signed [16:0] Cosine_HDL_Optimized1_x;  // sfix17_En14
  reg signed [16:0] Cosine_HDL_Optimized1_x_1;  // sfix17_En14
  reg signed [16:0] reduced_reg [0:1];  // sfix17 [2]
  wire signed [16:0] reduced_reg_next [0:1];  // sfix17_En14 [2]
  wire signed [16:0] Cosine_HDL_Optimized1_x_2;  // sfix17_En14
  wire signed [40:0] ay_sinphi_costheta_out1;  // sfix41_En32
  reg signed [40:0] ay_sinphi_costheta_out1_1;  // sfix41_En32
  wire signed [23:0] ay_sinphi_costheta_out1_2;  // sfix24_En18
  reg signed [23:0] HwModeRegister_reg [0:3];  // sfix24 [4]
  reg signed [23:0] HwModeRegister_reg_next [0:3];  // sfix24_En16 [4]
  reg signed [23:0] accelrometer_0_1;  // sfix24_En16
  wire signed [16:0] Sine_HDL_Optimized_x;  // sfix17_En14
  reg signed [16:0] Sine_HDL_Optimized_x_1;  // sfix17_En14
  wire signed [40:0] ax_sintheta_out1;  // sfix41_En30
  reg signed [40:0] ax_sintheta_out1_1;  // sfix41_En30
  wire signed [23:0] ax_sintheta_out1_2;  // sfix24_En18
  reg signed [23:0] HwModeRegister6_reg [0:5];  // sfix24 [6]
  reg signed [23:0] HwModeRegister6_reg_next [0:5];  // sfix24_En16 [6]
  reg signed [23:0] accelrometer_2_1;  // sfix24_En16
  wire signed [16:0] Cosine_HDL_Optimized_x;  // sfix17_En14
  reg signed [16:0] Cosine_HDL_Optimized_x_1;  // sfix17_En14
  wire signed [33:0] costheta_cosphi_out1;  // sfix34_En28
  reg signed [33:0] costheta_cosphi_out1_1;  // sfix34_En28
  wire signed [23:0] costheta_cosphi_out1_2;  // sfix24_En18
  reg signed [23:0] costheta_cosphi_out1_3;  // sfix24_En18
  wire signed [47:0] az_costheta_cosphi_out1;  // sfix48_En34
  reg signed [23:0] delayMatch9_reg [0:1];  // sfix24 [2]
  wire signed [23:0] delayMatch9_reg_next [0:1];  // sfix24_En18 [2]
  wire signed [23:0] ax_sintheta_out1_3;  // sfix24_En18
  wire signed [24:0] A_earth_Z_stage2_sub_cast;  // sfix25_En18
  wire signed [24:0] A_earth_Z_stage2_sub_cast_1;  // sfix25_En18
  wire signed [24:0] A_earth_Z_stage2_sub_temp;  // sfix25_En18
  wire signed [23:0] A_earth_Z_stage2_cast;  // sfix24_En18
  wire signed [24:0] A_earth_Z_op_stage1;  // sfix25_En18
  reg signed [47:0] az_costheta_cosphi_out1_1;  // sfix48_En34
  wire signed [23:0] az_costheta_cosphi_out1_2;  // sfix24_En18
  wire signed [23:0] A_earth_Z_stage3_add_cast;  // sfix24_En18
  wire signed [24:0] A_earth_Z_stage3_add_cast_1;  // sfix25_En18
  wire signed [24:0] A_earth_Z_stage3_add_cast_2;  // sfix25_En18
  wire signed [24:0] A_earth_Z_stage3_add_temp;  // sfix25_En18
  wire signed [23:0] A_earth_Z_out1;  // sfix24_En18
  wire signed [15:0] Constant1_out1;  // sfix16_En11
  wire signed [23:0] acc_linear_sub_cast;  // sfix24_En16
  wire signed [23:0] acc_linear_sub_cast_1;  // sfix24_En16
  wire signed [23:0] acc_linear_out1;  // sfix24_En16
  reg signed [23:0] acc_linear_out1_1;  // sfix24_En16
  wire stateControl_5;
  reg  [8:0] delayMatch1_reg;  // ufix1 [9]
  wire stateControl_6;
  wire [14:0] kconst_2;  // ufix15_En22
  reg [14:0] kconst_3;  // ufix15_En22
  wire signed [23:0] error_out1;  // sfix24_En18
  wire signed [47:0] K_bias_out1;  // sfix48_En34
  wire signed [23:0] K_bias_out1_1;  // sfix24_En16
  wire signed [23:0] B_est_indtc;  // sfix24
  reg signed [23:0] B_est_indtc_1;  // sfix24
  wire signed [15:0] gain_cast;  // sfix16_En22
  wire signed [39:0] gain_mul_temp;  // sfix40_En22
  wire signed [38:0] B_est_u_gain;  // sfix39_En22
  reg signed [38:0] B_est_u_gain_1;  // sfix39_En22
  wire signed [23:0] B_est_u_gain_2;  // sfix24
  wire signed [23:0] B_est_u_dtc;  // sfix24_En16
  reg signed [23:0] B_est_x_reg;  // sfix24_En16
  wire signed [24:0] adder_add_cast;  // sfix25_En16
  wire signed [24:0] adder_add_cast_1;  // sfix25_En16
  wire signed [24:0] adder_add_temp;  // sfix25_En16
  wire signed [23:0] B_est_u_add;  // sfix24_En16
  wire signed [23:0] B_est_x_reg_1;  // sfix24_En16
  wire signed [23:0] B_est_x_reg_2;  // sfix24_En16
  wire signed [24:0] Acc_corrected_sub_cast;  // sfix25_En16
  wire signed [24:0] Acc_corrected_sub_cast_1;  // sfix25_En16
  wire signed [24:0] Acc_corrected_sub_temp;  // sfix25_En16
  wire signed [23:0] Acc_corrected_out1;  // sfix24_En16
  wire signed [55:0] Kvel_out1;  // sfix56_En38
  wire signed [23:0] Kvel_out1_1;  // sfix24_En18
  reg signed [23:0] Kvel_out1_2;  // sfix24_En18
  wire signed [24:0] Sum_add_cast;  // sfix25_En18
  wire signed [23:0] Sum_add_cast_1;  // sfix24_En18
  wire signed [24:0] Sum_add_cast_2;  // sfix25_En18
  wire signed [24:0] Sum_add_temp;  // sfix25_En18
  wire signed [23:0] Sum_out1;  // sfix24_En18
  wire signed [23:0] Vpred_indtc;  // sfix24
  wire signed [38:0] gain2_mul_temp;  // sfix39_En23
  wire signed [37:0] Vpred_u_gain;  // sfix38_En23
  wire signed [23:0] Vpred_u_gain_1;  // sfix24
  wire signed [23:0] Vpred_u_dtc;  // sfix24_En16
  reg signed [23:0] Vpred_x_reg;  // sfix24_En16
  wire signed [24:0] adder2_add_cast;  // sfix25_En16
  wire signed [24:0] adder2_add_cast_1;  // sfix25_En16
  wire signed [24:0] adder2_add_temp;  // sfix25_En16
  wire signed [23:0] Vpred_x_reg_1;  // sfix24_En16
  wire signed [23:0] Vpred_x_reg_2;  // sfix24_En16
  reg signed [23:0] Discrete_Time_Integrator2_x_reg;  // sfix24_En16
  wire signed [23:0] error_sub_cast;  // sfix24_En18
  wire signed [24:0] error_sub_cast_1;  // sfix25_En18
  wire signed [23:0] error_sub_cast_2;  // sfix24_En18
  wire signed [24:0] error_sub_cast_3;  // sfix25_En18
  wire signed [24:0] error_sub_temp;  // sfix25_En18
  wire signed [47:0] K_pos_out1;  // sfix48_En36
  wire signed [23:0] K_pos_out1_1;  // sfix24_En16
  wire signed [24:0] Sum1_add_cast;  // sfix25_En16
  wire signed [24:0] Sum1_add_cast_1;  // sfix25_En16
  wire signed [24:0] Sum1_add_temp;  // sfix25_En16
  wire signed [23:0] Sum1_out1;  // sfix24_En16
  wire signed [23:0] Discrete_Time_Integrator2_indtc;  // sfix24
  wire signed [39:0] gain1_mul_temp;  // sfix40_En22
  wire signed [38:0] Discrete_Time_Integrator2_u_gain;  // sfix39_En22
  wire signed [23:0] Discrete_Time_Integrator2_u_gain_1;  // sfix24
  wire signed [23:0] Discrete_Time_Integrator2_u_dtc;  // sfix24_En16
  wire signed [24:0] adder1_add_cast;  // sfix25_En16
  wire signed [24:0] adder1_add_cast_1;  // sfix25_En16
  wire signed [24:0] adder1_add_temp;  // sfix25_En16
  wire signed [23:0] Discrete_Time_Integrator2_u_add;  // sfix24_En16
  wire signed [23:0] Discrete_Time_Integrator2_u_add_1;  // sfix24_En16
  reg signed [31:0] delayMatch13_t_0_0;  // int32
  reg signed [31:0] delayMatch13_t_0_1;  // int32
  reg signed [31:0] delayMatch13_t_1;  // int32
  reg signed [31:0] HwModeRegister2_t_0_0;  // int32
  reg signed [31:0] HwModeRegister2_t_0_1;  // int32
  reg signed [31:0] HwModeRegister2_t_1;  // int32
  reg signed [31:0] HwModeRegister10_t_0_0;  // int32
  reg signed [31:0] HwModeRegister10_t_1;  // int32
  reg signed [31:0] PipelineRegister5_t_0_0;  // int32
  reg signed [31:0] PipelineRegister5_t_1;  // int32
  reg signed [31:0] reduced_t_0_0;  // int32
  reg signed [31:0] reduced_t_1;  // int32
  reg signed [31:0] HwModeRegister_t_0_0;  // int32
  reg signed [31:0] HwModeRegister_t_0_1;  // int32
  reg signed [31:0] HwModeRegister_t_1;  // int32
  reg signed [31:0] HwModeRegister6_t_0_0;  // int32
  reg signed [31:0] HwModeRegister6_t_0_1;  // int32
  reg signed [31:0] HwModeRegister6_t_1;  // int32
  reg signed [31:0] delayMatch9_t_0_0;  // int32
  reg signed [31:0] delayMatch9_t_1;  // int32


  assign stateControl = 1'b1;

  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : delayMatch14_process
      if (reset == 1'b1) begin
        delayMatch14_reg <= {7{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch14_reg[0] <= stateControl;
          delayMatch14_reg[32'sd6:32'sd1] <= delayMatch14_reg[32'sd5:32'sd0];
        end
      end
    end

  assign stateControl_1 = delayMatch14_reg[6];

  always @(posedge clk or posedge reset)
    begin : delayMatch13_process
      if (reset == 1'b1) begin
        for(delayMatch13_t_1 = 32'sd0; delayMatch13_t_1 <= 32'sd6; delayMatch13_t_1 = delayMatch13_t_1 + 32'sd1) begin
          delayMatch13_reg[delayMatch13_t_1] <= 24'sb000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch13_t_0_1 = 32'sd0; delayMatch13_t_0_1 <= 32'sd6; delayMatch13_t_0_1 = delayMatch13_t_0_1 + 32'sd1) begin
            delayMatch13_reg[delayMatch13_t_0_1] <= delayMatch13_reg_next[delayMatch13_t_0_1];
          end
        end
      end
    end

  always @* begin
    barometer_1 = delayMatch13_reg[6];
    delayMatch13_reg_next[0] = barometer;

    for(delayMatch13_t_0_0 = 32'sd0; delayMatch13_t_0_0 <= 32'sd5; delayMatch13_t_0_0 = delayMatch13_t_0_0 + 32'sd1) begin
      delayMatch13_reg_next[delayMatch13_t_0_0 + 32'sd1] = delayMatch13_reg[delayMatch13_t_0_0];
    end

  end

  assign stateControl_2 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch5_process
      if (reset == 1'b1) begin
        delayMatch5_reg <= {8{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch5_reg[0] <= stateControl_2;
          delayMatch5_reg[32'sd7:32'sd1] <= delayMatch5_reg[32'sd6:32'sd0];
        end
      end
    end

  assign stateControl_3 = delayMatch5_reg[7];

  always @(posedge clk or posedge reset)
    begin : HwModeRegister2_process
      if (reset == 1'b1) begin
        for(HwModeRegister2_t_1 = 32'sd0; HwModeRegister2_t_1 <= 32'sd3; HwModeRegister2_t_1 = HwModeRegister2_t_1 + 32'sd1) begin
          HwModeRegister2_reg[HwModeRegister2_t_1] <= 24'sb000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(HwModeRegister2_t_0_1 = 32'sd0; HwModeRegister2_t_0_1 <= 32'sd3; HwModeRegister2_t_0_1 = HwModeRegister2_t_0_1 + 32'sd1) begin
            HwModeRegister2_reg[HwModeRegister2_t_0_1] <= HwModeRegister2_reg_next[HwModeRegister2_t_0_1];
          end
        end
      end
    end

  always @* begin
    accelrometer_1_1 = HwModeRegister2_reg[3];
    HwModeRegister2_reg_next[0] = accelrometer_1;

    for(HwModeRegister2_t_0_0 = 32'sd0; HwModeRegister2_t_0_0 <= 32'sd2; HwModeRegister2_t_0_0 = HwModeRegister2_t_0_0 + 32'sd1) begin
      HwModeRegister2_reg_next[HwModeRegister2_t_0_0 + 32'sd1] = HwModeRegister2_reg[HwModeRegister2_t_0_0];
    end

  end

  assign angles[0] = angles_0;
  assign angles[1] = angles_1;

  always @(posedge clk or posedge reset)
    begin : HwModeRegister10_process
      if (reset == 1'b1) begin
        for(HwModeRegister10_t_1 = 32'sd0; HwModeRegister10_t_1 <= 32'sd1; HwModeRegister10_t_1 = HwModeRegister10_t_1 + 32'sd1) begin
          angles_2[HwModeRegister10_t_1] <= 24'sb000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(HwModeRegister10_t_0_0 = 32'sd0; HwModeRegister10_t_0_0 <= 32'sd1; HwModeRegister10_t_0_0 = HwModeRegister10_t_0_0 + 32'sd1) begin
            angles_2[HwModeRegister10_t_0_0] <= angles[HwModeRegister10_t_0_0];
          end
        end
      end
    end

  assign kconst = 16'sb0000101000110000;

  always @(posedge clk or posedge reset)
    begin : HwModeRegister11_process
      if (reset == 1'b1) begin
        kconst_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          kconst_1 <= kconst;
        end
      end
    end


  genvar t_0_0;
  generate
    for(t_0_0 = 32'sd0; t_0_0 <= 32'sd1; t_0_0 = t_0_0 + 32'sd1) begin:Gain_out1_gen
      assign Gain_out1[t_0_0] = angles_2[t_0_0] * kconst_1;
    end
  endgenerate

  always @(posedge clk or posedge reset)
    begin : PipelineRegister5_process
      if (reset == 1'b1) begin
        for(PipelineRegister5_t_1 = 32'sd0; PipelineRegister5_t_1 <= 32'sd1; PipelineRegister5_t_1 = PipelineRegister5_t_1 + 32'sd1) begin
          Gain_out1_1[PipelineRegister5_t_1] <= 40'sh0000000000;
        end
      end
      else begin
        if (enb) begin
          for(PipelineRegister5_t_0_0 = 32'sd0; PipelineRegister5_t_0_0 <= 32'sd1; PipelineRegister5_t_0_0 = PipelineRegister5_t_0_0 + 32'sd1) begin
            Gain_out1_1[PipelineRegister5_t_0_0] <= Gain_out1[PipelineRegister5_t_0_0];
          end
        end
      end
    end


  genvar ii;
  generate
    for(ii = 32'sd0; ii <= 32'sd1; ii = ii + 32'sd1) begin:Gain_out1_2_gen
      assign Gain_out1_2[ii] = (((Gain_out1_1[ii][39] == 1'b0) && (Gain_out1_1[ii][38:33] != 6'b000000)) || ((Gain_out1_1[ii][39] == 1'b0) && (Gain_out1_1[ii][33:18] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
                  ((Gain_out1_1[ii][39] == 1'b1) && (Gain_out1_1[ii][38:33] != 6'b111111) ? 16'sb1000000000000000 :
                  Gain_out1_1[ii][33:18] + $signed({1'b0, Gain_out1_1[ii][17]})));
    end
  endgenerate

  Sine_HDL_Optimized1 u_Sine_HDL_Optimized1 (.clk(clk),
                                             .reset(reset),
                                             .enb(clk_enable),
                                             .u(Gain_out1_2[0]),  // sfix16_En12
                                             .x(Sine_HDL_Optimized1_x)  // sfix17_En14
                                             );

  always @(posedge clk or posedge reset)
    begin : HwModeRegister3_process
      if (reset == 1'b1) begin
        Sine_HDL_Optimized1_x_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Sine_HDL_Optimized1_x_1 <= Sine_HDL_Optimized1_x;
        end
      end
    end

  assign ay_sinphi_out1 = accelrometer_1_1 * Sine_HDL_Optimized1_x_1;

  always @(posedge clk or posedge reset)
    begin : PipelineRegister1_process
      if (reset == 1'b1) begin
        ay_sinphi_out1_1 <= 41'sh00000000000;
      end
      else begin
        if (enb) begin
          ay_sinphi_out1_1 <= ay_sinphi_out1;
        end
      end
    end

  assign ay_sinphi_out1_2 = (((ay_sinphi_out1_1[40] == 1'b0) && (ay_sinphi_out1_1[39:35] != 5'b00000)) || ((ay_sinphi_out1_1[40] == 1'b0) && (ay_sinphi_out1_1[35:12] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((ay_sinphi_out1_1[40] == 1'b1) && (ay_sinphi_out1_1[39:35] != 5'b11111) ? 24'sb100000000000000000000000 :
              ay_sinphi_out1_1[35:12] + $signed({1'b0, ay_sinphi_out1_1[11]})));

  always @(posedge clk or posedge reset)
    begin : HwModeRegister4_process
      if (reset == 1'b1) begin
        ay_sinphi_out1_3 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          ay_sinphi_out1_3 <= ay_sinphi_out1_2;
        end
      end
    end

  Cosine_HDL_Optimized1 u_Cosine_HDL_Optimized1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .u(Gain_out1_2[1]),  // sfix16_En12
                                                 .x(Cosine_HDL_Optimized1_x)  // sfix17_En14
                                                 );

  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        Cosine_HDL_Optimized1_x_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Cosine_HDL_Optimized1_x_1 <= Cosine_HDL_Optimized1_x;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        for(reduced_t_1 = 32'sd0; reduced_t_1 <= 32'sd1; reduced_t_1 = reduced_t_1 + 32'sd1) begin
          reduced_reg[reduced_t_1] <= 17'sb00000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(reduced_t_0_0 = 32'sd0; reduced_t_0_0 <= 32'sd1; reduced_t_0_0 = reduced_t_0_0 + 32'sd1) begin
            reduced_reg[reduced_t_0_0] <= reduced_reg_next[reduced_t_0_0];
          end
        end
      end
    end

  assign Cosine_HDL_Optimized1_x_2 = reduced_reg[1];
  assign reduced_reg_next[0] = Cosine_HDL_Optimized1_x_1;
  assign reduced_reg_next[1] = reduced_reg[0];

  assign ay_sinphi_costheta_out1 = ay_sinphi_out1_3 * Cosine_HDL_Optimized1_x_2;

  always @(posedge clk or posedge reset)
    begin : PipelineRegister2_process
      if (reset == 1'b1) begin
        ay_sinphi_costheta_out1_1 <= 41'sh00000000000;
      end
      else begin
        if (enb) begin
          ay_sinphi_costheta_out1_1 <= ay_sinphi_costheta_out1;
        end
      end
    end

  assign ay_sinphi_costheta_out1_2 = (((ay_sinphi_costheta_out1_1[40] == 1'b0) && (ay_sinphi_costheta_out1_1[39:37] != 3'b000)) || ((ay_sinphi_costheta_out1_1[40] == 1'b0) && (ay_sinphi_costheta_out1_1[37:14] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((ay_sinphi_costheta_out1_1[40] == 1'b1) && (ay_sinphi_costheta_out1_1[39:37] != 3'b111) ? 24'sb100000000000000000000000 :
              ay_sinphi_costheta_out1_1[37:14] + $signed({1'b0, ay_sinphi_costheta_out1_1[13]})));

  always @(posedge clk or posedge reset)
    begin : HwModeRegister_process
      if (reset == 1'b1) begin
        for(HwModeRegister_t_1 = 32'sd0; HwModeRegister_t_1 <= 32'sd3; HwModeRegister_t_1 = HwModeRegister_t_1 + 32'sd1) begin
          HwModeRegister_reg[HwModeRegister_t_1] <= 24'sb000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(HwModeRegister_t_0_1 = 32'sd0; HwModeRegister_t_0_1 <= 32'sd3; HwModeRegister_t_0_1 = HwModeRegister_t_0_1 + 32'sd1) begin
            HwModeRegister_reg[HwModeRegister_t_0_1] <= HwModeRegister_reg_next[HwModeRegister_t_0_1];
          end
        end
      end
    end

  always @* begin
    accelrometer_0_1 = HwModeRegister_reg[3];
    HwModeRegister_reg_next[0] = accelrometer_0;

    for(HwModeRegister_t_0_0 = 32'sd0; HwModeRegister_t_0_0 <= 32'sd2; HwModeRegister_t_0_0 = HwModeRegister_t_0_0 + 32'sd1) begin
      HwModeRegister_reg_next[HwModeRegister_t_0_0 + 32'sd1] = HwModeRegister_reg[HwModeRegister_t_0_0];
    end

  end

  Sine_HDL_Optimized u_Sine_HDL_Optimized (.clk(clk),
                                           .reset(reset),
                                           .enb(clk_enable),
                                           .u(Gain_out1_2[1]),  // sfix16_En12
                                           .x(Sine_HDL_Optimized_x)  // sfix17_En14
                                           );

  always @(posedge clk or posedge reset)
    begin : HwModeRegister1_process
      if (reset == 1'b1) begin
        Sine_HDL_Optimized_x_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Sine_HDL_Optimized_x_1 <= Sine_HDL_Optimized_x;
        end
      end
    end

  assign ax_sintheta_out1 = accelrometer_0_1 * Sine_HDL_Optimized_x_1;

  always @(posedge clk or posedge reset)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        ax_sintheta_out1_1 <= 41'sh00000000000;
      end
      else begin
        if (enb) begin
          ax_sintheta_out1_1 <= ax_sintheta_out1;
        end
      end
    end

  assign ax_sintheta_out1_2 = (((ax_sintheta_out1_1[40] == 1'b0) && (ax_sintheta_out1_1[39:35] != 5'b00000)) || ((ax_sintheta_out1_1[40] == 1'b0) && (ax_sintheta_out1_1[35:12] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((ax_sintheta_out1_1[40] == 1'b1) && (ax_sintheta_out1_1[39:35] != 5'b11111) ? 24'sb100000000000000000000000 :
              ax_sintheta_out1_1[35:12] + $signed({1'b0, ax_sintheta_out1_1[11]})));

  always @(posedge clk or posedge reset)
    begin : HwModeRegister6_process
      if (reset == 1'b1) begin
        for(HwModeRegister6_t_1 = 32'sd0; HwModeRegister6_t_1 <= 32'sd5; HwModeRegister6_t_1 = HwModeRegister6_t_1 + 32'sd1) begin
          HwModeRegister6_reg[HwModeRegister6_t_1] <= 24'sb000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(HwModeRegister6_t_0_1 = 32'sd0; HwModeRegister6_t_0_1 <= 32'sd5; HwModeRegister6_t_0_1 = HwModeRegister6_t_0_1 + 32'sd1) begin
            HwModeRegister6_reg[HwModeRegister6_t_0_1] <= HwModeRegister6_reg_next[HwModeRegister6_t_0_1];
          end
        end
      end
    end

  always @* begin
    accelrometer_2_1 = HwModeRegister6_reg[5];
    HwModeRegister6_reg_next[0] = accelrometer_2;

    for(HwModeRegister6_t_0_0 = 32'sd0; HwModeRegister6_t_0_0 <= 32'sd4; HwModeRegister6_t_0_0 = HwModeRegister6_t_0_0 + 32'sd1) begin
      HwModeRegister6_reg_next[HwModeRegister6_t_0_0 + 32'sd1] = HwModeRegister6_reg[HwModeRegister6_t_0_0];
    end

  end

  Cosine_HDL_Optimized u_Cosine_HDL_Optimized (.clk(clk),
                                               .reset(reset),
                                               .enb(clk_enable),
                                               .u(Gain_out1_2[0]),  // sfix16_En12
                                               .x(Cosine_HDL_Optimized_x)  // sfix17_En14
                                               );

  always @(posedge clk or posedge reset)
    begin : HwModeRegister8_process
      if (reset == 1'b1) begin
        Cosine_HDL_Optimized_x_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Cosine_HDL_Optimized_x_1 <= Cosine_HDL_Optimized_x;
        end
      end
    end

  assign costheta_cosphi_out1 = Cosine_HDL_Optimized_x_1 * Cosine_HDL_Optimized1_x_1;

  always @(posedge clk or posedge reset)
    begin : PipelineRegister4_process
      if (reset == 1'b1) begin
        costheta_cosphi_out1_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          costheta_cosphi_out1_1 <= costheta_cosphi_out1;
        end
      end
    end

  assign costheta_cosphi_out1_2 = ((costheta_cosphi_out1_1[33] == 1'b0) && (costheta_cosphi_out1_1[32:10] == 23'b11111111111111111111111) ? 24'sb011111111111111111111111 :
              costheta_cosphi_out1_1[33:10] + $signed({1'b0, costheta_cosphi_out1_1[9]}));

  always @(posedge clk or posedge reset)
    begin : HwModeRegister7_process
      if (reset == 1'b1) begin
        costheta_cosphi_out1_3 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          costheta_cosphi_out1_3 <= costheta_cosphi_out1_2;
        end
      end
    end

  assign az_costheta_cosphi_out1 = accelrometer_2_1 * costheta_cosphi_out1_3;

  always @(posedge clk or posedge reset)
    begin : delayMatch9_process
      if (reset == 1'b1) begin
        for(delayMatch9_t_1 = 32'sd0; delayMatch9_t_1 <= 32'sd1; delayMatch9_t_1 = delayMatch9_t_1 + 32'sd1) begin
          delayMatch9_reg[delayMatch9_t_1] <= 24'sb000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch9_t_0_0 = 32'sd0; delayMatch9_t_0_0 <= 32'sd1; delayMatch9_t_0_0 = delayMatch9_t_0_0 + 32'sd1) begin
            delayMatch9_reg[delayMatch9_t_0_0] <= delayMatch9_reg_next[delayMatch9_t_0_0];
          end
        end
      end
    end

  assign ax_sintheta_out1_3 = delayMatch9_reg[1];
  assign delayMatch9_reg_next[0] = ax_sintheta_out1_2;
  assign delayMatch9_reg_next[1] = delayMatch9_reg[0];

  assign A_earth_Z_stage2_sub_cast = {ay_sinphi_costheta_out1_2[23], ay_sinphi_costheta_out1_2};
  assign A_earth_Z_stage2_sub_cast_1 = {ax_sintheta_out1_3[23], ax_sintheta_out1_3};
  assign A_earth_Z_stage2_sub_temp = A_earth_Z_stage2_sub_cast - A_earth_Z_stage2_sub_cast_1;
  assign A_earth_Z_stage2_cast = ((A_earth_Z_stage2_sub_temp[24] == 1'b0) && (A_earth_Z_stage2_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((A_earth_Z_stage2_sub_temp[24] == 1'b1) && (A_earth_Z_stage2_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(A_earth_Z_stage2_sub_temp[23:0])));
  assign A_earth_Z_op_stage1 = {A_earth_Z_stage2_cast[23], A_earth_Z_stage2_cast};

  always @(posedge clk or posedge reset)
    begin : PipelineRegister3_process
      if (reset == 1'b1) begin
        az_costheta_cosphi_out1_1 <= 48'sh000000000000;
      end
      else begin
        if (enb) begin
          az_costheta_cosphi_out1_1 <= az_costheta_cosphi_out1;
        end
      end
    end

  assign az_costheta_cosphi_out1_2 = (((az_costheta_cosphi_out1_1[47] == 1'b0) && (az_costheta_cosphi_out1_1[46:39] != 8'b00000000)) || ((az_costheta_cosphi_out1_1[47] == 1'b0) && (az_costheta_cosphi_out1_1[39:16] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((az_costheta_cosphi_out1_1[47] == 1'b1) && (az_costheta_cosphi_out1_1[46:39] != 8'b11111111) ? 24'sb100000000000000000000000 :
              az_costheta_cosphi_out1_1[39:16] + $signed({1'b0, az_costheta_cosphi_out1_1[15]})));

  assign A_earth_Z_stage3_add_cast = ((A_earth_Z_op_stage1[24] == 1'b0) && (A_earth_Z_op_stage1[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((A_earth_Z_op_stage1[24] == 1'b1) && (A_earth_Z_op_stage1[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(A_earth_Z_op_stage1[23:0])));
  assign A_earth_Z_stage3_add_cast_1 = {A_earth_Z_stage3_add_cast[23], A_earth_Z_stage3_add_cast};
  assign A_earth_Z_stage3_add_cast_2 = {az_costheta_cosphi_out1_2[23], az_costheta_cosphi_out1_2};
  assign A_earth_Z_stage3_add_temp = A_earth_Z_stage3_add_cast_1 + A_earth_Z_stage3_add_cast_2;
  assign A_earth_Z_out1 = ((A_earth_Z_stage3_add_temp[24] == 1'b0) && (A_earth_Z_stage3_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((A_earth_Z_stage3_add_temp[24] == 1'b1) && (A_earth_Z_stage3_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(A_earth_Z_stage3_add_temp[23:0])));

  assign Constant1_out1 = 16'sb0000000000000000;

  assign acc_linear_sub_cast = ({{2{A_earth_Z_out1[23]}}, A_earth_Z_out1[23:2]}) + $signed({1'b0, A_earth_Z_out1[1]});
  assign acc_linear_sub_cast_1 = {{3{Constant1_out1[15]}}, {Constant1_out1, 5'b00000}};
  assign acc_linear_out1 = acc_linear_sub_cast - acc_linear_sub_cast_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch2_process
      if (reset == 1'b1) begin
        acc_linear_out1_1 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          acc_linear_out1_1 <= acc_linear_out1;
        end
      end
    end

  assign stateControl_5 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        delayMatch1_reg <= {9{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch1_reg[0] <= stateControl_5;
          delayMatch1_reg[32'sd8:32'sd1] <= delayMatch1_reg[32'sd7:32'sd0];
        end
      end
    end

  assign stateControl_6 = delayMatch1_reg[8];

  assign kconst_2 = 15'b100000110001001;

  always @(posedge clk or posedge reset)
    begin : HwModeRegister13_process
      if (reset == 1'b1) begin
        kconst_3 <= 15'b000000000000000;
      end
      else begin
        if (enb) begin
          kconst_3 <= kconst_2;
        end
      end
    end

  // CHANGED: Using K_bias_in instead of the 24-bit hardcoded constant
  assign K_bias_out1 = K_bias_in * error_out1;

  assign K_bias_out1_1 = (((K_bias_out1[47] == 1'b0) && (K_bias_out1[46:41] != 6'b000000)) || ((K_bias_out1[47] == 1'b0) && (K_bias_out1[41:18] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((K_bias_out1[47] == 1'b1) && (K_bias_out1[46:41] != 6'b111111) ? 24'sb100000000000000000000000 :
              K_bias_out1[41:18] + $signed({1'b0, K_bias_out1[17]})));

  assign B_est_indtc = K_bias_out1_1;

  always @(posedge clk or posedge reset)
    begin : HwModeRegister12_process
      if (reset == 1'b1) begin
        B_est_indtc_1 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          B_est_indtc_1 <= B_est_indtc;
        end
      end
    end

  assign gain_cast = {1'b0, kconst_3};
  assign gain_mul_temp = B_est_indtc_1 * gain_cast;
  assign B_est_u_gain = gain_mul_temp[38:0];

  always @(posedge clk or posedge reset)
    begin : PipelineRegister6_process
      if (reset == 1'b1) begin
        B_est_u_gain_1 <= 39'sh0000000000;
      end
      else begin
        if (enb) begin
          B_est_u_gain_1 <= B_est_u_gain;
        end
      end
    end

  assign B_est_u_gain_2 = ({{7{B_est_u_gain_1[38]}}, B_est_u_gain_1[38:22]}) + $signed({1'b0, B_est_u_gain_1[21]});

  assign B_est_u_dtc = B_est_u_gain_2;

  assign adder_add_cast = {B_est_x_reg[23], B_est_x_reg};
  assign adder_add_cast_1 = {B_est_u_dtc[23], B_est_u_dtc};
  assign adder_add_temp = adder_add_cast + adder_add_cast_1;
  assign B_est_u_add = ((adder_add_temp[24] == 1'b0) && (adder_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((adder_add_temp[24] == 1'b1) && (adder_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(adder_add_temp[23:0])));

  assign B_est_x_reg_1 = (B_est_u_add > 24'sb000000100000000000000000 ? 24'sb000000100000000000000000 :
              (B_est_u_add < 24'sb111111100000000000000000 ? 24'sb111111100000000000000000 :
              B_est_u_add));

  always @(posedge clk or posedge reset)
    begin : reduced_2_process
      if (reset == 1'b1) begin
        B_est_x_reg <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          B_est_x_reg <= B_est_x_reg_2;
        end
      end
    end

  assign B_est_x_reg_2 = (stateControl_6 == 1'b0 ? B_est_x_reg :
              B_est_x_reg_1);

//  assign Acc_corrected_sub_cast = {acc_linear_out1_1[23], acc_linear_out1_1};
//  assign Acc_corrected_sub_cast_1 = {B_est_x_reg_2[23], B_est_x_reg_2};
//  assign Acc_corrected_sub_temp = Acc_corrected_sub_cast - Acc_corrected_sub_cast_1;
//  assign Acc_corrected_out1 = ((Acc_corrected_sub_temp[24] == 1'b0) && (Acc_corrected_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
//              ((Acc_corrected_sub_temp[24] == 1'b1) && (Acc_corrected_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
//              $signed(Acc_corrected_sub_temp[23:0])));

assign Acc_corrected_sub_cast = {acc_linear_out1_1[23], acc_linear_out1_1};
  
  // CHANGED: Replaced B_est_x_reg_2 with hardcoded 9.81 (sfix24_En16)
  assign Acc_corrected_sub_cast_1 = {1'b0, 24'sb000010011100111101011100}; 
  
  assign Acc_corrected_sub_temp = Acc_corrected_sub_cast - Acc_corrected_sub_cast_1;
  assign Acc_corrected_out1 = ((Acc_corrected_sub_temp[24] == 1'b0) && (Acc_corrected_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((Acc_corrected_sub_temp[24] == 1'b1) && (Acc_corrected_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(Acc_corrected_sub_temp[23:0])));

  // CHANGED: Using K_vel_in instead of the 32-bit hardcoded constant
  assign Kvel_out1 = K_vel_in * error_out1;

  assign Kvel_out1_1 = (((Kvel_out1[55] == 1'b0) && (Kvel_out1[54:43] != 12'b000000000000)) || ((Kvel_out1[55] == 1'b0) && (Kvel_out1[43:20] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Kvel_out1[55] == 1'b1) && (Kvel_out1[54:43] != 12'b111111111111) ? 24'sb100000000000000000000000 :
              Kvel_out1[43:20] + $signed({1'b0, Kvel_out1[19]})));

  always @(posedge clk or posedge reset)
    begin : delayMatch3_process
      if (reset == 1'b1) begin
        Kvel_out1_2 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          Kvel_out1_2 <= Kvel_out1_1;
        end
      end
    end

  assign Sum_add_cast = {Kvel_out1_2[23], Kvel_out1_2};
  assign Sum_add_cast_1 = ((Acc_corrected_out1[23] == 1'b0) && (Acc_corrected_out1[22:21] != 2'b00) ? 24'sb011111111111111111111111 :
              ((Acc_corrected_out1[23] == 1'b1) && (Acc_corrected_out1[22:21] != 2'b11) ? 24'sb100000000000000000000000 :
              {Acc_corrected_out1[21:0], 2'b00}));
  assign Sum_add_cast_2 = {Sum_add_cast_1[23], Sum_add_cast_1};
  assign Sum_add_temp = Sum_add_cast + Sum_add_cast_2;
  assign Sum_out1 = ((Sum_add_temp[24] == 1'b0) && (Sum_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((Sum_add_temp[24] == 1'b1) && (Sum_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(Sum_add_temp[23:0])));

  assign Vpred_indtc = Sum_out1;

  assign gain2_mul_temp = 15'sb010000011000101 * Vpred_indtc;
  assign Vpred_u_gain = gain2_mul_temp[37:0];

  assign Vpred_u_gain_1 = ({{9{Vpred_u_gain[37]}}, Vpred_u_gain[37:23]}) + $signed({1'b0, Vpred_u_gain[22]});

  assign Vpred_u_dtc = Vpred_u_gain_1;

  assign adder2_add_cast = {Vpred_x_reg[23], Vpred_x_reg};
  assign adder2_add_cast_1 = {Vpred_u_dtc[23], Vpred_u_dtc};
  assign adder2_add_temp = adder2_add_cast + adder2_add_cast_1;
  assign Vpred_x_reg_1 = ((adder2_add_temp[24] == 1'b0) && (adder2_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((adder2_add_temp[24] == 1'b1) && (adder2_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(adder2_add_temp[23:0])));

  always @(posedge clk or posedge reset)
    begin : reduced_3_process
      if (reset == 1'b1) begin
        Vpred_x_reg <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          Vpred_x_reg <= Vpred_x_reg_2;
        end
      end
    end

  assign Vpred_x_reg_2 = (stateControl_3 == 1'b0 ? Vpred_x_reg :
              Vpred_x_reg_1);

  assign error_sub_cast = ((barometer_1[23] == 1'b0) && (barometer_1[22:21] != 2'b00) ? 24'sb011111111111111111111111 :
              ((barometer_1[23] == 1'b1) && (barometer_1[22:21] != 2'b11) ? 24'sb100000000000000000000000 :
              {barometer_1[21:0], 2'b00}));
  assign error_sub_cast_1 = {error_sub_cast[23], error_sub_cast};
  assign error_sub_cast_2 = ((Discrete_Time_Integrator2_x_reg[23] == 1'b0) && (Discrete_Time_Integrator2_x_reg[22:21] != 2'b00) ? 24'sb011111111111111111111111 :
              ((Discrete_Time_Integrator2_x_reg[23] == 1'b1) && (Discrete_Time_Integrator2_x_reg[22:21] != 2'b11) ? 24'sb100000000000000000000000 :
              {Discrete_Time_Integrator2_x_reg[21:0], 2'b00}));
  assign error_sub_cast_3 = {error_sub_cast_2[23], error_sub_cast_2};
  assign error_sub_temp = error_sub_cast_1 - error_sub_cast_3;
  assign error_out1 = ((error_sub_temp[24] == 1'b0) && (error_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((error_sub_temp[24] == 1'b1) && (error_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(error_sub_temp[23:0])));

  // CHANGED: Using K_pos_in instead of the 24-bit hardcoded constant
  assign K_pos_out1 = K_pos_in * error_out1;

  assign K_pos_out1_1 = (((K_pos_out1[47] == 1'b0) && (K_pos_out1[46:43] != 4'b0000)) || ((K_pos_out1[47] == 1'b0) && (K_pos_out1[43:20] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((K_pos_out1[47] == 1'b1) && (K_pos_out1[46:43] != 4'b1111) ? 24'sb100000000000000000000000 :
              K_pos_out1[43:20] + $signed({1'b0, K_pos_out1[19]})));

  assign Sum1_add_cast = {K_pos_out1_1[23], K_pos_out1_1};
  assign Sum1_add_cast_1 = {Vpred_x_reg_2[23], Vpred_x_reg_2};
  assign Sum1_add_temp = Sum1_add_cast + Sum1_add_cast_1;
  assign Sum1_out1 = ((Sum1_add_temp[24] == 1'b0) && (Sum1_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((Sum1_add_temp[24] == 1'b1) && (Sum1_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(Sum1_add_temp[23:0])));

  assign Discrete_Time_Integrator2_indtc = Sum1_out1;

  assign gain1_mul_temp = 16'sb0100000110001001 * Discrete_Time_Integrator2_indtc;
  assign Discrete_Time_Integrator2_u_gain = gain1_mul_temp[38:0];

  assign Discrete_Time_Integrator2_u_gain_1 = ({{7{Discrete_Time_Integrator2_u_gain[38]}}, Discrete_Time_Integrator2_u_gain[38:22]}) + $signed({1'b0, Discrete_Time_Integrator2_u_gain[21]});

  assign Discrete_Time_Integrator2_u_dtc = Discrete_Time_Integrator2_u_gain_1;

  assign adder1_add_cast = {Discrete_Time_Integrator2_x_reg[23], Discrete_Time_Integrator2_x_reg};
  assign adder1_add_cast_1 = {Discrete_Time_Integrator2_u_dtc[23], Discrete_Time_Integrator2_u_dtc};
  assign adder1_add_temp = adder1_add_cast + adder1_add_cast_1;
  assign Discrete_Time_Integrator2_u_add = ((adder1_add_temp[24] == 1'b0) && (adder1_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((adder1_add_temp[24] == 1'b1) && (adder1_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(adder1_add_temp[23:0])));

  assign Discrete_Time_Integrator2_u_add_1 = (stateControl_1 == 1'b0 ? Discrete_Time_Integrator2_x_reg :
              Discrete_Time_Integrator2_u_add);

  always @(posedge clk or posedge reset)
    begin : Discrete_Time_Integrator2_reg_process
      if (reset == 1'b1) begin
        Discrete_Time_Integrator2_x_reg <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          Discrete_Time_Integrator2_x_reg <= Discrete_Time_Integrator2_u_add_1;
        end
      end
    end

  assign Z_est = Discrete_Time_Integrator2_x_reg;

  assign V_est = Vpred_x_reg_2;

  assign ce_out = clk_enable;

endmodule  // alpha3rd_order_filter


//// -------------------------------------------------------------
//// 
//// Module: alpha3rd_order_filter
//// Source Path: experimental_model/3rd_order_filter
//// Hierarchy Level: 0
//// Model version: 4.36
//// 
//// -------------------------------------------------------------

//`timescale 1 ns / 1 ns

//module alpha3rd_order_filter
//          (clk,
//           reset,
//           clk_enable,
//           barometer,
//           angles_0,
//           angles_1,
//           accelrometer_0,
//           accelrometer_1,
//           accelrometer_2,
//           ce_out,
//           Z_est,
//           V_est);


//  input   clk;
//  input   reset;
//  input   clk_enable;
//  input   signed [23:0] barometer;  // sfix24_En16
//  input   signed [23:0] angles_0;  // sfix24_En16
//  input   signed [23:0] angles_1;  // sfix24_En16
//  input   signed [23:0] accelrometer_0;  // sfix24_En16
//  input   signed [23:0] accelrometer_1;  // sfix24_En16
//  input   signed [23:0] accelrometer_2;  // sfix24_En16
//  output  ce_out;
//  output  signed [23:0] Z_est;  // sfix24_En16
//  output  signed [23:0] V_est;  // sfix24_En16


//  wire enb;
//  wire stateControl;
//  reg  [6:0] delayMatch14_reg;  // ufix1 [7]
//  wire stateControl_1;
//  reg signed [23:0] delayMatch13_reg [0:6];  // sfix24 [7]
//  reg signed [23:0] delayMatch13_reg_next [0:6];  // sfix24_En16 [7]
//  reg signed [23:0] barometer_1;  // sfix24_En16
//  wire stateControl_2;
//  reg  [7:0] delayMatch5_reg;  // ufix1 [8]
//  wire stateControl_3;
//  reg signed [23:0] HwModeRegister2_reg [0:3];  // sfix24 [4]
//  reg signed [23:0] HwModeRegister2_reg_next [0:3];  // sfix24_En16 [4]
//  reg signed [23:0] accelrometer_1_1;  // sfix24_En16
//  wire signed [23:0] angles [0:1];  // sfix24_En16 [2]
//  reg signed [23:0] angles_2 [0:1];  // sfix24_En16 [2]
//  wire signed [15:0] kconst;  // sfix16_En14
//  reg signed [15:0] kconst_1;  // sfix16_En14
//  wire signed [39:0] Gain_out1 [0:1];  // sfix40_En30 [2]
//  reg signed [39:0] Gain_out1_1 [0:1];  // sfix40_En30 [2]
//  wire signed [15:0] Gain_out1_2 [0:1];  // sfix16_En12 [2]
//  wire signed [16:0] Sine_HDL_Optimized1_x;  // sfix17_En14
//  reg signed [16:0] Sine_HDL_Optimized1_x_1;  // sfix17_En14
//  wire signed [40:0] ay_sinphi_out1;  // sfix41_En30
//  reg signed [40:0] ay_sinphi_out1_1;  // sfix41_En30
//  wire signed [23:0] ay_sinphi_out1_2;  // sfix24_En18
//  reg signed [23:0] ay_sinphi_out1_3;  // sfix24_En18
//  wire signed [16:0] Cosine_HDL_Optimized1_x;  // sfix17_En14
//  reg signed [16:0] Cosine_HDL_Optimized1_x_1;  // sfix17_En14
//  reg signed [16:0] reduced_reg [0:1];  // sfix17 [2]
//  wire signed [16:0] reduced_reg_next [0:1];  // sfix17_En14 [2]
//  wire signed [16:0] Cosine_HDL_Optimized1_x_2;  // sfix17_En14
//  wire signed [40:0] ay_sinphi_costheta_out1;  // sfix41_En32
//  reg signed [40:0] ay_sinphi_costheta_out1_1;  // sfix41_En32
//  wire signed [23:0] ay_sinphi_costheta_out1_2;  // sfix24_En18
//  reg signed [23:0] HwModeRegister_reg [0:3];  // sfix24 [4]
//  reg signed [23:0] HwModeRegister_reg_next [0:3];  // sfix24_En16 [4]
//  reg signed [23:0] accelrometer_0_1;  // sfix24_En16
//  wire signed [16:0] Sine_HDL_Optimized_x;  // sfix17_En14
//  reg signed [16:0] Sine_HDL_Optimized_x_1;  // sfix17_En14
//  wire signed [40:0] ax_sintheta_out1;  // sfix41_En30
//  reg signed [40:0] ax_sintheta_out1_1;  // sfix41_En30
//  wire signed [23:0] ax_sintheta_out1_2;  // sfix24_En18
//  reg signed [23:0] HwModeRegister6_reg [0:5];  // sfix24 [6]
//  reg signed [23:0] HwModeRegister6_reg_next [0:5];  // sfix24_En16 [6]
//  reg signed [23:0] accelrometer_2_1;  // sfix24_En16
//  wire signed [16:0] Cosine_HDL_Optimized_x;  // sfix17_En14
//  reg signed [16:0] Cosine_HDL_Optimized_x_1;  // sfix17_En14
//  wire signed [33:0] costheta_cosphi_out1;  // sfix34_En28
//  reg signed [33:0] costheta_cosphi_out1_1;  // sfix34_En28
//  wire signed [23:0] costheta_cosphi_out1_2;  // sfix24_En18
//  reg signed [23:0] costheta_cosphi_out1_3;  // sfix24_En18
//  wire signed [47:0] az_costheta_cosphi_out1;  // sfix48_En34
//  reg signed [23:0] delayMatch9_reg [0:1];  // sfix24 [2]
//  wire signed [23:0] delayMatch9_reg_next [0:1];  // sfix24_En18 [2]
//  wire signed [23:0] ax_sintheta_out1_3;  // sfix24_En18
//  wire signed [24:0] A_earth_Z_stage2_sub_cast;  // sfix25_En18
//  wire signed [24:0] A_earth_Z_stage2_sub_cast_1;  // sfix25_En18
//  wire signed [24:0] A_earth_Z_stage2_sub_temp;  // sfix25_En18
//  wire signed [23:0] A_earth_Z_stage2_cast;  // sfix24_En18
//  wire signed [24:0] A_earth_Z_op_stage1;  // sfix25_En18
//  reg signed [47:0] az_costheta_cosphi_out1_1;  // sfix48_En34
//  wire signed [23:0] az_costheta_cosphi_out1_2;  // sfix24_En18
//  wire signed [23:0] A_earth_Z_stage3_add_cast;  // sfix24_En18
//  wire signed [24:0] A_earth_Z_stage3_add_cast_1;  // sfix25_En18
//  wire signed [24:0] A_earth_Z_stage3_add_cast_2;  // sfix25_En18
//  wire signed [24:0] A_earth_Z_stage3_add_temp;  // sfix25_En18
//  wire signed [23:0] A_earth_Z_out1;  // sfix24_En18
//  wire signed [15:0] Constant1_out1;  // sfix16_En11
//  wire signed [23:0] acc_linear_sub_cast;  // sfix24_En16
//  wire signed [23:0] acc_linear_sub_cast_1;  // sfix24_En16
//  wire signed [23:0] acc_linear_out1;  // sfix24_En16
//  reg signed [23:0] acc_linear_out1_1;  // sfix24_En16
//  wire stateControl_5;
//  reg  [8:0] delayMatch1_reg;  // ufix1 [9]
//  wire stateControl_6;
//  wire [14:0] kconst_2;  // ufix15_En22
//  reg [14:0] kconst_3;  // ufix15_En22
//  wire signed [23:0] error_out1;  // sfix24_En18
//  wire signed [47:0] K_bias_out1;  // sfix48_En34
//  wire signed [23:0] K_bias_out1_1;  // sfix24_En16
//  wire signed [23:0] B_est_indtc;  // sfix24
//  reg signed [23:0] B_est_indtc_1;  // sfix24
//  wire signed [15:0] gain_cast;  // sfix16_En22
//  wire signed [39:0] gain_mul_temp;  // sfix40_En22
//  wire signed [38:0] B_est_u_gain;  // sfix39_En22
//  reg signed [38:0] B_est_u_gain_1;  // sfix39_En22
//  wire signed [23:0] B_est_u_gain_2;  // sfix24
//  wire signed [23:0] B_est_u_dtc;  // sfix24_En16
//  reg signed [23:0] B_est_x_reg;  // sfix24_En16
//  wire signed [24:0] adder_add_cast;  // sfix25_En16
//  wire signed [24:0] adder_add_cast_1;  // sfix25_En16
//  wire signed [24:0] adder_add_temp;  // sfix25_En16
//  wire signed [23:0] B_est_u_add;  // sfix24_En16
//  wire signed [23:0] B_est_x_reg_1;  // sfix24_En16
//  wire signed [23:0] B_est_x_reg_2;  // sfix24_En16
//  wire signed [24:0] Acc_corrected_sub_cast;  // sfix25_En16
//  wire signed [24:0] Acc_corrected_sub_cast_1;  // sfix25_En16
//  wire signed [24:0] Acc_corrected_sub_temp;  // sfix25_En16
//  wire signed [23:0] Acc_corrected_out1;  // sfix24_En16
//  wire signed [55:0] Kvel_out1;  // sfix56_En38
//  wire signed [23:0] Kvel_out1_1;  // sfix24_En18
//  reg signed [23:0] Kvel_out1_2;  // sfix24_En18
//  wire signed [24:0] Sum_add_cast;  // sfix25_En18
//  wire signed [23:0] Sum_add_cast_1;  // sfix24_En18
//  wire signed [24:0] Sum_add_cast_2;  // sfix25_En18
//  wire signed [24:0] Sum_add_temp;  // sfix25_En18
//  wire signed [23:0] Sum_out1;  // sfix24_En18
//  wire signed [23:0] Vpred_indtc;  // sfix24
//  wire signed [38:0] gain2_mul_temp;  // sfix39_En23
//  wire signed [37:0] Vpred_u_gain;  // sfix38_En23
//  wire signed [23:0] Vpred_u_gain_1;  // sfix24
//  wire signed [23:0] Vpred_u_dtc;  // sfix24_En16
//  reg signed [23:0] Vpred_x_reg;  // sfix24_En16
//  wire signed [24:0] adder2_add_cast;  // sfix25_En16
//  wire signed [24:0] adder2_add_cast_1;  // sfix25_En16
//  wire signed [24:0] adder2_add_temp;  // sfix25_En16
//  wire signed [23:0] Vpred_x_reg_1;  // sfix24_En16
//  wire signed [23:0] Vpred_x_reg_2;  // sfix24_En16
//  reg signed [23:0] Discrete_Time_Integrator2_x_reg;  // sfix24_En16
//  wire signed [23:0] error_sub_cast;  // sfix24_En18
//  wire signed [24:0] error_sub_cast_1;  // sfix25_En18
//  wire signed [23:0] error_sub_cast_2;  // sfix24_En18
//  wire signed [24:0] error_sub_cast_3;  // sfix25_En18
//  wire signed [24:0] error_sub_temp;  // sfix25_En18
//  wire signed [47:0] K_pos_out1;  // sfix48_En36
//  wire signed [23:0] K_pos_out1_1;  // sfix24_En16
//  wire signed [24:0] Sum1_add_cast;  // sfix25_En16
//  wire signed [24:0] Sum1_add_cast_1;  // sfix25_En16
//  wire signed [24:0] Sum1_add_temp;  // sfix25_En16
//  wire signed [23:0] Sum1_out1;  // sfix24_En16
//  wire signed [23:0] Discrete_Time_Integrator2_indtc;  // sfix24
//  wire signed [39:0] gain1_mul_temp;  // sfix40_En22
//  wire signed [38:0] Discrete_Time_Integrator2_u_gain;  // sfix39_En22
//  wire signed [23:0] Discrete_Time_Integrator2_u_gain_1;  // sfix24
//  wire signed [23:0] Discrete_Time_Integrator2_u_dtc;  // sfix24_En16
//  wire signed [24:0] adder1_add_cast;  // sfix25_En16
//  wire signed [24:0] adder1_add_cast_1;  // sfix25_En16
//  wire signed [24:0] adder1_add_temp;  // sfix25_En16
//  wire signed [23:0] Discrete_Time_Integrator2_u_add;  // sfix24_En16
//  wire signed [23:0] Discrete_Time_Integrator2_u_add_1;  // sfix24_En16
//  reg signed [31:0] delayMatch13_t_0_0;  // int32
//  reg signed [31:0] delayMatch13_t_0_1;  // int32
//  reg signed [31:0] delayMatch13_t_1;  // int32
//  reg signed [31:0] HwModeRegister2_t_0_0;  // int32
//  reg signed [31:0] HwModeRegister2_t_0_1;  // int32
//  reg signed [31:0] HwModeRegister2_t_1;  // int32
//  reg signed [31:0] HwModeRegister10_t_0_0;  // int32
//  reg signed [31:0] HwModeRegister10_t_1;  // int32
//  reg signed [31:0] PipelineRegister5_t_0_0;  // int32
//  reg signed [31:0] PipelineRegister5_t_1;  // int32
//  reg signed [31:0] reduced_t_0_0;  // int32
//  reg signed [31:0] reduced_t_1;  // int32
//  reg signed [31:0] HwModeRegister_t_0_0;  // int32
//  reg signed [31:0] HwModeRegister_t_0_1;  // int32
//  reg signed [31:0] HwModeRegister_t_1;  // int32
//  reg signed [31:0] HwModeRegister6_t_0_0;  // int32
//  reg signed [31:0] HwModeRegister6_t_0_1;  // int32
//  reg signed [31:0] HwModeRegister6_t_1;  // int32
//  reg signed [31:0] delayMatch9_t_0_0;  // int32
//  reg signed [31:0] delayMatch9_t_1;  // int32


//  assign stateControl = 1'b1;

//  assign enb = clk_enable;

//  always @(posedge clk or posedge reset)
//    begin : delayMatch14_process
//      if (reset == 1'b1) begin
//        delayMatch14_reg <= {7{1'b0}};
//      end
//      else begin
//        if (enb) begin
//          delayMatch14_reg[0] <= stateControl;
//          delayMatch14_reg[32'sd6:32'sd1] <= delayMatch14_reg[32'sd5:32'sd0];
//        end
//      end
//    end

//  assign stateControl_1 = delayMatch14_reg[6];

//  always @(posedge clk or posedge reset)
//    begin : delayMatch13_process
//      if (reset == 1'b1) begin
//        for(delayMatch13_t_1 = 32'sd0; delayMatch13_t_1 <= 32'sd6; delayMatch13_t_1 = delayMatch13_t_1 + 32'sd1) begin
//          delayMatch13_reg[delayMatch13_t_1] <= 24'sb000000000000000000000000;
//        end
//      end
//      else begin
//        if (enb) begin
//          for(delayMatch13_t_0_1 = 32'sd0; delayMatch13_t_0_1 <= 32'sd6; delayMatch13_t_0_1 = delayMatch13_t_0_1 + 32'sd1) begin
//            delayMatch13_reg[delayMatch13_t_0_1] <= delayMatch13_reg_next[delayMatch13_t_0_1];
//          end
//        end
//      end
//    end

//  always @* begin
//    barometer_1 = delayMatch13_reg[6];
//    delayMatch13_reg_next[0] = barometer;

//    for(delayMatch13_t_0_0 = 32'sd0; delayMatch13_t_0_0 <= 32'sd5; delayMatch13_t_0_0 = delayMatch13_t_0_0 + 32'sd1) begin
//      delayMatch13_reg_next[delayMatch13_t_0_0 + 32'sd1] = delayMatch13_reg[delayMatch13_t_0_0];
//    end

//  end

//  assign stateControl_2 = 1'b1;

//  always @(posedge clk or posedge reset)
//    begin : delayMatch5_process
//      if (reset == 1'b1) begin
//        delayMatch5_reg <= {8{1'b0}};
//      end
//      else begin
//        if (enb) begin
//          delayMatch5_reg[0] <= stateControl_2;
//          delayMatch5_reg[32'sd7:32'sd1] <= delayMatch5_reg[32'sd6:32'sd0];
//        end
//      end
//    end

//  assign stateControl_3 = delayMatch5_reg[7];

//  always @(posedge clk or posedge reset)
//    begin : HwModeRegister2_process
//      if (reset == 1'b1) begin
//        for(HwModeRegister2_t_1 = 32'sd0; HwModeRegister2_t_1 <= 32'sd3; HwModeRegister2_t_1 = HwModeRegister2_t_1 + 32'sd1) begin
//          HwModeRegister2_reg[HwModeRegister2_t_1] <= 24'sb000000000000000000000000;
//        end
//      end
//      else begin
//        if (enb) begin
//          for(HwModeRegister2_t_0_1 = 32'sd0; HwModeRegister2_t_0_1 <= 32'sd3; HwModeRegister2_t_0_1 = HwModeRegister2_t_0_1 + 32'sd1) begin
//            HwModeRegister2_reg[HwModeRegister2_t_0_1] <= HwModeRegister2_reg_next[HwModeRegister2_t_0_1];
//          end
//        end
//      end
//    end

//  always @* begin
//    accelrometer_1_1 = HwModeRegister2_reg[3];
//    HwModeRegister2_reg_next[0] = accelrometer_1;

//    for(HwModeRegister2_t_0_0 = 32'sd0; HwModeRegister2_t_0_0 <= 32'sd2; HwModeRegister2_t_0_0 = HwModeRegister2_t_0_0 + 32'sd1) begin
//      HwModeRegister2_reg_next[HwModeRegister2_t_0_0 + 32'sd1] = HwModeRegister2_reg[HwModeRegister2_t_0_0];
//    end

//  end

//  assign angles[0] = angles_0;
//  assign angles[1] = angles_1;

//  always @(posedge clk or posedge reset)
//    begin : HwModeRegister10_process
//      if (reset == 1'b1) begin
//        for(HwModeRegister10_t_1 = 32'sd0; HwModeRegister10_t_1 <= 32'sd1; HwModeRegister10_t_1 = HwModeRegister10_t_1 + 32'sd1) begin
//          angles_2[HwModeRegister10_t_1] <= 24'sb000000000000000000000000;
//        end
//      end
//      else begin
//        if (enb) begin
//          for(HwModeRegister10_t_0_0 = 32'sd0; HwModeRegister10_t_0_0 <= 32'sd1; HwModeRegister10_t_0_0 = HwModeRegister10_t_0_0 + 32'sd1) begin
//            angles_2[HwModeRegister10_t_0_0] <= angles[HwModeRegister10_t_0_0];
//          end
//        end
//      end
//    end

//  assign kconst = 16'sb0000101000110000;

//  always @(posedge clk or posedge reset)
//    begin : HwModeRegister11_process
//      if (reset == 1'b1) begin
//        kconst_1 <= 16'sb0000000000000000;
//      end
//      else begin
//        if (enb) begin
//          kconst_1 <= kconst;
//        end
//      end
//    end


//  genvar t_0_0;
//  generate
//    for(t_0_0 = 32'sd0; t_0_0 <= 32'sd1; t_0_0 = t_0_0 + 32'sd1) begin:Gain_out1_gen
//      assign Gain_out1[t_0_0] = angles_2[t_0_0] * kconst_1;
//    end
//  endgenerate

//  always @(posedge clk or posedge reset)
//    begin : PipelineRegister5_process
//      if (reset == 1'b1) begin
//        for(PipelineRegister5_t_1 = 32'sd0; PipelineRegister5_t_1 <= 32'sd1; PipelineRegister5_t_1 = PipelineRegister5_t_1 + 32'sd1) begin
//          Gain_out1_1[PipelineRegister5_t_1] <= 40'sh0000000000;
//        end
//      end
//      else begin
//        if (enb) begin
//          for(PipelineRegister5_t_0_0 = 32'sd0; PipelineRegister5_t_0_0 <= 32'sd1; PipelineRegister5_t_0_0 = PipelineRegister5_t_0_0 + 32'sd1) begin
//            Gain_out1_1[PipelineRegister5_t_0_0] <= Gain_out1[PipelineRegister5_t_0_0];
//          end
//        end
//      end
//    end


//  genvar ii;
//  generate
//    for(ii = 32'sd0; ii <= 32'sd1; ii = ii + 32'sd1) begin:Gain_out1_2_gen
//      assign Gain_out1_2[ii] = (((Gain_out1_1[ii][39] == 1'b0) && (Gain_out1_1[ii][38:33] != 6'b000000)) || ((Gain_out1_1[ii][39] == 1'b0) && (Gain_out1_1[ii][33:18] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
//                  ((Gain_out1_1[ii][39] == 1'b1) && (Gain_out1_1[ii][38:33] != 6'b111111) ? 16'sb1000000000000000 :
//                  Gain_out1_1[ii][33:18] + $signed({1'b0, Gain_out1_1[ii][17]})));
//    end
//  endgenerate

//  Sine_HDL_Optimized1 u_Sine_HDL_Optimized1 (.clk(clk),
//                                             .reset(reset),
//                                             .enb(clk_enable),
//                                             .u(Gain_out1_2[0]),  // sfix16_En12
//                                             .x(Sine_HDL_Optimized1_x)  // sfix17_En14
//                                             );

//  always @(posedge clk or posedge reset)
//    begin : HwModeRegister3_process
//      if (reset == 1'b1) begin
//        Sine_HDL_Optimized1_x_1 <= 17'sb00000000000000000;
//      end
//      else begin
//        if (enb) begin
//          Sine_HDL_Optimized1_x_1 <= Sine_HDL_Optimized1_x;
//        end
//      end
//    end

//  assign ay_sinphi_out1 = accelrometer_1_1 * Sine_HDL_Optimized1_x_1;

//  always @(posedge clk or posedge reset)
//    begin : PipelineRegister1_process
//      if (reset == 1'b1) begin
//        ay_sinphi_out1_1 <= 41'sh00000000000;
//      end
//      else begin
//        if (enb) begin
//          ay_sinphi_out1_1 <= ay_sinphi_out1;
//        end
//      end
//    end

//  assign ay_sinphi_out1_2 = (((ay_sinphi_out1_1[40] == 1'b0) && (ay_sinphi_out1_1[39:35] != 5'b00000)) || ((ay_sinphi_out1_1[40] == 1'b0) && (ay_sinphi_out1_1[35:12] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
//              ((ay_sinphi_out1_1[40] == 1'b1) && (ay_sinphi_out1_1[39:35] != 5'b11111) ? 24'sb100000000000000000000000 :
//              ay_sinphi_out1_1[35:12] + $signed({1'b0, ay_sinphi_out1_1[11]})));

//  always @(posedge clk or posedge reset)
//    begin : HwModeRegister4_process
//      if (reset == 1'b1) begin
//        ay_sinphi_out1_3 <= 24'sb000000000000000000000000;
//      end
//      else begin
//        if (enb) begin
//          ay_sinphi_out1_3 <= ay_sinphi_out1_2;
//        end
//      end
//    end

//  Cosine_HDL_Optimized1 u_Cosine_HDL_Optimized1 (.clk(clk),
//                                                 .reset(reset),
//                                                 .enb(clk_enable),
//                                                 .u(Gain_out1_2[1]),  // sfix16_En12
//                                                 .x(Cosine_HDL_Optimized1_x)  // sfix17_En14
//                                                 );

//  always @(posedge clk or posedge reset)
//    begin : reduced_process
//      if (reset == 1'b1) begin
//        Cosine_HDL_Optimized1_x_1 <= 17'sb00000000000000000;
//      end
//      else begin
//        if (enb) begin
//          Cosine_HDL_Optimized1_x_1 <= Cosine_HDL_Optimized1_x;
//        end
//      end
//    end

//  always @(posedge clk or posedge reset)
//    begin : reduced_1_process
//      if (reset == 1'b1) begin
//        for(reduced_t_1 = 32'sd0; reduced_t_1 <= 32'sd1; reduced_t_1 = reduced_t_1 + 32'sd1) begin
//          reduced_reg[reduced_t_1] <= 17'sb00000000000000000;
//        end
//      end
//      else begin
//        if (enb) begin
//          for(reduced_t_0_0 = 32'sd0; reduced_t_0_0 <= 32'sd1; reduced_t_0_0 = reduced_t_0_0 + 32'sd1) begin
//            reduced_reg[reduced_t_0_0] <= reduced_reg_next[reduced_t_0_0];
//          end
//        end
//      end
//    end

//  assign Cosine_HDL_Optimized1_x_2 = reduced_reg[1];
//  assign reduced_reg_next[0] = Cosine_HDL_Optimized1_x_1;
//  assign reduced_reg_next[1] = reduced_reg[0];

//  assign ay_sinphi_costheta_out1 = ay_sinphi_out1_3 * Cosine_HDL_Optimized1_x_2;

//  always @(posedge clk or posedge reset)
//    begin : PipelineRegister2_process
//      if (reset == 1'b1) begin
//        ay_sinphi_costheta_out1_1 <= 41'sh00000000000;
//      end
//      else begin
//        if (enb) begin
//          ay_sinphi_costheta_out1_1 <= ay_sinphi_costheta_out1;
//        end
//      end
//    end

//  assign ay_sinphi_costheta_out1_2 = (((ay_sinphi_costheta_out1_1[40] == 1'b0) && (ay_sinphi_costheta_out1_1[39:37] != 3'b000)) || ((ay_sinphi_costheta_out1_1[40] == 1'b0) && (ay_sinphi_costheta_out1_1[37:14] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
//              ((ay_sinphi_costheta_out1_1[40] == 1'b1) && (ay_sinphi_costheta_out1_1[39:37] != 3'b111) ? 24'sb100000000000000000000000 :
//              ay_sinphi_costheta_out1_1[37:14] + $signed({1'b0, ay_sinphi_costheta_out1_1[13]})));

//  always @(posedge clk or posedge reset)
//    begin : HwModeRegister_process
//      if (reset == 1'b1) begin
//        for(HwModeRegister_t_1 = 32'sd0; HwModeRegister_t_1 <= 32'sd3; HwModeRegister_t_1 = HwModeRegister_t_1 + 32'sd1) begin
//          HwModeRegister_reg[HwModeRegister_t_1] <= 24'sb000000000000000000000000;
//        end
//      end
//      else begin
//        if (enb) begin
//          for(HwModeRegister_t_0_1 = 32'sd0; HwModeRegister_t_0_1 <= 32'sd3; HwModeRegister_t_0_1 = HwModeRegister_t_0_1 + 32'sd1) begin
//            HwModeRegister_reg[HwModeRegister_t_0_1] <= HwModeRegister_reg_next[HwModeRegister_t_0_1];
//          end
//        end
//      end
//    end

//  always @* begin
//    accelrometer_0_1 = HwModeRegister_reg[3];
//    HwModeRegister_reg_next[0] = accelrometer_0;

//    for(HwModeRegister_t_0_0 = 32'sd0; HwModeRegister_t_0_0 <= 32'sd2; HwModeRegister_t_0_0 = HwModeRegister_t_0_0 + 32'sd1) begin
//      HwModeRegister_reg_next[HwModeRegister_t_0_0 + 32'sd1] = HwModeRegister_reg[HwModeRegister_t_0_0];
//    end

//  end

//  Sine_HDL_Optimized u_Sine_HDL_Optimized (.clk(clk),
//                                           .reset(reset),
//                                           .enb(clk_enable),
//                                           .u(Gain_out1_2[1]),  // sfix16_En12
//                                           .x(Sine_HDL_Optimized_x)  // sfix17_En14
//                                           );

//  always @(posedge clk or posedge reset)
//    begin : HwModeRegister1_process
//      if (reset == 1'b1) begin
//        Sine_HDL_Optimized_x_1 <= 17'sb00000000000000000;
//      end
//      else begin
//        if (enb) begin
//          Sine_HDL_Optimized_x_1 <= Sine_HDL_Optimized_x;
//        end
//      end
//    end

//  assign ax_sintheta_out1 = accelrometer_0_1 * Sine_HDL_Optimized_x_1;

//  always @(posedge clk or posedge reset)
//    begin : PipelineRegister_process
//      if (reset == 1'b1) begin
//        ax_sintheta_out1_1 <= 41'sh00000000000;
//      end
//      else begin
//        if (enb) begin
//          ax_sintheta_out1_1 <= ax_sintheta_out1;
//        end
//      end
//    end

//  assign ax_sintheta_out1_2 = (((ax_sintheta_out1_1[40] == 1'b0) && (ax_sintheta_out1_1[39:35] != 5'b00000)) || ((ax_sintheta_out1_1[40] == 1'b0) && (ax_sintheta_out1_1[35:12] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
//              ((ax_sintheta_out1_1[40] == 1'b1) && (ax_sintheta_out1_1[39:35] != 5'b11111) ? 24'sb100000000000000000000000 :
//              ax_sintheta_out1_1[35:12] + $signed({1'b0, ax_sintheta_out1_1[11]})));

//  always @(posedge clk or posedge reset)
//    begin : HwModeRegister6_process
//      if (reset == 1'b1) begin
//        for(HwModeRegister6_t_1 = 32'sd0; HwModeRegister6_t_1 <= 32'sd5; HwModeRegister6_t_1 = HwModeRegister6_t_1 + 32'sd1) begin
//          HwModeRegister6_reg[HwModeRegister6_t_1] <= 24'sb000000000000000000000000;
//        end
//      end
//      else begin
//        if (enb) begin
//          for(HwModeRegister6_t_0_1 = 32'sd0; HwModeRegister6_t_0_1 <= 32'sd5; HwModeRegister6_t_0_1 = HwModeRegister6_t_0_1 + 32'sd1) begin
//            HwModeRegister6_reg[HwModeRegister6_t_0_1] <= HwModeRegister6_reg_next[HwModeRegister6_t_0_1];
//          end
//        end
//      end
//    end

//  always @* begin
//    accelrometer_2_1 = HwModeRegister6_reg[5];
//    HwModeRegister6_reg_next[0] = accelrometer_2;

//    for(HwModeRegister6_t_0_0 = 32'sd0; HwModeRegister6_t_0_0 <= 32'sd4; HwModeRegister6_t_0_0 = HwModeRegister6_t_0_0 + 32'sd1) begin
//      HwModeRegister6_reg_next[HwModeRegister6_t_0_0 + 32'sd1] = HwModeRegister6_reg[HwModeRegister6_t_0_0];
//    end

//  end

//  Cosine_HDL_Optimized u_Cosine_HDL_Optimized (.clk(clk),
//                                               .reset(reset),
//                                               .enb(clk_enable),
//                                               .u(Gain_out1_2[0]),  // sfix16_En12
//                                               .x(Cosine_HDL_Optimized_x)  // sfix17_En14
//                                               );

//  always @(posedge clk or posedge reset)
//    begin : HwModeRegister8_process
//      if (reset == 1'b1) begin
//        Cosine_HDL_Optimized_x_1 <= 17'sb00000000000000000;
//      end
//      else begin
//        if (enb) begin
//          Cosine_HDL_Optimized_x_1 <= Cosine_HDL_Optimized_x;
//        end
//      end
//    end

//  assign costheta_cosphi_out1 = Cosine_HDL_Optimized_x_1 * Cosine_HDL_Optimized1_x_1;

//  always @(posedge clk or posedge reset)
//    begin : PipelineRegister4_process
//      if (reset == 1'b1) begin
//        costheta_cosphi_out1_1 <= 34'sh000000000;
//      end
//      else begin
//        if (enb) begin
//          costheta_cosphi_out1_1 <= costheta_cosphi_out1;
//        end
//      end
//    end

//  assign costheta_cosphi_out1_2 = ((costheta_cosphi_out1_1[33] == 1'b0) && (costheta_cosphi_out1_1[32:10] == 23'b11111111111111111111111) ? 24'sb011111111111111111111111 :
//              costheta_cosphi_out1_1[33:10] + $signed({1'b0, costheta_cosphi_out1_1[9]}));

//  always @(posedge clk or posedge reset)
//    begin : HwModeRegister7_process
//      if (reset == 1'b1) begin
//        costheta_cosphi_out1_3 <= 24'sb000000000000000000000000;
//      end
//      else begin
//        if (enb) begin
//          costheta_cosphi_out1_3 <= costheta_cosphi_out1_2;
//        end
//      end
//    end

//  assign az_costheta_cosphi_out1 = accelrometer_2_1 * costheta_cosphi_out1_3;

//  always @(posedge clk or posedge reset)
//    begin : delayMatch9_process
//      if (reset == 1'b1) begin
//        for(delayMatch9_t_1 = 32'sd0; delayMatch9_t_1 <= 32'sd1; delayMatch9_t_1 = delayMatch9_t_1 + 32'sd1) begin
//          delayMatch9_reg[delayMatch9_t_1] <= 24'sb000000000000000000000000;
//        end
//      end
//      else begin
//        if (enb) begin
//          for(delayMatch9_t_0_0 = 32'sd0; delayMatch9_t_0_0 <= 32'sd1; delayMatch9_t_0_0 = delayMatch9_t_0_0 + 32'sd1) begin
//            delayMatch9_reg[delayMatch9_t_0_0] <= delayMatch9_reg_next[delayMatch9_t_0_0];
//          end
//        end
//      end
//    end

//  assign ax_sintheta_out1_3 = delayMatch9_reg[1];
//  assign delayMatch9_reg_next[0] = ax_sintheta_out1_2;
//  assign delayMatch9_reg_next[1] = delayMatch9_reg[0];

//  assign A_earth_Z_stage2_sub_cast = {ay_sinphi_costheta_out1_2[23], ay_sinphi_costheta_out1_2};
//  assign A_earth_Z_stage2_sub_cast_1 = {ax_sintheta_out1_3[23], ax_sintheta_out1_3};
//  assign A_earth_Z_stage2_sub_temp = A_earth_Z_stage2_sub_cast - A_earth_Z_stage2_sub_cast_1;
//  assign A_earth_Z_stage2_cast = ((A_earth_Z_stage2_sub_temp[24] == 1'b0) && (A_earth_Z_stage2_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
//              ((A_earth_Z_stage2_sub_temp[24] == 1'b1) && (A_earth_Z_stage2_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
//              $signed(A_earth_Z_stage2_sub_temp[23:0])));
//  assign A_earth_Z_op_stage1 = {A_earth_Z_stage2_cast[23], A_earth_Z_stage2_cast};

//  always @(posedge clk or posedge reset)
//    begin : PipelineRegister3_process
//      if (reset == 1'b1) begin
//        az_costheta_cosphi_out1_1 <= 48'sh000000000000;
//      end
//      else begin
//        if (enb) begin
//          az_costheta_cosphi_out1_1 <= az_costheta_cosphi_out1;
//        end
//      end
//    end

//  assign az_costheta_cosphi_out1_2 = (((az_costheta_cosphi_out1_1[47] == 1'b0) && (az_costheta_cosphi_out1_1[46:39] != 8'b00000000)) || ((az_costheta_cosphi_out1_1[47] == 1'b0) && (az_costheta_cosphi_out1_1[39:16] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
//              ((az_costheta_cosphi_out1_1[47] == 1'b1) && (az_costheta_cosphi_out1_1[46:39] != 8'b11111111) ? 24'sb100000000000000000000000 :
//              az_costheta_cosphi_out1_1[39:16] + $signed({1'b0, az_costheta_cosphi_out1_1[15]})));

//  assign A_earth_Z_stage3_add_cast = ((A_earth_Z_op_stage1[24] == 1'b0) && (A_earth_Z_op_stage1[23] != 1'b0) ? 24'sb011111111111111111111111 :
//              ((A_earth_Z_op_stage1[24] == 1'b1) && (A_earth_Z_op_stage1[23] != 1'b1) ? 24'sb100000000000000000000000 :
//              $signed(A_earth_Z_op_stage1[23:0])));
//  assign A_earth_Z_stage3_add_cast_1 = {A_earth_Z_stage3_add_cast[23], A_earth_Z_stage3_add_cast};
//  assign A_earth_Z_stage3_add_cast_2 = {az_costheta_cosphi_out1_2[23], az_costheta_cosphi_out1_2};
//  assign A_earth_Z_stage3_add_temp = A_earth_Z_stage3_add_cast_1 + A_earth_Z_stage3_add_cast_2;
//  assign A_earth_Z_out1 = ((A_earth_Z_stage3_add_temp[24] == 1'b0) && (A_earth_Z_stage3_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
//              ((A_earth_Z_stage3_add_temp[24] == 1'b1) && (A_earth_Z_stage3_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
//              $signed(A_earth_Z_stage3_add_temp[23:0])));

//  assign Constant1_out1 = 16'sb0000000000000000;

//  assign acc_linear_sub_cast = ({{2{A_earth_Z_out1[23]}}, A_earth_Z_out1[23:2]}) + $signed({1'b0, A_earth_Z_out1[1]});
//  assign acc_linear_sub_cast_1 = {{3{Constant1_out1[15]}}, {Constant1_out1, 5'b00000}};
//  assign acc_linear_out1 = acc_linear_sub_cast - acc_linear_sub_cast_1;

//  always @(posedge clk or posedge reset)
//    begin : delayMatch2_process
//      if (reset == 1'b1) begin
//        acc_linear_out1_1 <= 24'sb000000000000000000000000;
//      end
//      else begin
//        if (enb) begin
//          acc_linear_out1_1 <= acc_linear_out1;
//        end
//      end
//    end

//  assign stateControl_5 = 1'b1;

//  always @(posedge clk or posedge reset)
//    begin : delayMatch1_process
//      if (reset == 1'b1) begin
//        delayMatch1_reg <= {9{1'b0}};
//      end
//      else begin
//        if (enb) begin
//          delayMatch1_reg[0] <= stateControl_5;
//          delayMatch1_reg[32'sd8:32'sd1] <= delayMatch1_reg[32'sd7:32'sd0];
//        end
//      end
//    end

//  assign stateControl_6 = delayMatch1_reg[8];

//  assign kconst_2 = 15'b100000110001001;

//  always @(posedge clk or posedge reset)
//    begin : HwModeRegister13_process
//      if (reset == 1'b1) begin
//        kconst_3 <= 15'b000000000000000;
//      end
//      else begin
//        if (enb) begin
//          kconst_3 <= kconst_2;
//        end
//      end
//    end

//  assign K_bias_out1 = 24'sb001101001000000000000000 * error_out1;

//  assign K_bias_out1_1 = (((K_bias_out1[47] == 1'b0) && (K_bias_out1[46:41] != 6'b000000)) || ((K_bias_out1[47] == 1'b0) && (K_bias_out1[41:18] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
//              ((K_bias_out1[47] == 1'b1) && (K_bias_out1[46:41] != 6'b111111) ? 24'sb100000000000000000000000 :
//              K_bias_out1[41:18] + $signed({1'b0, K_bias_out1[17]})));

//  assign B_est_indtc = K_bias_out1_1;

//  always @(posedge clk or posedge reset)
//    begin : HwModeRegister12_process
//      if (reset == 1'b1) begin
//        B_est_indtc_1 <= 24'sb000000000000000000000000;
//      end
//      else begin
//        if (enb) begin
//          B_est_indtc_1 <= B_est_indtc;
//        end
//      end
//    end

//  assign gain_cast = {1'b0, kconst_3};
//  assign gain_mul_temp = B_est_indtc_1 * gain_cast;
//  assign B_est_u_gain = gain_mul_temp[38:0];

//  always @(posedge clk or posedge reset)
//    begin : PipelineRegister6_process
//      if (reset == 1'b1) begin
//        B_est_u_gain_1 <= 39'sh0000000000;
//      end
//      else begin
//        if (enb) begin
//          B_est_u_gain_1 <= B_est_u_gain;
//        end
//      end
//    end

//  assign B_est_u_gain_2 = ({{7{B_est_u_gain_1[38]}}, B_est_u_gain_1[38:22]}) + $signed({1'b0, B_est_u_gain_1[21]});

//  assign B_est_u_dtc = B_est_u_gain_2;

//  assign adder_add_cast = {B_est_x_reg[23], B_est_x_reg};
//  assign adder_add_cast_1 = {B_est_u_dtc[23], B_est_u_dtc};
//  assign adder_add_temp = adder_add_cast + adder_add_cast_1;
//  assign B_est_u_add = ((adder_add_temp[24] == 1'b0) && (adder_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
//              ((adder_add_temp[24] == 1'b1) && (adder_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
//              $signed(adder_add_temp[23:0])));

//  assign B_est_x_reg_1 = (B_est_u_add > 24'sb000000100000000000000000 ? 24'sb000000100000000000000000 :
//              (B_est_u_add < 24'sb111111100000000000000000 ? 24'sb111111100000000000000000 :
//              B_est_u_add));

//  always @(posedge clk or posedge reset)
//    begin : reduced_2_process
//      if (reset == 1'b1) begin
//        B_est_x_reg <= 24'sb000000000000000000000000;
//      end
//      else begin
//        if (enb) begin
//          B_est_x_reg <= B_est_x_reg_2;
//        end
//      end
//    end

//  assign B_est_x_reg_2 = (stateControl_6 == 1'b0 ? B_est_x_reg :
//              B_est_x_reg_1);

//  assign Acc_corrected_sub_cast = {acc_linear_out1_1[23], acc_linear_out1_1};
//  assign Acc_corrected_sub_cast_1 = {B_est_x_reg_2[23], B_est_x_reg_2};
//  assign Acc_corrected_sub_temp = Acc_corrected_sub_cast - Acc_corrected_sub_cast_1;
//  assign Acc_corrected_out1 = ((Acc_corrected_sub_temp[24] == 1'b0) && (Acc_corrected_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
//              ((Acc_corrected_sub_temp[24] == 1'b1) && (Acc_corrected_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
//              $signed(Acc_corrected_sub_temp[23:0])));

//  assign Kvel_out1 = 32'sb00000010110011000000000000000000 * error_out1;

//  assign Kvel_out1_1 = (((Kvel_out1[55] == 1'b0) && (Kvel_out1[54:43] != 12'b000000000000)) || ((Kvel_out1[55] == 1'b0) && (Kvel_out1[43:20] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
//              ((Kvel_out1[55] == 1'b1) && (Kvel_out1[54:43] != 12'b111111111111) ? 24'sb100000000000000000000000 :
//              Kvel_out1[43:20] + $signed({1'b0, Kvel_out1[19]})));

//  always @(posedge clk or posedge reset)
//    begin : delayMatch3_process
//      if (reset == 1'b1) begin
//        Kvel_out1_2 <= 24'sb000000000000000000000000;
//      end
//      else begin
//        if (enb) begin
//          Kvel_out1_2 <= Kvel_out1_1;
//        end
//      end
//    end

//  assign Sum_add_cast = {Kvel_out1_2[23], Kvel_out1_2};
//  assign Sum_add_cast_1 = ((Acc_corrected_out1[23] == 1'b0) && (Acc_corrected_out1[22:21] != 2'b00) ? 24'sb011111111111111111111111 :
//              ((Acc_corrected_out1[23] == 1'b1) && (Acc_corrected_out1[22:21] != 2'b11) ? 24'sb100000000000000000000000 :
//              {Acc_corrected_out1[21:0], 2'b00}));
//  assign Sum_add_cast_2 = {Sum_add_cast_1[23], Sum_add_cast_1};
//  assign Sum_add_temp = Sum_add_cast + Sum_add_cast_2;
//  assign Sum_out1 = ((Sum_add_temp[24] == 1'b0) && (Sum_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
//              ((Sum_add_temp[24] == 1'b1) && (Sum_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
//              $signed(Sum_add_temp[23:0])));

//  assign Vpred_indtc = Sum_out1;

//  assign gain2_mul_temp = 15'sb010000011000101 * Vpred_indtc;
//  assign Vpred_u_gain = gain2_mul_temp[37:0];

//  assign Vpred_u_gain_1 = ({{9{Vpred_u_gain[37]}}, Vpred_u_gain[37:23]}) + $signed({1'b0, Vpred_u_gain[22]});

//  assign Vpred_u_dtc = Vpred_u_gain_1;

//  assign adder2_add_cast = {Vpred_x_reg[23], Vpred_x_reg};
//  assign adder2_add_cast_1 = {Vpred_u_dtc[23], Vpred_u_dtc};
//  assign adder2_add_temp = adder2_add_cast + adder2_add_cast_1;
//  assign Vpred_x_reg_1 = ((adder2_add_temp[24] == 1'b0) && (adder2_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
//              ((adder2_add_temp[24] == 1'b1) && (adder2_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
//              $signed(adder2_add_temp[23:0])));

//  always @(posedge clk or posedge reset)
//    begin : reduced_3_process
//      if (reset == 1'b1) begin
//        Vpred_x_reg <= 24'sb000000000000000000000000;
//      end
//      else begin
//        if (enb) begin
//          Vpred_x_reg <= Vpred_x_reg_2;
//        end
//      end
//    end

//  assign Vpred_x_reg_2 = (stateControl_3 == 1'b0 ? Vpred_x_reg :
//              Vpred_x_reg_1);

//  assign error_sub_cast = ((barometer_1[23] == 1'b0) && (barometer_1[22:21] != 2'b00) ? 24'sb011111111111111111111111 :
//              ((barometer_1[23] == 1'b1) && (barometer_1[22:21] != 2'b11) ? 24'sb100000000000000000000000 :
//              {barometer_1[21:0], 2'b00}));
//  assign error_sub_cast_1 = {error_sub_cast[23], error_sub_cast};
//  assign error_sub_cast_2 = ((Discrete_Time_Integrator2_x_reg[23] == 1'b0) && (Discrete_Time_Integrator2_x_reg[22:21] != 2'b00) ? 24'sb011111111111111111111111 :
//              ((Discrete_Time_Integrator2_x_reg[23] == 1'b1) && (Discrete_Time_Integrator2_x_reg[22:21] != 2'b11) ? 24'sb100000000000000000000000 :
//              {Discrete_Time_Integrator2_x_reg[21:0], 2'b00}));
//  assign error_sub_cast_3 = {error_sub_cast_2[23], error_sub_cast_2};
//  assign error_sub_temp = error_sub_cast_1 - error_sub_cast_3;
//  assign error_out1 = ((error_sub_temp[24] == 1'b0) && (error_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
//              ((error_sub_temp[24] == 1'b1) && (error_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
//              $signed(error_sub_temp[23:0])));

//  assign K_pos_out1 = 24'sb001100000000000000000000 * error_out1;

//  assign K_pos_out1_1 = (((K_pos_out1[47] == 1'b0) && (K_pos_out1[46:43] != 4'b0000)) || ((K_pos_out1[47] == 1'b0) && (K_pos_out1[43:20] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
//              ((K_pos_out1[47] == 1'b1) && (K_pos_out1[46:43] != 4'b1111) ? 24'sb100000000000000000000000 :
//              K_pos_out1[43:20] + $signed({1'b0, K_pos_out1[19]})));

//  assign Sum1_add_cast = {K_pos_out1_1[23], K_pos_out1_1};
//  assign Sum1_add_cast_1 = {Vpred_x_reg_2[23], Vpred_x_reg_2};
//  assign Sum1_add_temp = Sum1_add_cast + Sum1_add_cast_1;
//  assign Sum1_out1 = ((Sum1_add_temp[24] == 1'b0) && (Sum1_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
//              ((Sum1_add_temp[24] == 1'b1) && (Sum1_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
//              $signed(Sum1_add_temp[23:0])));

//  assign Discrete_Time_Integrator2_indtc = Sum1_out1;

//  assign gain1_mul_temp = 16'sb0100000110001001 * Discrete_Time_Integrator2_indtc;
//  assign Discrete_Time_Integrator2_u_gain = gain1_mul_temp[38:0];

//  assign Discrete_Time_Integrator2_u_gain_1 = ({{7{Discrete_Time_Integrator2_u_gain[38]}}, Discrete_Time_Integrator2_u_gain[38:22]}) + $signed({1'b0, Discrete_Time_Integrator2_u_gain[21]});

//  assign Discrete_Time_Integrator2_u_dtc = Discrete_Time_Integrator2_u_gain_1;

//  assign adder1_add_cast = {Discrete_Time_Integrator2_x_reg[23], Discrete_Time_Integrator2_x_reg};
//  assign adder1_add_cast_1 = {Discrete_Time_Integrator2_u_dtc[23], Discrete_Time_Integrator2_u_dtc};
//  assign adder1_add_temp = adder1_add_cast + adder1_add_cast_1;
//  assign Discrete_Time_Integrator2_u_add = ((adder1_add_temp[24] == 1'b0) && (adder1_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
//              ((adder1_add_temp[24] == 1'b1) && (adder1_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
//              $signed(adder1_add_temp[23:0])));

//  assign Discrete_Time_Integrator2_u_add_1 = (stateControl_1 == 1'b0 ? Discrete_Time_Integrator2_x_reg :
//              Discrete_Time_Integrator2_u_add);

//  always @(posedge clk or posedge reset)
//    begin : Discrete_Time_Integrator2_reg_process
//      if (reset == 1'b1) begin
//        Discrete_Time_Integrator2_x_reg <= 24'sb000000000000000000000000;
//      end
//      else begin
//        if (enb) begin
//          Discrete_Time_Integrator2_x_reg <= Discrete_Time_Integrator2_u_add_1;
//        end
//      end
//    end

//  assign Z_est = Discrete_Time_Integrator2_x_reg;

//  assign V_est = Vpred_x_reg_2;

//  assign ce_out = clk_enable;

//endmodule  // alpha3rd_order_filter