// -------------------------------------------------------------
// 
// File Name: C:\Users\Labhesh\OneDrive\Desktop\IIT Madras\Startup\FPGA\aLTITUDE_Controller\experimental_model\DirectLUTSubNetwork.v
// Created: 2026-07-01 14:08:36
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DirectLUTSubNetwork
// Source Path: DirectLUTSubNetwork
// Hierarchy Level: 1
// Model version: 4.38
// kd
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DirectLUTSubNetwork
          (Q1,
           fQ1);


  input   [2:0] Q1;  // ufix3
  output  signed [15:0] fQ1;  // sfix16_En10


  wire signed [15:0] DirectLUT_fQ11111_1 [0:4];  // sfix16_En10 [5]


  assign DirectLUT_fQ11111_1[0] = 16'sb0000010011001101; // +1.20 (1229 / 1024)
  assign DirectLUT_fQ11111_1[1] = 16'sb0000010100110011; // +1.30 (1331 / 1024)
  assign DirectLUT_fQ11111_1[2] = 16'sb0000010110011010; // +1.40 (1434 / 1024)
  assign DirectLUT_fQ11111_1[3] = 16'sb0000011000110011; // +1.55 (1587 / 1024)
  assign DirectLUT_fQ11111_1[4] = 16'sb0000011011001101; // +1.70 (1741 / 1024)
  assign fQ1 = DirectLUT_fQ11111_1[Q1];

endmodule  // DirectLUTSubNetwork

