// -------------------------------------------------------------
// 
// File Name: C:\Users\Labhesh\OneDrive\Desktop\IIT Madras\Startup\FPGA\aLTITUDE_Controller\experimental_model\DirectLUTSubNetwork_block.v
// Created: 2026-07-01 14:08:36
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DirectLUTSubNetwork_block
// Source Path: DirectLUTSubNetwork
// Hierarchy Level: 1
// Model version: 4.38
// ki
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DirectLUTSubNetwork_block
          (Q1,
           fQ1);


  input   [2:0] Q1;  // ufix3
  output  signed [15:0] fQ1;  // sfix16_En10


  wire signed [15:0] DirectLUT_fQ11111_1 [0:4];  // sfix16_En10 [5]


  assign DirectLUT_fQ11111_1[0] = 16'sb0000000010011010; // +0.15 (154 / 1024)
  assign DirectLUT_fQ11111_1[1] = 16'sb0000000100000000; // +0.25 (256 / 1024)
  assign DirectLUT_fQ11111_1[2] = 16'sb0000000101100110; // +0.35 (358 / 1024)
  assign DirectLUT_fQ11111_1[3] = 16'sb0000000110011010; // +0.40 (410 / 1024)
  assign DirectLUT_fQ11111_1[4] = 16'sb0000000111001101; // +0.45 (461 / 1024)
  assign fQ1 = DirectLUT_fQ11111_1[Q1];

endmodule  // DirectLUTSubNetwork_block

