// -------------------------------------------------------------
// 
// File Name: C:\Users\Labhesh\OneDrive\Desktop\IIT Madras\Startup\FPGA\aLTITUDE_Controller\experimental_model\DirectLUTSubNetwork_block1.v
// Created: 2026-07-01 14:08:36
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DirectLUTSubNetwork_block1
// Source Path: DirectLUTSubNetwork
// Hierarchy Level: 1
// Model version: 4.38
// kp
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DirectLUTSubNetwork_block1
          (Q1,
           fQ1);


  input   [2:0] Q1;  // ufix3
  output  signed [15:0] fQ1;  // sfix16_En10


  wire signed [15:0] DirectLUT_fQ11111_1 [0:4];  // sfix16_En10 [5]


  assign DirectLUT_fQ11111_1[0] = 16'sb0000001000110011; // +0.55 (563 / 1024)
  assign DirectLUT_fQ11111_1[1] = 16'sb0000001010011010; // +0.65 (666 / 1024)
  assign DirectLUT_fQ11111_1[2] = 16'sb0000001100000000; // +0.75 (768 / 1024)
  assign DirectLUT_fQ11111_1[3] = 16'sb0000001101100110; // +0.85 (870 / 1024)
  assign DirectLUT_fQ11111_1[4] = 16'sb0000001111001101; // +0.95 (973 / 1024)
  assign fQ1 = DirectLUT_fQ11111_1[Q1];

endmodule  // DirectLUTSubNetwork_block1

