// -------------------------------------------------------------
// 
// File Name: C:\Users\Labhesh\OneDrive\Desktop\IIT Madras\Startup\FPGA\aLTITUDE_Controller\experimental_model\Sine_HDL_Optimized.v
// Created: 2026-06-11 23:44:57
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Sine_HDL_Optimized
// Source Path: experimental_model/3rd_order_filter/Sine HDL Optimized
// Hierarchy Level: 1
// Model version: 4.36
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Sine_HDL_Optimized
          (clk,
           reset,
           enb,
           u,
           x);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] u;  // sfix16_En12
  output  signed [16:0] x;  // sfix17_En14


  wire [11:0] insig_out1;  // ufix12_En12
  wire [16:0] Point50_out1;  // ufix17_En17
  wire [16:0] LTEp50_cast;  // ufix17_En17
  wire LTEp50_out1;
  reg  RAMDelayBalance_out1;
  wire init_guard_true_1;
  reg  init_guard_true_2;
  wire signed [16:0] outinit_guard_default;  // sfix17_En14
  wire pow2switch_out1;
  wire signed [31:0] Amp50_sub_cast;  // sfix32_En17
  wire signed [31:0] Amp50_sub_cast_1;  // sfix32_En17
  wire signed [31:0] Amp50_sub_temp;  // sfix32_En17
  wire [31:0] Amp50_out1;  // ufix32_En17
  wire [31:0] insig_out1_dtc;  // ufix32_En17
  wire [31:0] QuadHandle1_out1;  // ufix32_En17
  wire [16:0] Point25_out1;  // ufix17_En17
  wire [31:0] LTEp25_cast;  // ufix32_En17
  wire LTEp25_out1;
  wire [31:0] p50mA_sub_cast;  // ufix32_En17
  wire [31:0] p50mA_out1;  // ufix32_En17
  wire [11:0] p50mA_out1_dtc;  // ufix12_En12
  wire [11:0] QuadHandle1_out1_dtc;  // ufix12_En12
  wire [11:0] QuadHandle2_out1;  // ufix12_En12
  wire [11:0] CastU16En2_out1;  // ufix12
  wire [12:0] CastU16En4_out1;  // ufix13
  wire [11:0] CastU16En3_out1;  // ufix12
  wire [11:0] Saturation_out1;  // ufix12
  wire [11:0] Switch_out1;  // ufix12
  wire [9:0] prelookup_idx;  // ufix10
  wire signed [16:0] Look_Up_Table_1 [0:1023];  // sfix17_En14 [1024]
  wire signed [16:0] out;  // sfix17_En14
  reg signed [16:0] out_1;  // sfix17_En14
  wire signed [16:0] Look_Up_Table_out1;  // sfix17_En14
  wire signed [17:0] Negate_cast;  // sfix18_En14
  wire signed [17:0] Negate_cast_1;  // sfix18_En14
  wire signed [16:0] Negate_out1;  // sfix17_En14
  wire signed [16:0] Sine;  // sfix17_En14

  initial begin
    out_1 = 17'sb00000000000000000;
  end
  // (C) 2016 Mathworks, Inc


  assign insig_out1 = u[11:0];

  assign Point50_out1 = 17'b10000000000000000;

  assign LTEp50_cast = {insig_out1, 5'b00000};
  assign LTEp50_out1 = LTEp50_cast <= Point50_out1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        RAMDelayBalance_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          RAMDelayBalance_out1 <= LTEp50_out1;
        end
      end
    end

  assign init_guard_true_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : matching_delays_process
      if (reset == 1'b1) begin
        init_guard_true_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          init_guard_true_2 <= init_guard_true_1;
        end
      end
    end

  assign outinit_guard_default = 17'sb00000000000000000;

  assign pow2switch_out1 = 1'b1;

  assign Amp50_sub_cast = {15'b0, {insig_out1, 5'b00000}};
  assign Amp50_sub_cast_1 = {15'b0, Point50_out1};
  assign Amp50_sub_temp = Amp50_sub_cast - Amp50_sub_cast_1;
  assign Amp50_out1 = Amp50_sub_temp;

  assign insig_out1_dtc = {15'b0, {insig_out1, 5'b00000}};

  assign QuadHandle1_out1 = (LTEp50_out1 == 1'b0 ? Amp50_out1 :
              insig_out1_dtc);

  assign Point25_out1 = 17'b01000000000000000;

  assign LTEp25_cast = {15'b0, Point25_out1};
  assign LTEp25_out1 = QuadHandle1_out1 <= LTEp25_cast;

  assign p50mA_sub_cast = {15'b0, Point50_out1};
  assign p50mA_out1 = p50mA_sub_cast - QuadHandle1_out1;

  assign p50mA_out1_dtc = p50mA_out1[16:5];

  assign QuadHandle1_out1_dtc = QuadHandle1_out1[16:5];

  assign QuadHandle2_out1 = (LTEp25_out1 == 1'b0 ? p50mA_out1_dtc :
              QuadHandle1_out1_dtc);

  assign CastU16En2_out1 = QuadHandle2_out1;

  assign CastU16En4_out1 = {1'b0, CastU16En2_out1};

  assign CastU16En3_out1 = (CastU16En4_out1[12] != 1'b0 ? 12'b111111111111 :
              CastU16En4_out1[11:0]);

  // saturation block maybe optimized away
  // if the NumDataPoints is a power of 2
  assign Saturation_out1 = (CastU16En3_out1 > 12'b001111111111 ? 12'b001111111111 :
              CastU16En3_out1);

  assign Switch_out1 = (pow2switch_out1 == 1'b0 ? CastU16En3_out1 :
              Saturation_out1);

  assign prelookup_idx = (Switch_out1 == 12'b000000000000 ? 10'b0000000000 :
              (Switch_out1 >= 12'b001111111111 ? 10'b1111111111 :
              Switch_out1[9:0]));

  assign Look_Up_Table_1[0] = 17'sb00000000000000000;
  assign Look_Up_Table_1[1] = 17'sb00000000000011001;
  assign Look_Up_Table_1[2] = 17'sb00000000000110010;
  assign Look_Up_Table_1[3] = 17'sb00000000001001011;
  assign Look_Up_Table_1[4] = 17'sb00000000001100101;
  assign Look_Up_Table_1[5] = 17'sb00000000001111110;
  assign Look_Up_Table_1[6] = 17'sb00000000010010111;
  assign Look_Up_Table_1[7] = 17'sb00000000010110000;
  assign Look_Up_Table_1[8] = 17'sb00000000011001001;
  assign Look_Up_Table_1[9] = 17'sb00000000011100010;
  assign Look_Up_Table_1[10] = 17'sb00000000011111011;
  assign Look_Up_Table_1[11] = 17'sb00000000100010100;
  assign Look_Up_Table_1[12] = 17'sb00000000100101110;
  assign Look_Up_Table_1[13] = 17'sb00000000101000111;
  assign Look_Up_Table_1[14] = 17'sb00000000101100000;
  assign Look_Up_Table_1[15] = 17'sb00000000101111001;
  assign Look_Up_Table_1[16] = 17'sb00000000110010010;
  assign Look_Up_Table_1[17] = 17'sb00000000110101011;
  assign Look_Up_Table_1[18] = 17'sb00000000111000100;
  assign Look_Up_Table_1[19] = 17'sb00000000111011101;
  assign Look_Up_Table_1[20] = 17'sb00000000111110111;
  assign Look_Up_Table_1[21] = 17'sb00000001000010000;
  assign Look_Up_Table_1[22] = 17'sb00000001000101001;
  assign Look_Up_Table_1[23] = 17'sb00000001001000010;
  assign Look_Up_Table_1[24] = 17'sb00000001001011011;
  assign Look_Up_Table_1[25] = 17'sb00000001001110100;
  assign Look_Up_Table_1[26] = 17'sb00000001010001101;
  assign Look_Up_Table_1[27] = 17'sb00000001010100110;
  assign Look_Up_Table_1[28] = 17'sb00000001011000000;
  assign Look_Up_Table_1[29] = 17'sb00000001011011001;
  assign Look_Up_Table_1[30] = 17'sb00000001011110010;
  assign Look_Up_Table_1[31] = 17'sb00000001100001011;
  assign Look_Up_Table_1[32] = 17'sb00000001100100100;
  assign Look_Up_Table_1[33] = 17'sb00000001100111101;
  assign Look_Up_Table_1[34] = 17'sb00000001101010110;
  assign Look_Up_Table_1[35] = 17'sb00000001101101111;
  assign Look_Up_Table_1[36] = 17'sb00000001110001000;
  assign Look_Up_Table_1[37] = 17'sb00000001110100001;
  assign Look_Up_Table_1[38] = 17'sb00000001110111011;
  assign Look_Up_Table_1[39] = 17'sb00000001111010100;
  assign Look_Up_Table_1[40] = 17'sb00000001111101101;
  assign Look_Up_Table_1[41] = 17'sb00000010000000110;
  assign Look_Up_Table_1[42] = 17'sb00000010000011111;
  assign Look_Up_Table_1[43] = 17'sb00000010000111000;
  assign Look_Up_Table_1[44] = 17'sb00000010001010001;
  assign Look_Up_Table_1[45] = 17'sb00000010001101010;
  assign Look_Up_Table_1[46] = 17'sb00000010010000011;
  assign Look_Up_Table_1[47] = 17'sb00000010010011100;
  assign Look_Up_Table_1[48] = 17'sb00000010010110101;
  assign Look_Up_Table_1[49] = 17'sb00000010011001110;
  assign Look_Up_Table_1[50] = 17'sb00000010011100111;
  assign Look_Up_Table_1[51] = 17'sb00000010100000000;
  assign Look_Up_Table_1[52] = 17'sb00000010100011010;
  assign Look_Up_Table_1[53] = 17'sb00000010100110011;
  assign Look_Up_Table_1[54] = 17'sb00000010101001100;
  assign Look_Up_Table_1[55] = 17'sb00000010101100101;
  assign Look_Up_Table_1[56] = 17'sb00000010101111110;
  assign Look_Up_Table_1[57] = 17'sb00000010110010111;
  assign Look_Up_Table_1[58] = 17'sb00000010110110000;
  assign Look_Up_Table_1[59] = 17'sb00000010111001001;
  assign Look_Up_Table_1[60] = 17'sb00000010111100010;
  assign Look_Up_Table_1[61] = 17'sb00000010111111011;
  assign Look_Up_Table_1[62] = 17'sb00000011000010100;
  assign Look_Up_Table_1[63] = 17'sb00000011000101101;
  assign Look_Up_Table_1[64] = 17'sb00000011001000110;
  assign Look_Up_Table_1[65] = 17'sb00000011001011111;
  assign Look_Up_Table_1[66] = 17'sb00000011001111000;
  assign Look_Up_Table_1[67] = 17'sb00000011010010001;
  assign Look_Up_Table_1[68] = 17'sb00000011010101010;
  assign Look_Up_Table_1[69] = 17'sb00000011011000011;
  assign Look_Up_Table_1[70] = 17'sb00000011011011100;
  assign Look_Up_Table_1[71] = 17'sb00000011011110101;
  assign Look_Up_Table_1[72] = 17'sb00000011100001110;
  assign Look_Up_Table_1[73] = 17'sb00000011100100111;
  assign Look_Up_Table_1[74] = 17'sb00000011101000000;
  assign Look_Up_Table_1[75] = 17'sb00000011101011001;
  assign Look_Up_Table_1[76] = 17'sb00000011101110010;
  assign Look_Up_Table_1[77] = 17'sb00000011110001011;
  assign Look_Up_Table_1[78] = 17'sb00000011110100100;
  assign Look_Up_Table_1[79] = 17'sb00000011110111101;
  assign Look_Up_Table_1[80] = 17'sb00000011111010110;
  assign Look_Up_Table_1[81] = 17'sb00000011111101111;
  assign Look_Up_Table_1[82] = 17'sb00000100000000111;
  assign Look_Up_Table_1[83] = 17'sb00000100000100000;
  assign Look_Up_Table_1[84] = 17'sb00000100000111001;
  assign Look_Up_Table_1[85] = 17'sb00000100001010010;
  assign Look_Up_Table_1[86] = 17'sb00000100001101011;
  assign Look_Up_Table_1[87] = 17'sb00000100010000100;
  assign Look_Up_Table_1[88] = 17'sb00000100010011101;
  assign Look_Up_Table_1[89] = 17'sb00000100010110110;
  assign Look_Up_Table_1[90] = 17'sb00000100011001111;
  assign Look_Up_Table_1[91] = 17'sb00000100011101000;
  assign Look_Up_Table_1[92] = 17'sb00000100100000001;
  assign Look_Up_Table_1[93] = 17'sb00000100100011001;
  assign Look_Up_Table_1[94] = 17'sb00000100100110010;
  assign Look_Up_Table_1[95] = 17'sb00000100101001011;
  assign Look_Up_Table_1[96] = 17'sb00000100101100100;
  assign Look_Up_Table_1[97] = 17'sb00000100101111101;
  assign Look_Up_Table_1[98] = 17'sb00000100110010110;
  assign Look_Up_Table_1[99] = 17'sb00000100110101111;
  assign Look_Up_Table_1[100] = 17'sb00000100111000111;
  assign Look_Up_Table_1[101] = 17'sb00000100111100000;
  assign Look_Up_Table_1[102] = 17'sb00000100111111001;
  assign Look_Up_Table_1[103] = 17'sb00000101000010010;
  assign Look_Up_Table_1[104] = 17'sb00000101000101011;
  assign Look_Up_Table_1[105] = 17'sb00000101001000100;
  assign Look_Up_Table_1[106] = 17'sb00000101001011100;
  assign Look_Up_Table_1[107] = 17'sb00000101001110101;
  assign Look_Up_Table_1[108] = 17'sb00000101010001110;
  assign Look_Up_Table_1[109] = 17'sb00000101010100111;
  assign Look_Up_Table_1[110] = 17'sb00000101011000000;
  assign Look_Up_Table_1[111] = 17'sb00000101011011000;
  assign Look_Up_Table_1[112] = 17'sb00000101011110001;
  assign Look_Up_Table_1[113] = 17'sb00000101100001010;
  assign Look_Up_Table_1[114] = 17'sb00000101100100011;
  assign Look_Up_Table_1[115] = 17'sb00000101100111011;
  assign Look_Up_Table_1[116] = 17'sb00000101101010100;
  assign Look_Up_Table_1[117] = 17'sb00000101101101101;
  assign Look_Up_Table_1[118] = 17'sb00000101110000101;
  assign Look_Up_Table_1[119] = 17'sb00000101110011110;
  assign Look_Up_Table_1[120] = 17'sb00000101110110111;
  assign Look_Up_Table_1[121] = 17'sb00000101111010000;
  assign Look_Up_Table_1[122] = 17'sb00000101111101000;
  assign Look_Up_Table_1[123] = 17'sb00000110000000001;
  assign Look_Up_Table_1[124] = 17'sb00000110000011010;
  assign Look_Up_Table_1[125] = 17'sb00000110000110010;
  assign Look_Up_Table_1[126] = 17'sb00000110001001011;
  assign Look_Up_Table_1[127] = 17'sb00000110001100100;
  assign Look_Up_Table_1[128] = 17'sb00000110001111100;
  assign Look_Up_Table_1[129] = 17'sb00000110010010101;
  assign Look_Up_Table_1[130] = 17'sb00000110010101110;
  assign Look_Up_Table_1[131] = 17'sb00000110011000110;
  assign Look_Up_Table_1[132] = 17'sb00000110011011111;
  assign Look_Up_Table_1[133] = 17'sb00000110011111000;
  assign Look_Up_Table_1[134] = 17'sb00000110100010000;
  assign Look_Up_Table_1[135] = 17'sb00000110100101001;
  assign Look_Up_Table_1[136] = 17'sb00000110101000001;
  assign Look_Up_Table_1[137] = 17'sb00000110101011010;
  assign Look_Up_Table_1[138] = 17'sb00000110101110010;
  assign Look_Up_Table_1[139] = 17'sb00000110110001011;
  assign Look_Up_Table_1[140] = 17'sb00000110110100100;
  assign Look_Up_Table_1[141] = 17'sb00000110110111100;
  assign Look_Up_Table_1[142] = 17'sb00000110111010101;
  assign Look_Up_Table_1[143] = 17'sb00000110111101101;
  assign Look_Up_Table_1[144] = 17'sb00000111000000110;
  assign Look_Up_Table_1[145] = 17'sb00000111000011110;
  assign Look_Up_Table_1[146] = 17'sb00000111000110111;
  assign Look_Up_Table_1[147] = 17'sb00000111001001111;
  assign Look_Up_Table_1[148] = 17'sb00000111001101000;
  assign Look_Up_Table_1[149] = 17'sb00000111010000000;
  assign Look_Up_Table_1[150] = 17'sb00000111010011001;
  assign Look_Up_Table_1[151] = 17'sb00000111010110001;
  assign Look_Up_Table_1[152] = 17'sb00000111011001010;
  assign Look_Up_Table_1[153] = 17'sb00000111011100010;
  assign Look_Up_Table_1[154] = 17'sb00000111011111011;
  assign Look_Up_Table_1[155] = 17'sb00000111100010011;
  assign Look_Up_Table_1[156] = 17'sb00000111100101011;
  assign Look_Up_Table_1[157] = 17'sb00000111101000100;
  assign Look_Up_Table_1[158] = 17'sb00000111101011100;
  assign Look_Up_Table_1[159] = 17'sb00000111101110101;
  assign Look_Up_Table_1[160] = 17'sb00000111110001101;
  assign Look_Up_Table_1[161] = 17'sb00000111110100101;
  assign Look_Up_Table_1[162] = 17'sb00000111110111110;
  assign Look_Up_Table_1[163] = 17'sb00000111111010110;
  assign Look_Up_Table_1[164] = 17'sb00000111111101110;
  assign Look_Up_Table_1[165] = 17'sb00001000000000111;
  assign Look_Up_Table_1[166] = 17'sb00001000000011111;
  assign Look_Up_Table_1[167] = 17'sb00001000000110111;
  assign Look_Up_Table_1[168] = 17'sb00001000001010000;
  assign Look_Up_Table_1[169] = 17'sb00001000001101000;
  assign Look_Up_Table_1[170] = 17'sb00001000010000000;
  assign Look_Up_Table_1[171] = 17'sb00001000010011001;
  assign Look_Up_Table_1[172] = 17'sb00001000010110001;
  assign Look_Up_Table_1[173] = 17'sb00001000011001001;
  assign Look_Up_Table_1[174] = 17'sb00001000011100001;
  assign Look_Up_Table_1[175] = 17'sb00001000011111010;
  assign Look_Up_Table_1[176] = 17'sb00001000100010010;
  assign Look_Up_Table_1[177] = 17'sb00001000100101010;
  assign Look_Up_Table_1[178] = 17'sb00001000101000010;
  assign Look_Up_Table_1[179] = 17'sb00001000101011010;
  assign Look_Up_Table_1[180] = 17'sb00001000101110011;
  assign Look_Up_Table_1[181] = 17'sb00001000110001011;
  assign Look_Up_Table_1[182] = 17'sb00001000110100011;
  assign Look_Up_Table_1[183] = 17'sb00001000110111011;
  assign Look_Up_Table_1[184] = 17'sb00001000111010011;
  assign Look_Up_Table_1[185] = 17'sb00001000111101011;
  assign Look_Up_Table_1[186] = 17'sb00001001000000100;
  assign Look_Up_Table_1[187] = 17'sb00001001000011100;
  assign Look_Up_Table_1[188] = 17'sb00001001000110100;
  assign Look_Up_Table_1[189] = 17'sb00001001001001100;
  assign Look_Up_Table_1[190] = 17'sb00001001001100100;
  assign Look_Up_Table_1[191] = 17'sb00001001001111100;
  assign Look_Up_Table_1[192] = 17'sb00001001010010100;
  assign Look_Up_Table_1[193] = 17'sb00001001010101100;
  assign Look_Up_Table_1[194] = 17'sb00001001011000100;
  assign Look_Up_Table_1[195] = 17'sb00001001011011100;
  assign Look_Up_Table_1[196] = 17'sb00001001011110100;
  assign Look_Up_Table_1[197] = 17'sb00001001100001100;
  assign Look_Up_Table_1[198] = 17'sb00001001100100100;
  assign Look_Up_Table_1[199] = 17'sb00001001100111100;
  assign Look_Up_Table_1[200] = 17'sb00001001101010100;
  assign Look_Up_Table_1[201] = 17'sb00001001101101100;
  assign Look_Up_Table_1[202] = 17'sb00001001110000100;
  assign Look_Up_Table_1[203] = 17'sb00001001110011100;
  assign Look_Up_Table_1[204] = 17'sb00001001110110100;
  assign Look_Up_Table_1[205] = 17'sb00001001111001100;
  assign Look_Up_Table_1[206] = 17'sb00001001111100100;
  assign Look_Up_Table_1[207] = 17'sb00001001111111011;
  assign Look_Up_Table_1[208] = 17'sb00001010000010011;
  assign Look_Up_Table_1[209] = 17'sb00001010000101011;
  assign Look_Up_Table_1[210] = 17'sb00001010001000011;
  assign Look_Up_Table_1[211] = 17'sb00001010001011011;
  assign Look_Up_Table_1[212] = 17'sb00001010001110011;
  assign Look_Up_Table_1[213] = 17'sb00001010010001011;
  assign Look_Up_Table_1[214] = 17'sb00001010010100010;
  assign Look_Up_Table_1[215] = 17'sb00001010010111010;
  assign Look_Up_Table_1[216] = 17'sb00001010011010010;
  assign Look_Up_Table_1[217] = 17'sb00001010011101010;
  assign Look_Up_Table_1[218] = 17'sb00001010100000001;
  assign Look_Up_Table_1[219] = 17'sb00001010100011001;
  assign Look_Up_Table_1[220] = 17'sb00001010100110001;
  assign Look_Up_Table_1[221] = 17'sb00001010101001001;
  assign Look_Up_Table_1[222] = 17'sb00001010101100000;
  assign Look_Up_Table_1[223] = 17'sb00001010101111000;
  assign Look_Up_Table_1[224] = 17'sb00001010110010000;
  assign Look_Up_Table_1[225] = 17'sb00001010110100111;
  assign Look_Up_Table_1[226] = 17'sb00001010110111111;
  assign Look_Up_Table_1[227] = 17'sb00001010111010111;
  assign Look_Up_Table_1[228] = 17'sb00001010111101110;
  assign Look_Up_Table_1[229] = 17'sb00001011000000110;
  assign Look_Up_Table_1[230] = 17'sb00001011000011101;
  assign Look_Up_Table_1[231] = 17'sb00001011000110101;
  assign Look_Up_Table_1[232] = 17'sb00001011001001100;
  assign Look_Up_Table_1[233] = 17'sb00001011001100100;
  assign Look_Up_Table_1[234] = 17'sb00001011001111100;
  assign Look_Up_Table_1[235] = 17'sb00001011010010011;
  assign Look_Up_Table_1[236] = 17'sb00001011010101011;
  assign Look_Up_Table_1[237] = 17'sb00001011011000010;
  assign Look_Up_Table_1[238] = 17'sb00001011011011010;
  assign Look_Up_Table_1[239] = 17'sb00001011011110001;
  assign Look_Up_Table_1[240] = 17'sb00001011100001001;
  assign Look_Up_Table_1[241] = 17'sb00001011100100000;
  assign Look_Up_Table_1[242] = 17'sb00001011100110111;
  assign Look_Up_Table_1[243] = 17'sb00001011101001111;
  assign Look_Up_Table_1[244] = 17'sb00001011101100110;
  assign Look_Up_Table_1[245] = 17'sb00001011101111110;
  assign Look_Up_Table_1[246] = 17'sb00001011110010101;
  assign Look_Up_Table_1[247] = 17'sb00001011110101100;
  assign Look_Up_Table_1[248] = 17'sb00001011111000100;
  assign Look_Up_Table_1[249] = 17'sb00001011111011011;
  assign Look_Up_Table_1[250] = 17'sb00001011111110010;
  assign Look_Up_Table_1[251] = 17'sb00001100000001010;
  assign Look_Up_Table_1[252] = 17'sb00001100000100001;
  assign Look_Up_Table_1[253] = 17'sb00001100000111000;
  assign Look_Up_Table_1[254] = 17'sb00001100001001111;
  assign Look_Up_Table_1[255] = 17'sb00001100001100111;
  assign Look_Up_Table_1[256] = 17'sb00001100001111110;
  assign Look_Up_Table_1[257] = 17'sb00001100010010101;
  assign Look_Up_Table_1[258] = 17'sb00001100010101100;
  assign Look_Up_Table_1[259] = 17'sb00001100011000011;
  assign Look_Up_Table_1[260] = 17'sb00001100011011011;
  assign Look_Up_Table_1[261] = 17'sb00001100011110010;
  assign Look_Up_Table_1[262] = 17'sb00001100100001001;
  assign Look_Up_Table_1[263] = 17'sb00001100100100000;
  assign Look_Up_Table_1[264] = 17'sb00001100100110111;
  assign Look_Up_Table_1[265] = 17'sb00001100101001110;
  assign Look_Up_Table_1[266] = 17'sb00001100101100101;
  assign Look_Up_Table_1[267] = 17'sb00001100101111100;
  assign Look_Up_Table_1[268] = 17'sb00001100110010011;
  assign Look_Up_Table_1[269] = 17'sb00001100110101010;
  assign Look_Up_Table_1[270] = 17'sb00001100111000001;
  assign Look_Up_Table_1[271] = 17'sb00001100111011000;
  assign Look_Up_Table_1[272] = 17'sb00001100111101111;
  assign Look_Up_Table_1[273] = 17'sb00001101000000110;
  assign Look_Up_Table_1[274] = 17'sb00001101000011101;
  assign Look_Up_Table_1[275] = 17'sb00001101000110100;
  assign Look_Up_Table_1[276] = 17'sb00001101001001011;
  assign Look_Up_Table_1[277] = 17'sb00001101001100010;
  assign Look_Up_Table_1[278] = 17'sb00001101001111001;
  assign Look_Up_Table_1[279] = 17'sb00001101010010000;
  assign Look_Up_Table_1[280] = 17'sb00001101010100111;
  assign Look_Up_Table_1[281] = 17'sb00001101010111110;
  assign Look_Up_Table_1[282] = 17'sb00001101011010100;
  assign Look_Up_Table_1[283] = 17'sb00001101011101011;
  assign Look_Up_Table_1[284] = 17'sb00001101100000010;
  assign Look_Up_Table_1[285] = 17'sb00001101100011001;
  assign Look_Up_Table_1[286] = 17'sb00001101100110000;
  assign Look_Up_Table_1[287] = 17'sb00001101101000110;
  assign Look_Up_Table_1[288] = 17'sb00001101101011101;
  assign Look_Up_Table_1[289] = 17'sb00001101101110100;
  assign Look_Up_Table_1[290] = 17'sb00001101110001010;
  assign Look_Up_Table_1[291] = 17'sb00001101110100001;
  assign Look_Up_Table_1[292] = 17'sb00001101110111000;
  assign Look_Up_Table_1[293] = 17'sb00001101111001110;
  assign Look_Up_Table_1[294] = 17'sb00001101111100101;
  assign Look_Up_Table_1[295] = 17'sb00001101111111100;
  assign Look_Up_Table_1[296] = 17'sb00001110000010010;
  assign Look_Up_Table_1[297] = 17'sb00001110000101001;
  assign Look_Up_Table_1[298] = 17'sb00001110000111111;
  assign Look_Up_Table_1[299] = 17'sb00001110001010110;
  assign Look_Up_Table_1[300] = 17'sb00001110001101100;
  assign Look_Up_Table_1[301] = 17'sb00001110010000011;
  assign Look_Up_Table_1[302] = 17'sb00001110010011001;
  assign Look_Up_Table_1[303] = 17'sb00001110010110000;
  assign Look_Up_Table_1[304] = 17'sb00001110011000110;
  assign Look_Up_Table_1[305] = 17'sb00001110011011101;
  assign Look_Up_Table_1[306] = 17'sb00001110011110011;
  assign Look_Up_Table_1[307] = 17'sb00001110100001010;
  assign Look_Up_Table_1[308] = 17'sb00001110100100000;
  assign Look_Up_Table_1[309] = 17'sb00001110100110110;
  assign Look_Up_Table_1[310] = 17'sb00001110101001101;
  assign Look_Up_Table_1[311] = 17'sb00001110101100011;
  assign Look_Up_Table_1[312] = 17'sb00001110101111001;
  assign Look_Up_Table_1[313] = 17'sb00001110110010000;
  assign Look_Up_Table_1[314] = 17'sb00001110110100110;
  assign Look_Up_Table_1[315] = 17'sb00001110110111100;
  assign Look_Up_Table_1[316] = 17'sb00001110111010011;
  assign Look_Up_Table_1[317] = 17'sb00001110111101001;
  assign Look_Up_Table_1[318] = 17'sb00001110111111111;
  assign Look_Up_Table_1[319] = 17'sb00001111000010101;
  assign Look_Up_Table_1[320] = 17'sb00001111000101011;
  assign Look_Up_Table_1[321] = 17'sb00001111001000010;
  assign Look_Up_Table_1[322] = 17'sb00001111001011000;
  assign Look_Up_Table_1[323] = 17'sb00001111001101110;
  assign Look_Up_Table_1[324] = 17'sb00001111010000100;
  assign Look_Up_Table_1[325] = 17'sb00001111010011010;
  assign Look_Up_Table_1[326] = 17'sb00001111010110000;
  assign Look_Up_Table_1[327] = 17'sb00001111011000110;
  assign Look_Up_Table_1[328] = 17'sb00001111011011100;
  assign Look_Up_Table_1[329] = 17'sb00001111011110010;
  assign Look_Up_Table_1[330] = 17'sb00001111100001000;
  assign Look_Up_Table_1[331] = 17'sb00001111100011110;
  assign Look_Up_Table_1[332] = 17'sb00001111100110100;
  assign Look_Up_Table_1[333] = 17'sb00001111101001010;
  assign Look_Up_Table_1[334] = 17'sb00001111101100000;
  assign Look_Up_Table_1[335] = 17'sb00001111101110110;
  assign Look_Up_Table_1[336] = 17'sb00001111110001100;
  assign Look_Up_Table_1[337] = 17'sb00001111110100010;
  assign Look_Up_Table_1[338] = 17'sb00001111110110111;
  assign Look_Up_Table_1[339] = 17'sb00001111111001101;
  assign Look_Up_Table_1[340] = 17'sb00001111111100011;
  assign Look_Up_Table_1[341] = 17'sb00001111111111001;
  assign Look_Up_Table_1[342] = 17'sb00010000000001111;
  assign Look_Up_Table_1[343] = 17'sb00010000000100100;
  assign Look_Up_Table_1[344] = 17'sb00010000000111010;
  assign Look_Up_Table_1[345] = 17'sb00010000001010000;
  assign Look_Up_Table_1[346] = 17'sb00010000001100101;
  assign Look_Up_Table_1[347] = 17'sb00010000001111011;
  assign Look_Up_Table_1[348] = 17'sb00010000010010001;
  assign Look_Up_Table_1[349] = 17'sb00010000010100110;
  assign Look_Up_Table_1[350] = 17'sb00010000010111100;
  assign Look_Up_Table_1[351] = 17'sb00010000011010001;
  assign Look_Up_Table_1[352] = 17'sb00010000011100111;
  assign Look_Up_Table_1[353] = 17'sb00010000011111101;
  assign Look_Up_Table_1[354] = 17'sb00010000100010010;
  assign Look_Up_Table_1[355] = 17'sb00010000100101000;
  assign Look_Up_Table_1[356] = 17'sb00010000100111101;
  assign Look_Up_Table_1[357] = 17'sb00010000101010011;
  assign Look_Up_Table_1[358] = 17'sb00010000101101000;
  assign Look_Up_Table_1[359] = 17'sb00010000101111101;
  assign Look_Up_Table_1[360] = 17'sb00010000110010011;
  assign Look_Up_Table_1[361] = 17'sb00010000110101000;
  assign Look_Up_Table_1[362] = 17'sb00010000110111110;
  assign Look_Up_Table_1[363] = 17'sb00010000111010011;
  assign Look_Up_Table_1[364] = 17'sb00010000111101000;
  assign Look_Up_Table_1[365] = 17'sb00010000111111110;
  assign Look_Up_Table_1[366] = 17'sb00010001000010011;
  assign Look_Up_Table_1[367] = 17'sb00010001000101000;
  assign Look_Up_Table_1[368] = 17'sb00010001000111101;
  assign Look_Up_Table_1[369] = 17'sb00010001001010011;
  assign Look_Up_Table_1[370] = 17'sb00010001001101000;
  assign Look_Up_Table_1[371] = 17'sb00010001001111101;
  assign Look_Up_Table_1[372] = 17'sb00010001010010010;
  assign Look_Up_Table_1[373] = 17'sb00010001010100111;
  assign Look_Up_Table_1[374] = 17'sb00010001010111100;
  assign Look_Up_Table_1[375] = 17'sb00010001011010010;
  assign Look_Up_Table_1[376] = 17'sb00010001011100111;
  assign Look_Up_Table_1[377] = 17'sb00010001011111100;
  assign Look_Up_Table_1[378] = 17'sb00010001100010001;
  assign Look_Up_Table_1[379] = 17'sb00010001100100110;
  assign Look_Up_Table_1[380] = 17'sb00010001100111011;
  assign Look_Up_Table_1[381] = 17'sb00010001101010000;
  assign Look_Up_Table_1[382] = 17'sb00010001101100101;
  assign Look_Up_Table_1[383] = 17'sb00010001101111010;
  assign Look_Up_Table_1[384] = 17'sb00010001110001110;
  assign Look_Up_Table_1[385] = 17'sb00010001110100011;
  assign Look_Up_Table_1[386] = 17'sb00010001110111000;
  assign Look_Up_Table_1[387] = 17'sb00010001111001101;
  assign Look_Up_Table_1[388] = 17'sb00010001111100010;
  assign Look_Up_Table_1[389] = 17'sb00010001111110111;
  assign Look_Up_Table_1[390] = 17'sb00010010000001011;
  assign Look_Up_Table_1[391] = 17'sb00010010000100000;
  assign Look_Up_Table_1[392] = 17'sb00010010000110101;
  assign Look_Up_Table_1[393] = 17'sb00010010001001010;
  assign Look_Up_Table_1[394] = 17'sb00010010001011110;
  assign Look_Up_Table_1[395] = 17'sb00010010001110011;
  assign Look_Up_Table_1[396] = 17'sb00010010010001000;
  assign Look_Up_Table_1[397] = 17'sb00010010010011100;
  assign Look_Up_Table_1[398] = 17'sb00010010010110001;
  assign Look_Up_Table_1[399] = 17'sb00010010011000101;
  assign Look_Up_Table_1[400] = 17'sb00010010011011010;
  assign Look_Up_Table_1[401] = 17'sb00010010011101111;
  assign Look_Up_Table_1[402] = 17'sb00010010100000011;
  assign Look_Up_Table_1[403] = 17'sb00010010100011000;
  assign Look_Up_Table_1[404] = 17'sb00010010100101100;
  assign Look_Up_Table_1[405] = 17'sb00010010101000001;
  assign Look_Up_Table_1[406] = 17'sb00010010101010101;
  assign Look_Up_Table_1[407] = 17'sb00010010101101001;
  assign Look_Up_Table_1[408] = 17'sb00010010101111110;
  assign Look_Up_Table_1[409] = 17'sb00010010110010010;
  assign Look_Up_Table_1[410] = 17'sb00010010110100110;
  assign Look_Up_Table_1[411] = 17'sb00010010110111011;
  assign Look_Up_Table_1[412] = 17'sb00010010111001111;
  assign Look_Up_Table_1[413] = 17'sb00010010111100011;
  assign Look_Up_Table_1[414] = 17'sb00010010111111000;
  assign Look_Up_Table_1[415] = 17'sb00010011000001100;
  assign Look_Up_Table_1[416] = 17'sb00010011000100000;
  assign Look_Up_Table_1[417] = 17'sb00010011000110100;
  assign Look_Up_Table_1[418] = 17'sb00010011001001000;
  assign Look_Up_Table_1[419] = 17'sb00010011001011100;
  assign Look_Up_Table_1[420] = 17'sb00010011001110001;
  assign Look_Up_Table_1[421] = 17'sb00010011010000101;
  assign Look_Up_Table_1[422] = 17'sb00010011010011001;
  assign Look_Up_Table_1[423] = 17'sb00010011010101101;
  assign Look_Up_Table_1[424] = 17'sb00010011011000001;
  assign Look_Up_Table_1[425] = 17'sb00010011011010101;
  assign Look_Up_Table_1[426] = 17'sb00010011011101001;
  assign Look_Up_Table_1[427] = 17'sb00010011011111101;
  assign Look_Up_Table_1[428] = 17'sb00010011100010001;
  assign Look_Up_Table_1[429] = 17'sb00010011100100100;
  assign Look_Up_Table_1[430] = 17'sb00010011100111000;
  assign Look_Up_Table_1[431] = 17'sb00010011101001100;
  assign Look_Up_Table_1[432] = 17'sb00010011101100000;
  assign Look_Up_Table_1[433] = 17'sb00010011101110100;
  assign Look_Up_Table_1[434] = 17'sb00010011110001000;
  assign Look_Up_Table_1[435] = 17'sb00010011110011011;
  assign Look_Up_Table_1[436] = 17'sb00010011110101111;
  assign Look_Up_Table_1[437] = 17'sb00010011111000011;
  assign Look_Up_Table_1[438] = 17'sb00010011111010110;
  assign Look_Up_Table_1[439] = 17'sb00010011111101010;
  assign Look_Up_Table_1[440] = 17'sb00010011111111110;
  assign Look_Up_Table_1[441] = 17'sb00010100000010001;
  assign Look_Up_Table_1[442] = 17'sb00010100000100101;
  assign Look_Up_Table_1[443] = 17'sb00010100000111000;
  assign Look_Up_Table_1[444] = 17'sb00010100001001100;
  assign Look_Up_Table_1[445] = 17'sb00010100001100000;
  assign Look_Up_Table_1[446] = 17'sb00010100001110011;
  assign Look_Up_Table_1[447] = 17'sb00010100010000110;
  assign Look_Up_Table_1[448] = 17'sb00010100010011010;
  assign Look_Up_Table_1[449] = 17'sb00010100010101101;
  assign Look_Up_Table_1[450] = 17'sb00010100011000001;
  assign Look_Up_Table_1[451] = 17'sb00010100011010100;
  assign Look_Up_Table_1[452] = 17'sb00010100011100111;
  assign Look_Up_Table_1[453] = 17'sb00010100011111011;
  assign Look_Up_Table_1[454] = 17'sb00010100100001110;
  assign Look_Up_Table_1[455] = 17'sb00010100100100001;
  assign Look_Up_Table_1[456] = 17'sb00010100100110101;
  assign Look_Up_Table_1[457] = 17'sb00010100101001000;
  assign Look_Up_Table_1[458] = 17'sb00010100101011011;
  assign Look_Up_Table_1[459] = 17'sb00010100101101110;
  assign Look_Up_Table_1[460] = 17'sb00010100110000001;
  assign Look_Up_Table_1[461] = 17'sb00010100110010100;
  assign Look_Up_Table_1[462] = 17'sb00010100110100111;
  assign Look_Up_Table_1[463] = 17'sb00010100110111011;
  assign Look_Up_Table_1[464] = 17'sb00010100111001110;
  assign Look_Up_Table_1[465] = 17'sb00010100111100001;
  assign Look_Up_Table_1[466] = 17'sb00010100111110100;
  assign Look_Up_Table_1[467] = 17'sb00010101000000111;
  assign Look_Up_Table_1[468] = 17'sb00010101000011010;
  assign Look_Up_Table_1[469] = 17'sb00010101000101100;
  assign Look_Up_Table_1[470] = 17'sb00010101000111111;
  assign Look_Up_Table_1[471] = 17'sb00010101001010010;
  assign Look_Up_Table_1[472] = 17'sb00010101001100101;
  assign Look_Up_Table_1[473] = 17'sb00010101001111000;
  assign Look_Up_Table_1[474] = 17'sb00010101010001011;
  assign Look_Up_Table_1[475] = 17'sb00010101010011101;
  assign Look_Up_Table_1[476] = 17'sb00010101010110000;
  assign Look_Up_Table_1[477] = 17'sb00010101011000011;
  assign Look_Up_Table_1[478] = 17'sb00010101011010110;
  assign Look_Up_Table_1[479] = 17'sb00010101011101000;
  assign Look_Up_Table_1[480] = 17'sb00010101011111011;
  assign Look_Up_Table_1[481] = 17'sb00010101100001101;
  assign Look_Up_Table_1[482] = 17'sb00010101100100000;
  assign Look_Up_Table_1[483] = 17'sb00010101100110011;
  assign Look_Up_Table_1[484] = 17'sb00010101101000101;
  assign Look_Up_Table_1[485] = 17'sb00010101101011000;
  assign Look_Up_Table_1[486] = 17'sb00010101101101010;
  assign Look_Up_Table_1[487] = 17'sb00010101101111101;
  assign Look_Up_Table_1[488] = 17'sb00010101110001111;
  assign Look_Up_Table_1[489] = 17'sb00010101110100001;
  assign Look_Up_Table_1[490] = 17'sb00010101110110100;
  assign Look_Up_Table_1[491] = 17'sb00010101111000110;
  assign Look_Up_Table_1[492] = 17'sb00010101111011000;
  assign Look_Up_Table_1[493] = 17'sb00010101111101011;
  assign Look_Up_Table_1[494] = 17'sb00010101111111101;
  assign Look_Up_Table_1[495] = 17'sb00010110000001111;
  assign Look_Up_Table_1[496] = 17'sb00010110000100001;
  assign Look_Up_Table_1[497] = 17'sb00010110000110100;
  assign Look_Up_Table_1[498] = 17'sb00010110001000110;
  assign Look_Up_Table_1[499] = 17'sb00010110001011000;
  assign Look_Up_Table_1[500] = 17'sb00010110001101010;
  assign Look_Up_Table_1[501] = 17'sb00010110001111100;
  assign Look_Up_Table_1[502] = 17'sb00010110010001110;
  assign Look_Up_Table_1[503] = 17'sb00010110010100000;
  assign Look_Up_Table_1[504] = 17'sb00010110010110010;
  assign Look_Up_Table_1[505] = 17'sb00010110011000100;
  assign Look_Up_Table_1[506] = 17'sb00010110011010110;
  assign Look_Up_Table_1[507] = 17'sb00010110011101000;
  assign Look_Up_Table_1[508] = 17'sb00010110011111010;
  assign Look_Up_Table_1[509] = 17'sb00010110100001100;
  assign Look_Up_Table_1[510] = 17'sb00010110100011110;
  assign Look_Up_Table_1[511] = 17'sb00010110100101111;
  assign Look_Up_Table_1[512] = 17'sb00010110101000001;
  assign Look_Up_Table_1[513] = 17'sb00010110101010011;
  assign Look_Up_Table_1[514] = 17'sb00010110101100101;
  assign Look_Up_Table_1[515] = 17'sb00010110101110110;
  assign Look_Up_Table_1[516] = 17'sb00010110110001000;
  assign Look_Up_Table_1[517] = 17'sb00010110110011010;
  assign Look_Up_Table_1[518] = 17'sb00010110110101011;
  assign Look_Up_Table_1[519] = 17'sb00010110110111101;
  assign Look_Up_Table_1[520] = 17'sb00010110111001111;
  assign Look_Up_Table_1[521] = 17'sb00010110111100000;
  assign Look_Up_Table_1[522] = 17'sb00010110111110010;
  assign Look_Up_Table_1[523] = 17'sb00010111000000011;
  assign Look_Up_Table_1[524] = 17'sb00010111000010101;
  assign Look_Up_Table_1[525] = 17'sb00010111000100110;
  assign Look_Up_Table_1[526] = 17'sb00010111000110111;
  assign Look_Up_Table_1[527] = 17'sb00010111001001001;
  assign Look_Up_Table_1[528] = 17'sb00010111001011010;
  assign Look_Up_Table_1[529] = 17'sb00010111001101011;
  assign Look_Up_Table_1[530] = 17'sb00010111001111101;
  assign Look_Up_Table_1[531] = 17'sb00010111010001110;
  assign Look_Up_Table_1[532] = 17'sb00010111010011111;
  assign Look_Up_Table_1[533] = 17'sb00010111010110000;
  assign Look_Up_Table_1[534] = 17'sb00010111011000010;
  assign Look_Up_Table_1[535] = 17'sb00010111011010011;
  assign Look_Up_Table_1[536] = 17'sb00010111011100100;
  assign Look_Up_Table_1[537] = 17'sb00010111011110101;
  assign Look_Up_Table_1[538] = 17'sb00010111100000110;
  assign Look_Up_Table_1[539] = 17'sb00010111100010111;
  assign Look_Up_Table_1[540] = 17'sb00010111100101000;
  assign Look_Up_Table_1[541] = 17'sb00010111100111001;
  assign Look_Up_Table_1[542] = 17'sb00010111101001010;
  assign Look_Up_Table_1[543] = 17'sb00010111101011011;
  assign Look_Up_Table_1[544] = 17'sb00010111101101100;
  assign Look_Up_Table_1[545] = 17'sb00010111101111101;
  assign Look_Up_Table_1[546] = 17'sb00010111110001101;
  assign Look_Up_Table_1[547] = 17'sb00010111110011110;
  assign Look_Up_Table_1[548] = 17'sb00010111110101111;
  assign Look_Up_Table_1[549] = 17'sb00010111111000000;
  assign Look_Up_Table_1[550] = 17'sb00010111111010000;
  assign Look_Up_Table_1[551] = 17'sb00010111111100001;
  assign Look_Up_Table_1[552] = 17'sb00010111111110010;
  assign Look_Up_Table_1[553] = 17'sb00011000000000010;
  assign Look_Up_Table_1[554] = 17'sb00011000000010011;
  assign Look_Up_Table_1[555] = 17'sb00011000000100100;
  assign Look_Up_Table_1[556] = 17'sb00011000000110100;
  assign Look_Up_Table_1[557] = 17'sb00011000001000101;
  assign Look_Up_Table_1[558] = 17'sb00011000001010101;
  assign Look_Up_Table_1[559] = 17'sb00011000001100110;
  assign Look_Up_Table_1[560] = 17'sb00011000001110110;
  assign Look_Up_Table_1[561] = 17'sb00011000010000111;
  assign Look_Up_Table_1[562] = 17'sb00011000010010111;
  assign Look_Up_Table_1[563] = 17'sb00011000010100111;
  assign Look_Up_Table_1[564] = 17'sb00011000010111000;
  assign Look_Up_Table_1[565] = 17'sb00011000011001000;
  assign Look_Up_Table_1[566] = 17'sb00011000011011000;
  assign Look_Up_Table_1[567] = 17'sb00011000011101000;
  assign Look_Up_Table_1[568] = 17'sb00011000011111001;
  assign Look_Up_Table_1[569] = 17'sb00011000100001001;
  assign Look_Up_Table_1[570] = 17'sb00011000100011001;
  assign Look_Up_Table_1[571] = 17'sb00011000100101001;
  assign Look_Up_Table_1[572] = 17'sb00011000100111001;
  assign Look_Up_Table_1[573] = 17'sb00011000101001001;
  assign Look_Up_Table_1[574] = 17'sb00011000101011001;
  assign Look_Up_Table_1[575] = 17'sb00011000101101001;
  assign Look_Up_Table_1[576] = 17'sb00011000101111001;
  assign Look_Up_Table_1[577] = 17'sb00011000110001001;
  assign Look_Up_Table_1[578] = 17'sb00011000110011001;
  assign Look_Up_Table_1[579] = 17'sb00011000110101001;
  assign Look_Up_Table_1[580] = 17'sb00011000110111001;
  assign Look_Up_Table_1[581] = 17'sb00011000111001000;
  assign Look_Up_Table_1[582] = 17'sb00011000111011000;
  assign Look_Up_Table_1[583] = 17'sb00011000111101000;
  assign Look_Up_Table_1[584] = 17'sb00011000111111000;
  assign Look_Up_Table_1[585] = 17'sb00011001000000111;
  assign Look_Up_Table_1[586] = 17'sb00011001000010111;
  assign Look_Up_Table_1[587] = 17'sb00011001000100111;
  assign Look_Up_Table_1[588] = 17'sb00011001000110110;
  assign Look_Up_Table_1[589] = 17'sb00011001001000110;
  assign Look_Up_Table_1[590] = 17'sb00011001001010101;
  assign Look_Up_Table_1[591] = 17'sb00011001001100101;
  assign Look_Up_Table_1[592] = 17'sb00011001001110100;
  assign Look_Up_Table_1[593] = 17'sb00011001010000100;
  assign Look_Up_Table_1[594] = 17'sb00011001010010011;
  assign Look_Up_Table_1[595] = 17'sb00011001010100011;
  assign Look_Up_Table_1[596] = 17'sb00011001010110010;
  assign Look_Up_Table_1[597] = 17'sb00011001011000001;
  assign Look_Up_Table_1[598] = 17'sb00011001011010000;
  assign Look_Up_Table_1[599] = 17'sb00011001011100000;
  assign Look_Up_Table_1[600] = 17'sb00011001011101111;
  assign Look_Up_Table_1[601] = 17'sb00011001011111110;
  assign Look_Up_Table_1[602] = 17'sb00011001100001101;
  assign Look_Up_Table_1[603] = 17'sb00011001100011101;
  assign Look_Up_Table_1[604] = 17'sb00011001100101100;
  assign Look_Up_Table_1[605] = 17'sb00011001100111011;
  assign Look_Up_Table_1[606] = 17'sb00011001101001010;
  assign Look_Up_Table_1[607] = 17'sb00011001101011001;
  assign Look_Up_Table_1[608] = 17'sb00011001101101000;
  assign Look_Up_Table_1[609] = 17'sb00011001101110111;
  assign Look_Up_Table_1[610] = 17'sb00011001110000110;
  assign Look_Up_Table_1[611] = 17'sb00011001110010101;
  assign Look_Up_Table_1[612] = 17'sb00011001110100011;
  assign Look_Up_Table_1[613] = 17'sb00011001110110010;
  assign Look_Up_Table_1[614] = 17'sb00011001111000001;
  assign Look_Up_Table_1[615] = 17'sb00011001111010000;
  assign Look_Up_Table_1[616] = 17'sb00011001111011111;
  assign Look_Up_Table_1[617] = 17'sb00011001111101101;
  assign Look_Up_Table_1[618] = 17'sb00011001111111100;
  assign Look_Up_Table_1[619] = 17'sb00011010000001011;
  assign Look_Up_Table_1[620] = 17'sb00011010000011001;
  assign Look_Up_Table_1[621] = 17'sb00011010000101000;
  assign Look_Up_Table_1[622] = 17'sb00011010000110110;
  assign Look_Up_Table_1[623] = 17'sb00011010001000101;
  assign Look_Up_Table_1[624] = 17'sb00011010001010011;
  assign Look_Up_Table_1[625] = 17'sb00011010001100010;
  assign Look_Up_Table_1[626] = 17'sb00011010001110000;
  assign Look_Up_Table_1[627] = 17'sb00011010001111111;
  assign Look_Up_Table_1[628] = 17'sb00011010010001101;
  assign Look_Up_Table_1[629] = 17'sb00011010010011011;
  assign Look_Up_Table_1[630] = 17'sb00011010010101010;
  assign Look_Up_Table_1[631] = 17'sb00011010010111000;
  assign Look_Up_Table_1[632] = 17'sb00011010011000110;
  assign Look_Up_Table_1[633] = 17'sb00011010011010100;
  assign Look_Up_Table_1[634] = 17'sb00011010011100010;
  assign Look_Up_Table_1[635] = 17'sb00011010011110001;
  assign Look_Up_Table_1[636] = 17'sb00011010011111111;
  assign Look_Up_Table_1[637] = 17'sb00011010100001101;
  assign Look_Up_Table_1[638] = 17'sb00011010100011011;
  assign Look_Up_Table_1[639] = 17'sb00011010100101001;
  assign Look_Up_Table_1[640] = 17'sb00011010100110111;
  assign Look_Up_Table_1[641] = 17'sb00011010101000101;
  assign Look_Up_Table_1[642] = 17'sb00011010101010011;
  assign Look_Up_Table_1[643] = 17'sb00011010101100001;
  assign Look_Up_Table_1[644] = 17'sb00011010101101110;
  assign Look_Up_Table_1[645] = 17'sb00011010101111100;
  assign Look_Up_Table_1[646] = 17'sb00011010110001010;
  assign Look_Up_Table_1[647] = 17'sb00011010110011000;
  assign Look_Up_Table_1[648] = 17'sb00011010110100101;
  assign Look_Up_Table_1[649] = 17'sb00011010110110011;
  assign Look_Up_Table_1[650] = 17'sb00011010111000001;
  assign Look_Up_Table_1[651] = 17'sb00011010111001110;
  assign Look_Up_Table_1[652] = 17'sb00011010111011100;
  assign Look_Up_Table_1[653] = 17'sb00011010111101010;
  assign Look_Up_Table_1[654] = 17'sb00011010111110111;
  assign Look_Up_Table_1[655] = 17'sb00011011000000101;
  assign Look_Up_Table_1[656] = 17'sb00011011000010010;
  assign Look_Up_Table_1[657] = 17'sb00011011000100000;
  assign Look_Up_Table_1[658] = 17'sb00011011000101101;
  assign Look_Up_Table_1[659] = 17'sb00011011000111010;
  assign Look_Up_Table_1[660] = 17'sb00011011001001000;
  assign Look_Up_Table_1[661] = 17'sb00011011001010101;
  assign Look_Up_Table_1[662] = 17'sb00011011001100010;
  assign Look_Up_Table_1[663] = 17'sb00011011001101111;
  assign Look_Up_Table_1[664] = 17'sb00011011001111101;
  assign Look_Up_Table_1[665] = 17'sb00011011010001010;
  assign Look_Up_Table_1[666] = 17'sb00011011010010111;
  assign Look_Up_Table_1[667] = 17'sb00011011010100100;
  assign Look_Up_Table_1[668] = 17'sb00011011010110001;
  assign Look_Up_Table_1[669] = 17'sb00011011010111110;
  assign Look_Up_Table_1[670] = 17'sb00011011011001011;
  assign Look_Up_Table_1[671] = 17'sb00011011011011000;
  assign Look_Up_Table_1[672] = 17'sb00011011011100101;
  assign Look_Up_Table_1[673] = 17'sb00011011011110010;
  assign Look_Up_Table_1[674] = 17'sb00011011011111111;
  assign Look_Up_Table_1[675] = 17'sb00011011100001100;
  assign Look_Up_Table_1[676] = 17'sb00011011100011000;
  assign Look_Up_Table_1[677] = 17'sb00011011100100101;
  assign Look_Up_Table_1[678] = 17'sb00011011100110010;
  assign Look_Up_Table_1[679] = 17'sb00011011100111111;
  assign Look_Up_Table_1[680] = 17'sb00011011101001011;
  assign Look_Up_Table_1[681] = 17'sb00011011101011000;
  assign Look_Up_Table_1[682] = 17'sb00011011101100101;
  assign Look_Up_Table_1[683] = 17'sb00011011101110001;
  assign Look_Up_Table_1[684] = 17'sb00011011101111110;
  assign Look_Up_Table_1[685] = 17'sb00011011110001010;
  assign Look_Up_Table_1[686] = 17'sb00011011110010111;
  assign Look_Up_Table_1[687] = 17'sb00011011110100011;
  assign Look_Up_Table_1[688] = 17'sb00011011110110000;
  assign Look_Up_Table_1[689] = 17'sb00011011110111100;
  assign Look_Up_Table_1[690] = 17'sb00011011111001000;
  assign Look_Up_Table_1[691] = 17'sb00011011111010101;
  assign Look_Up_Table_1[692] = 17'sb00011011111100001;
  assign Look_Up_Table_1[693] = 17'sb00011011111101101;
  assign Look_Up_Table_1[694] = 17'sb00011011111111001;
  assign Look_Up_Table_1[695] = 17'sb00011100000000101;
  assign Look_Up_Table_1[696] = 17'sb00011100000010010;
  assign Look_Up_Table_1[697] = 17'sb00011100000011110;
  assign Look_Up_Table_1[698] = 17'sb00011100000101010;
  assign Look_Up_Table_1[699] = 17'sb00011100000110110;
  assign Look_Up_Table_1[700] = 17'sb00011100001000010;
  assign Look_Up_Table_1[701] = 17'sb00011100001001110;
  assign Look_Up_Table_1[702] = 17'sb00011100001011010;
  assign Look_Up_Table_1[703] = 17'sb00011100001100110;
  assign Look_Up_Table_1[704] = 17'sb00011100001110001;
  assign Look_Up_Table_1[705] = 17'sb00011100001111101;
  assign Look_Up_Table_1[706] = 17'sb00011100010001001;
  assign Look_Up_Table_1[707] = 17'sb00011100010010101;
  assign Look_Up_Table_1[708] = 17'sb00011100010100001;
  assign Look_Up_Table_1[709] = 17'sb00011100010101100;
  assign Look_Up_Table_1[710] = 17'sb00011100010111000;
  assign Look_Up_Table_1[711] = 17'sb00011100011000011;
  assign Look_Up_Table_1[712] = 17'sb00011100011001111;
  assign Look_Up_Table_1[713] = 17'sb00011100011011011;
  assign Look_Up_Table_1[714] = 17'sb00011100011100110;
  assign Look_Up_Table_1[715] = 17'sb00011100011110010;
  assign Look_Up_Table_1[716] = 17'sb00011100011111101;
  assign Look_Up_Table_1[717] = 17'sb00011100100001001;
  assign Look_Up_Table_1[718] = 17'sb00011100100010100;
  assign Look_Up_Table_1[719] = 17'sb00011100100011111;
  assign Look_Up_Table_1[720] = 17'sb00011100100101011;
  assign Look_Up_Table_1[721] = 17'sb00011100100110110;
  assign Look_Up_Table_1[722] = 17'sb00011100101000001;
  assign Look_Up_Table_1[723] = 17'sb00011100101001100;
  assign Look_Up_Table_1[724] = 17'sb00011100101011000;
  assign Look_Up_Table_1[725] = 17'sb00011100101100011;
  assign Look_Up_Table_1[726] = 17'sb00011100101101110;
  assign Look_Up_Table_1[727] = 17'sb00011100101111001;
  assign Look_Up_Table_1[728] = 17'sb00011100110000100;
  assign Look_Up_Table_1[729] = 17'sb00011100110001111;
  assign Look_Up_Table_1[730] = 17'sb00011100110011010;
  assign Look_Up_Table_1[731] = 17'sb00011100110100101;
  assign Look_Up_Table_1[732] = 17'sb00011100110110000;
  assign Look_Up_Table_1[733] = 17'sb00011100110111011;
  assign Look_Up_Table_1[734] = 17'sb00011100111000101;
  assign Look_Up_Table_1[735] = 17'sb00011100111010000;
  assign Look_Up_Table_1[736] = 17'sb00011100111011011;
  assign Look_Up_Table_1[737] = 17'sb00011100111100110;
  assign Look_Up_Table_1[738] = 17'sb00011100111110000;
  assign Look_Up_Table_1[739] = 17'sb00011100111111011;
  assign Look_Up_Table_1[740] = 17'sb00011101000000110;
  assign Look_Up_Table_1[741] = 17'sb00011101000010000;
  assign Look_Up_Table_1[742] = 17'sb00011101000011011;
  assign Look_Up_Table_1[743] = 17'sb00011101000100101;
  assign Look_Up_Table_1[744] = 17'sb00011101000110000;
  assign Look_Up_Table_1[745] = 17'sb00011101000111010;
  assign Look_Up_Table_1[746] = 17'sb00011101001000101;
  assign Look_Up_Table_1[747] = 17'sb00011101001001111;
  assign Look_Up_Table_1[748] = 17'sb00011101001011001;
  assign Look_Up_Table_1[749] = 17'sb00011101001100100;
  assign Look_Up_Table_1[750] = 17'sb00011101001101110;
  assign Look_Up_Table_1[751] = 17'sb00011101001111000;
  assign Look_Up_Table_1[752] = 17'sb00011101010000010;
  assign Look_Up_Table_1[753] = 17'sb00011101010001101;
  assign Look_Up_Table_1[754] = 17'sb00011101010010111;
  assign Look_Up_Table_1[755] = 17'sb00011101010100001;
  assign Look_Up_Table_1[756] = 17'sb00011101010101011;
  assign Look_Up_Table_1[757] = 17'sb00011101010110101;
  assign Look_Up_Table_1[758] = 17'sb00011101010111111;
  assign Look_Up_Table_1[759] = 17'sb00011101011001001;
  assign Look_Up_Table_1[760] = 17'sb00011101011010011;
  assign Look_Up_Table_1[761] = 17'sb00011101011011101;
  assign Look_Up_Table_1[762] = 17'sb00011101011100110;
  assign Look_Up_Table_1[763] = 17'sb00011101011110000;
  assign Look_Up_Table_1[764] = 17'sb00011101011111010;
  assign Look_Up_Table_1[765] = 17'sb00011101100000100;
  assign Look_Up_Table_1[766] = 17'sb00011101100001110;
  assign Look_Up_Table_1[767] = 17'sb00011101100010111;
  assign Look_Up_Table_1[768] = 17'sb00011101100100001;
  assign Look_Up_Table_1[769] = 17'sb00011101100101010;
  assign Look_Up_Table_1[770] = 17'sb00011101100110100;
  assign Look_Up_Table_1[771] = 17'sb00011101100111110;
  assign Look_Up_Table_1[772] = 17'sb00011101101000111;
  assign Look_Up_Table_1[773] = 17'sb00011101101010000;
  assign Look_Up_Table_1[774] = 17'sb00011101101011010;
  assign Look_Up_Table_1[775] = 17'sb00011101101100011;
  assign Look_Up_Table_1[776] = 17'sb00011101101101101;
  assign Look_Up_Table_1[777] = 17'sb00011101101110110;
  assign Look_Up_Table_1[778] = 17'sb00011101101111111;
  assign Look_Up_Table_1[779] = 17'sb00011101110001000;
  assign Look_Up_Table_1[780] = 17'sb00011101110010010;
  assign Look_Up_Table_1[781] = 17'sb00011101110011011;
  assign Look_Up_Table_1[782] = 17'sb00011101110100100;
  assign Look_Up_Table_1[783] = 17'sb00011101110101101;
  assign Look_Up_Table_1[784] = 17'sb00011101110110110;
  assign Look_Up_Table_1[785] = 17'sb00011101110111111;
  assign Look_Up_Table_1[786] = 17'sb00011101111001000;
  assign Look_Up_Table_1[787] = 17'sb00011101111010001;
  assign Look_Up_Table_1[788] = 17'sb00011101111011010;
  assign Look_Up_Table_1[789] = 17'sb00011101111100011;
  assign Look_Up_Table_1[790] = 17'sb00011101111101100;
  assign Look_Up_Table_1[791] = 17'sb00011101111110101;
  assign Look_Up_Table_1[792] = 17'sb00011101111111101;
  assign Look_Up_Table_1[793] = 17'sb00011110000000110;
  assign Look_Up_Table_1[794] = 17'sb00011110000001111;
  assign Look_Up_Table_1[795] = 17'sb00011110000010111;
  assign Look_Up_Table_1[796] = 17'sb00011110000100000;
  assign Look_Up_Table_1[797] = 17'sb00011110000101001;
  assign Look_Up_Table_1[798] = 17'sb00011110000110001;
  assign Look_Up_Table_1[799] = 17'sb00011110000111010;
  assign Look_Up_Table_1[800] = 17'sb00011110001000010;
  assign Look_Up_Table_1[801] = 17'sb00011110001001011;
  assign Look_Up_Table_1[802] = 17'sb00011110001010011;
  assign Look_Up_Table_1[803] = 17'sb00011110001011011;
  assign Look_Up_Table_1[804] = 17'sb00011110001100100;
  assign Look_Up_Table_1[805] = 17'sb00011110001101100;
  assign Look_Up_Table_1[806] = 17'sb00011110001110100;
  assign Look_Up_Table_1[807] = 17'sb00011110001111101;
  assign Look_Up_Table_1[808] = 17'sb00011110010000101;
  assign Look_Up_Table_1[809] = 17'sb00011110010001101;
  assign Look_Up_Table_1[810] = 17'sb00011110010010101;
  assign Look_Up_Table_1[811] = 17'sb00011110010011101;
  assign Look_Up_Table_1[812] = 17'sb00011110010100101;
  assign Look_Up_Table_1[813] = 17'sb00011110010101101;
  assign Look_Up_Table_1[814] = 17'sb00011110010110101;
  assign Look_Up_Table_1[815] = 17'sb00011110010111101;
  assign Look_Up_Table_1[816] = 17'sb00011110011000101;
  assign Look_Up_Table_1[817] = 17'sb00011110011001101;
  assign Look_Up_Table_1[818] = 17'sb00011110011010101;
  assign Look_Up_Table_1[819] = 17'sb00011110011011101;
  assign Look_Up_Table_1[820] = 17'sb00011110011100100;
  assign Look_Up_Table_1[821] = 17'sb00011110011101100;
  assign Look_Up_Table_1[822] = 17'sb00011110011110100;
  assign Look_Up_Table_1[823] = 17'sb00011110011111011;
  assign Look_Up_Table_1[824] = 17'sb00011110100000011;
  assign Look_Up_Table_1[825] = 17'sb00011110100001011;
  assign Look_Up_Table_1[826] = 17'sb00011110100010010;
  assign Look_Up_Table_1[827] = 17'sb00011110100011010;
  assign Look_Up_Table_1[828] = 17'sb00011110100100001;
  assign Look_Up_Table_1[829] = 17'sb00011110100101000;
  assign Look_Up_Table_1[830] = 17'sb00011110100110000;
  assign Look_Up_Table_1[831] = 17'sb00011110100110111;
  assign Look_Up_Table_1[832] = 17'sb00011110100111111;
  assign Look_Up_Table_1[833] = 17'sb00011110101000110;
  assign Look_Up_Table_1[834] = 17'sb00011110101001101;
  assign Look_Up_Table_1[835] = 17'sb00011110101010100;
  assign Look_Up_Table_1[836] = 17'sb00011110101011011;
  assign Look_Up_Table_1[837] = 17'sb00011110101100011;
  assign Look_Up_Table_1[838] = 17'sb00011110101101010;
  assign Look_Up_Table_1[839] = 17'sb00011110101110001;
  assign Look_Up_Table_1[840] = 17'sb00011110101111000;
  assign Look_Up_Table_1[841] = 17'sb00011110101111111;
  assign Look_Up_Table_1[842] = 17'sb00011110110000110;
  assign Look_Up_Table_1[843] = 17'sb00011110110001101;
  assign Look_Up_Table_1[844] = 17'sb00011110110010011;
  assign Look_Up_Table_1[845] = 17'sb00011110110011010;
  assign Look_Up_Table_1[846] = 17'sb00011110110100001;
  assign Look_Up_Table_1[847] = 17'sb00011110110101000;
  assign Look_Up_Table_1[848] = 17'sb00011110110101111;
  assign Look_Up_Table_1[849] = 17'sb00011110110110101;
  assign Look_Up_Table_1[850] = 17'sb00011110110111100;
  assign Look_Up_Table_1[851] = 17'sb00011110111000010;
  assign Look_Up_Table_1[852] = 17'sb00011110111001001;
  assign Look_Up_Table_1[853] = 17'sb00011110111010000;
  assign Look_Up_Table_1[854] = 17'sb00011110111010110;
  assign Look_Up_Table_1[855] = 17'sb00011110111011101;
  assign Look_Up_Table_1[856] = 17'sb00011110111100011;
  assign Look_Up_Table_1[857] = 17'sb00011110111101001;
  assign Look_Up_Table_1[858] = 17'sb00011110111110000;
  assign Look_Up_Table_1[859] = 17'sb00011110111110110;
  assign Look_Up_Table_1[860] = 17'sb00011110111111100;
  assign Look_Up_Table_1[861] = 17'sb00011111000000011;
  assign Look_Up_Table_1[862] = 17'sb00011111000001001;
  assign Look_Up_Table_1[863] = 17'sb00011111000001111;
  assign Look_Up_Table_1[864] = 17'sb00011111000010101;
  assign Look_Up_Table_1[865] = 17'sb00011111000011011;
  assign Look_Up_Table_1[866] = 17'sb00011111000100001;
  assign Look_Up_Table_1[867] = 17'sb00011111000100111;
  assign Look_Up_Table_1[868] = 17'sb00011111000101101;
  assign Look_Up_Table_1[869] = 17'sb00011111000110011;
  assign Look_Up_Table_1[870] = 17'sb00011111000111001;
  assign Look_Up_Table_1[871] = 17'sb00011111000111111;
  assign Look_Up_Table_1[872] = 17'sb00011111001000101;
  assign Look_Up_Table_1[873] = 17'sb00011111001001010;
  assign Look_Up_Table_1[874] = 17'sb00011111001010000;
  assign Look_Up_Table_1[875] = 17'sb00011111001010110;
  assign Look_Up_Table_1[876] = 17'sb00011111001011100;
  assign Look_Up_Table_1[877] = 17'sb00011111001100001;
  assign Look_Up_Table_1[878] = 17'sb00011111001100111;
  assign Look_Up_Table_1[879] = 17'sb00011111001101100;
  assign Look_Up_Table_1[880] = 17'sb00011111001110010;
  assign Look_Up_Table_1[881] = 17'sb00011111001110111;
  assign Look_Up_Table_1[882] = 17'sb00011111001111101;
  assign Look_Up_Table_1[883] = 17'sb00011111010000010;
  assign Look_Up_Table_1[884] = 17'sb00011111010001000;
  assign Look_Up_Table_1[885] = 17'sb00011111010001101;
  assign Look_Up_Table_1[886] = 17'sb00011111010010010;
  assign Look_Up_Table_1[887] = 17'sb00011111010011000;
  assign Look_Up_Table_1[888] = 17'sb00011111010011101;
  assign Look_Up_Table_1[889] = 17'sb00011111010100010;
  assign Look_Up_Table_1[890] = 17'sb00011111010100111;
  assign Look_Up_Table_1[891] = 17'sb00011111010101100;
  assign Look_Up_Table_1[892] = 17'sb00011111010110001;
  assign Look_Up_Table_1[893] = 17'sb00011111010110110;
  assign Look_Up_Table_1[894] = 17'sb00011111010111011;
  assign Look_Up_Table_1[895] = 17'sb00011111011000000;
  assign Look_Up_Table_1[896] = 17'sb00011111011000101;
  assign Look_Up_Table_1[897] = 17'sb00011111011001010;
  assign Look_Up_Table_1[898] = 17'sb00011111011001111;
  assign Look_Up_Table_1[899] = 17'sb00011111011010100;
  assign Look_Up_Table_1[900] = 17'sb00011111011011000;
  assign Look_Up_Table_1[901] = 17'sb00011111011011101;
  assign Look_Up_Table_1[902] = 17'sb00011111011100010;
  assign Look_Up_Table_1[903] = 17'sb00011111011100111;
  assign Look_Up_Table_1[904] = 17'sb00011111011101011;
  assign Look_Up_Table_1[905] = 17'sb00011111011110000;
  assign Look_Up_Table_1[906] = 17'sb00011111011110100;
  assign Look_Up_Table_1[907] = 17'sb00011111011111001;
  assign Look_Up_Table_1[908] = 17'sb00011111011111101;
  assign Look_Up_Table_1[909] = 17'sb00011111100000010;
  assign Look_Up_Table_1[910] = 17'sb00011111100000110;
  assign Look_Up_Table_1[911] = 17'sb00011111100001010;
  assign Look_Up_Table_1[912] = 17'sb00011111100001111;
  assign Look_Up_Table_1[913] = 17'sb00011111100010011;
  assign Look_Up_Table_1[914] = 17'sb00011111100010111;
  assign Look_Up_Table_1[915] = 17'sb00011111100011100;
  assign Look_Up_Table_1[916] = 17'sb00011111100100000;
  assign Look_Up_Table_1[917] = 17'sb00011111100100100;
  assign Look_Up_Table_1[918] = 17'sb00011111100101000;
  assign Look_Up_Table_1[919] = 17'sb00011111100101100;
  assign Look_Up_Table_1[920] = 17'sb00011111100110000;
  assign Look_Up_Table_1[921] = 17'sb00011111100110100;
  assign Look_Up_Table_1[922] = 17'sb00011111100111000;
  assign Look_Up_Table_1[923] = 17'sb00011111100111100;
  assign Look_Up_Table_1[924] = 17'sb00011111101000000;
  assign Look_Up_Table_1[925] = 17'sb00011111101000011;
  assign Look_Up_Table_1[926] = 17'sb00011111101000111;
  assign Look_Up_Table_1[927] = 17'sb00011111101001011;
  assign Look_Up_Table_1[928] = 17'sb00011111101001111;
  assign Look_Up_Table_1[929] = 17'sb00011111101010010;
  assign Look_Up_Table_1[930] = 17'sb00011111101010110;
  assign Look_Up_Table_1[931] = 17'sb00011111101011010;
  assign Look_Up_Table_1[932] = 17'sb00011111101011101;
  assign Look_Up_Table_1[933] = 17'sb00011111101100001;
  assign Look_Up_Table_1[934] = 17'sb00011111101100100;
  assign Look_Up_Table_1[935] = 17'sb00011111101101000;
  assign Look_Up_Table_1[936] = 17'sb00011111101101011;
  assign Look_Up_Table_1[937] = 17'sb00011111101101110;
  assign Look_Up_Table_1[938] = 17'sb00011111101110010;
  assign Look_Up_Table_1[939] = 17'sb00011111101110101;
  assign Look_Up_Table_1[940] = 17'sb00011111101111000;
  assign Look_Up_Table_1[941] = 17'sb00011111101111011;
  assign Look_Up_Table_1[942] = 17'sb00011111101111111;
  assign Look_Up_Table_1[943] = 17'sb00011111110000010;
  assign Look_Up_Table_1[944] = 17'sb00011111110000101;
  assign Look_Up_Table_1[945] = 17'sb00011111110001000;
  assign Look_Up_Table_1[946] = 17'sb00011111110001011;
  assign Look_Up_Table_1[947] = 17'sb00011111110001110;
  assign Look_Up_Table_1[948] = 17'sb00011111110010001;
  assign Look_Up_Table_1[949] = 17'sb00011111110010100;
  assign Look_Up_Table_1[950] = 17'sb00011111110010111;
  assign Look_Up_Table_1[951] = 17'sb00011111110011001;
  assign Look_Up_Table_1[952] = 17'sb00011111110011100;
  assign Look_Up_Table_1[953] = 17'sb00011111110011111;
  assign Look_Up_Table_1[954] = 17'sb00011111110100010;
  assign Look_Up_Table_1[955] = 17'sb00011111110100100;
  assign Look_Up_Table_1[956] = 17'sb00011111110100111;
  assign Look_Up_Table_1[957] = 17'sb00011111110101010;
  assign Look_Up_Table_1[958] = 17'sb00011111110101100;
  assign Look_Up_Table_1[959] = 17'sb00011111110101111;
  assign Look_Up_Table_1[960] = 17'sb00011111110110001;
  assign Look_Up_Table_1[961] = 17'sb00011111110110100;
  assign Look_Up_Table_1[962] = 17'sb00011111110110110;
  assign Look_Up_Table_1[963] = 17'sb00011111110111000;
  assign Look_Up_Table_1[964] = 17'sb00011111110111011;
  assign Look_Up_Table_1[965] = 17'sb00011111110111101;
  assign Look_Up_Table_1[966] = 17'sb00011111110111111;
  assign Look_Up_Table_1[967] = 17'sb00011111111000001;
  assign Look_Up_Table_1[968] = 17'sb00011111111000100;
  assign Look_Up_Table_1[969] = 17'sb00011111111000110;
  assign Look_Up_Table_1[970] = 17'sb00011111111001000;
  assign Look_Up_Table_1[971] = 17'sb00011111111001010;
  assign Look_Up_Table_1[972] = 17'sb00011111111001100;
  assign Look_Up_Table_1[973] = 17'sb00011111111001110;
  assign Look_Up_Table_1[974] = 17'sb00011111111010000;
  assign Look_Up_Table_1[975] = 17'sb00011111111010010;
  assign Look_Up_Table_1[976] = 17'sb00011111111010100;
  assign Look_Up_Table_1[977] = 17'sb00011111111010101;
  assign Look_Up_Table_1[978] = 17'sb00011111111010111;
  assign Look_Up_Table_1[979] = 17'sb00011111111011001;
  assign Look_Up_Table_1[980] = 17'sb00011111111011011;
  assign Look_Up_Table_1[981] = 17'sb00011111111011100;
  assign Look_Up_Table_1[982] = 17'sb00011111111011110;
  assign Look_Up_Table_1[983] = 17'sb00011111111100000;
  assign Look_Up_Table_1[984] = 17'sb00011111111100001;
  assign Look_Up_Table_1[985] = 17'sb00011111111100011;
  assign Look_Up_Table_1[986] = 17'sb00011111111100100;
  assign Look_Up_Table_1[987] = 17'sb00011111111100110;
  assign Look_Up_Table_1[988] = 17'sb00011111111100111;
  assign Look_Up_Table_1[989] = 17'sb00011111111101000;
  assign Look_Up_Table_1[990] = 17'sb00011111111101010;
  assign Look_Up_Table_1[991] = 17'sb00011111111101011;
  assign Look_Up_Table_1[992] = 17'sb00011111111101100;
  assign Look_Up_Table_1[993] = 17'sb00011111111101101;
  assign Look_Up_Table_1[994] = 17'sb00011111111101111;
  assign Look_Up_Table_1[995] = 17'sb00011111111110000;
  assign Look_Up_Table_1[996] = 17'sb00011111111110001;
  assign Look_Up_Table_1[997] = 17'sb00011111111110010;
  assign Look_Up_Table_1[998] = 17'sb00011111111110011;
  assign Look_Up_Table_1[999] = 17'sb00011111111110100;
  assign Look_Up_Table_1[1000] = 17'sb00011111111110101;
  assign Look_Up_Table_1[1001] = 17'sb00011111111110110;
  assign Look_Up_Table_1[1002] = 17'sb00011111111110111;
  assign Look_Up_Table_1[1003] = 17'sb00011111111110111;
  assign Look_Up_Table_1[1004] = 17'sb00011111111111000;
  assign Look_Up_Table_1[1005] = 17'sb00011111111111001;
  assign Look_Up_Table_1[1006] = 17'sb00011111111111010;
  assign Look_Up_Table_1[1007] = 17'sb00011111111111010;
  assign Look_Up_Table_1[1008] = 17'sb00011111111111011;
  assign Look_Up_Table_1[1009] = 17'sb00011111111111100;
  assign Look_Up_Table_1[1010] = 17'sb00011111111111100;
  assign Look_Up_Table_1[1011] = 17'sb00011111111111101;
  assign Look_Up_Table_1[1012] = 17'sb00011111111111101;
  assign Look_Up_Table_1[1013] = 17'sb00011111111111110;
  assign Look_Up_Table_1[1014] = 17'sb00011111111111110;
  assign Look_Up_Table_1[1015] = 17'sb00011111111111110;
  assign Look_Up_Table_1[1016] = 17'sb00011111111111111;
  assign Look_Up_Table_1[1017] = 17'sb00011111111111111;
  assign Look_Up_Table_1[1018] = 17'sb00011111111111111;
  assign Look_Up_Table_1[1019] = 17'sb00100000000000000;
  assign Look_Up_Table_1[1020] = 17'sb00100000000000000;
  assign Look_Up_Table_1[1021] = 17'sb00100000000000000;
  assign Look_Up_Table_1[1022] = 17'sb00100000000000000;
  assign Look_Up_Table_1[1023] = 17'sb00100000000000000;
  assign out = Look_Up_Table_1[prelookup_idx];

  always @(posedge clk)
    begin : PipelineRegister_process
      if (enb) begin
        out_1 <= out;
      end
    end

  assign Look_Up_Table_out1 = (init_guard_true_2 == 1'b0 ? outinit_guard_default :
              out_1);

  assign Negate_cast = {Look_Up_Table_out1[16], Look_Up_Table_out1};
  assign Negate_cast_1 =  - (Negate_cast);
  assign Negate_out1 = Negate_cast_1[16:0];

  assign Sine = (RAMDelayBalance_out1 == 1'b0 ? Negate_out1 :
              Look_Up_Table_out1);

  assign x = Sine;

endmodule  // Sine_HDL_Optimized