// -------------------------------------------------------------
// 
// File Name: C:\Users\Labhesh\OneDrive\Desktop\IIT Madras\Startup\FPGA\Yaw_Control_loop\Yaw_controller\Yaw_filter.v
// Created: 2026-06-09 12:36:18
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.004
// Target subsystem base rate: 0.004
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.004
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// psi_filt                      ce_out        0.004
// r_filt                        ce_out        0.004
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Yaw_filter
// Source Path: Yaw_controller/Yaw_filter
// Hierarchy Level: 0
// Model version: 1.9
// 
// -------------------------------------------------------------


`timescale 1 ns / 1 ns

module Yaw_filter
          (clk,
           resetn,        // Changed to active-low reset for Block Diagram compliance
           clk_enable,
           gz,
           mag_yaw,
           ce_out,
           psi_filt,
           r_filt);


  input   clk;
  input   resetn;         // Changed to active-low reset
  input   clk_enable;
  input   signed [15:0] gz;  // sfix16_En10
  input   signed [15:0] mag_yaw;  // sfix16_En12
  output  ce_out;
  output  signed [15:0] psi_filt;  // sfix16_En12
  output  signed [15:0] r_filt;  // sfix16_En10


  wire enb;
  reg signed [15:0] mag_yaw_1;  // sfix16_En12
  wire signed [31:0] alpha1_beta_cast;  // sfix32_En24
  wire signed [15:0] alpha1_beta_out1;  // sfix16_En10
  wire signed [15:0] Add_out1;  // sfix16_En10
  reg signed [15:0] Add_out1_1;  // sfix16_En10
  reg signed [15:0] r_filt_prev_out1;  // sfix16_En10
  wire signed [31:0] beta_cast;  // sfix32_En24
  wire signed [15:0] beta_out1;  // sfix16_En10
  wire signed [15:0] Add_add_cast;  // sfix16_En11
  wire signed [16:0] Add_add_cast_1;  // sfix17_En11
  wire signed [15:0] Add_add_cast_2;  // sfix16_En11
  wire signed [16:0] Add_add_cast_3;  // sfix17_En11
  wire signed [16:0] Add_add_temp;  // sfix17_En11
  wire signed [15:0] Add_cast;  // sfix16_En11
  wire Constant_out1;  // ufix1_En8
  wire signed [15:0] Product_in1;  // sfix16_En18
  wire signed [16:0] Product_out1;  // sfix17_En18
  reg signed [16:0] Product_out1_1;  // sfix17_En18
  wire signed [15:0] Product_out1_2;  // sfix16_En12
  wire stateControl_1;
  reg  stateControl_2;
  wire signed [15:0] Constant3_out1;  // sfix16_En12
  wire signed [15:0] Constant2_out1;  // sfix16_En12
  wire signed [15:0] Constant4_out1;  // sfix16_En12
  wire signed [15:0] psi_filt_uncorrected_out1;  // sfix16_En12
  wire signed [16:0] error_raw1_sub_cast;  // sfix17_En12
  wire signed [16:0] error_raw1_sub_cast_1;  // sfix17_En12
  wire signed [16:0] error_raw1_sub_temp;  // sfix17_En12
  wire signed [15:0] error_raw1_out1;  // sfix16_En12
  wire switch_compare_1;
  wire signed [15:0] Switch1_out1;  // sfix16_En12
  wire signed [16:0] Add2_add_cast;  // sfix17_En12
  wire signed [16:0] Add2_add_cast_1;  // sfix17_En12
  wire signed [16:0] Add2_add_temp;  // sfix17_En12
  wire signed [15:0] Add2_out1;  // sfix16_En12
  wire signed [15:0] error_raw_out1;  // sfix16_En12
  wire signed [16:0] Subtract_sub_cast;  // sfix17_En12
  wire signed [16:0] Subtract_sub_cast_1;  // sfix17_En12
  wire signed [16:0] Subtract_sub_temp;  // sfix17_En12
  wire signed [15:0] Subtract_out1;  // sfix16_En12
  wire switch_compare_1_1;
  wire signed [15:0] Switch_out1;  // sfix16_En12
  wire signed [16:0] Add1_add_cast;  // sfix17_En12
  wire signed [16:0] Add1_add_cast_1;  // sfix17_En12
  wire signed [16:0] Add1_add_temp;  // sfix17_En12
  wire signed [15:0] Add1_out1;  // sfix16_En12
  reg signed [15:0] Unit_Delay1_out1;  // sfix16_En12
  wire signed [15:0] psi_filt_prev;  // sfix16_En12
  wire signed [15:0] psi_filt_prev_1;  // sfix16_En12
  wire signed [16:0] Sum_add_cast;  // sfix17_En12
  wire signed [16:0] Sum_add_cast_1;  // sfix17_En12
  wire signed [16:0] Sum_add_temp;  // sfix17_En12
  wire signed [15:0] psi_pred;  // sfix16_En12
  wire signed [16:0] error_raw_sub_cast;  // sfix17_En12
  wire signed [16:0] error_raw_sub_cast_1;  // sfix17_En12
  wire signed [16:0] error_raw_sub_temp;  // sfix17_En12
  wire switch_compare_1_2;
  wire signed [15:0] e_wrap_out1;  // sfix16_En12
  wire signed [31:0] alpha1_alpha_cast;  // sfix32_En26
  wire signed [15:0] alpha1_alpha_out1;  // sfix16_En12
  wire signed [16:0] psi_filt_uncorrected_add_cast;  // sfix17_En12
  wire signed [16:0] psi_filt_uncorrected_add_cast_1;  // sfix17_En12
  wire signed [16:0] psi_filt_uncorrected_add_temp;  // sfix17_En12
  wire switch_compare_1_3;
  wire signed [15:0] psi_filt_prev_2;  // sfix16_En12


  assign enb = clk_enable;

  // 1. Updated: delayMatch1_process
  always @(posedge clk)
    begin : delayMatch1_process
      if (resetn == 1'b0) begin
        mag_yaw_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          mag_yaw_1 <= mag_yaw;
        end
      end
    end

  assign alpha1_beta_cast = {{3{gz[15]}}, {gz, 13'b0000000000000}};
  assign alpha1_beta_out1 = (((alpha1_beta_cast[31] == 1'b0) && (alpha1_beta_cast[30:29] != 2'b00)) || ((alpha1_beta_cast[31] == 1'b0) && (alpha1_beta_cast[29:14] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((alpha1_beta_cast[31] == 1'b1) && (alpha1_beta_cast[30:29] != 2'b11) ? 16'sb1000000000000000 :
              alpha1_beta_cast[29:14] + $signed({1'b0, alpha1_beta_cast[13]})));

  // 2. Updated: delayMatch2_process
  always @(posedge clk)
    begin : delayMatch2_process
      if (resetn == 1'b0) begin
        Add_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Add_out1_1 <= Add_out1;
        end
      end
    end

  // 3. Updated: r_filt_prev_process
  always @(posedge clk)
    begin : r_filt_prev_process
      if (resetn == 1'b0) begin
        r_filt_prev_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          r_filt_prev_out1 <= Add_out1_1;
        end
      end
    end

  assign beta_cast = {{3{r_filt_prev_out1[15]}}, {r_filt_prev_out1, 13'b0000000000000}};
  assign beta_out1 = (((beta_cast[31] == 1'b0) && (beta_cast[30:29] != 2'b00)) || ((beta_cast[31] == 1'b0) && (beta_cast[29:14] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((beta_cast[31] == 1'b1) && (beta_cast[30:29] != 2'b11) ? 16'sb1000000000000000 :
              beta_cast[29:14] + $signed({1'b0, beta_cast[13]})));

  assign Add_add_cast = ((alpha1_beta_out1[15] == 1'b0) && (alpha1_beta_out1[14] != 1'b0) ? 16'sb0111111111111111 :
              ((alpha1_beta_out1[15] == 1'b1) && (alpha1_beta_out1[14] != 1'b1) ? 16'sb1000000000000000 :
              {alpha1_beta_out1[14:0], 1'b0}));
  assign Add_add_cast_1 = {Add_add_cast[15], Add_add_cast};
  assign Add_add_cast_2 = ((beta_out1[15] == 1'b0) && (beta_out1[14] != 1'b0) ? 16'sb0111111111111111 :
              ((beta_out1[15] == 1'b1) && (beta_out1[14] != 1'b1) ? 16'sb1000000000000000 :
              {beta_out1[14:0], 1'b0}));
  assign Add_add_cast_3 = {Add_add_cast_2[15], Add_add_cast_2};
  assign Add_add_temp = Add_add_cast_1 + Add_add_cast_3;
  assign Add_cast = ((Add_add_temp[16] == 1'b0) && (Add_add_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((Add_add_temp[16] == 1'b1) && (Add_add_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(Add_add_temp[15:0])));
  assign Add_out1 = ({Add_cast[15], Add_cast[15:1]}) + $signed({1'b0, Add_cast[0]});

  assign Constant_out1 = 1'b1;

  assign Product_in1 = (Constant_out1 == 1'b1 ? Add_out1 :
              16'sb0000000000000000);
  assign Product_out1 = {Product_in1[15], Product_in1};

  // 4. Updated: PipelineRegister_process
  always @(posedge clk)
    begin : PipelineRegister_process
      if (resetn == 1'b0) begin
        Product_out1_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          Product_out1_1 <= Product_out1;
        end
      end
    end

  assign Product_out1_2 = ({{5{Product_out1_1[16]}}, Product_out1_1[16:6]}) + $signed({1'b0, Product_out1_1[5]});

  assign stateControl_1 = 1'b1;

  // 5. Updated: delayMatch_process
  always @(posedge clk)
    begin : delayMatch_process
      if (resetn == 1'b0) begin
        stateControl_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          stateControl_2 <= stateControl_1;
        end
      end
    end

  assign Constant3_out1 = 16'sb0110010010001000;

  assign Constant2_out1 = 16'sb0110010010001000;

  assign Constant4_out1 = 16'sb0110010010001000;

  assign error_raw1_sub_cast = {psi_filt_uncorrected_out1[15], psi_filt_uncorrected_out1};
  assign error_raw1_sub_cast_1 = {Constant4_out1[15], Constant4_out1};
  assign error_raw1_sub_temp = error_raw1_sub_cast - error_raw1_sub_cast_1;
  assign error_raw1_out1 = ((error_raw1_sub_temp[16] == 1'b0) && (error_raw1_sub_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((error_raw1_sub_temp[16] == 1'b1) && (error_raw1_sub_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(error_raw1_sub_temp[15:0])));

  assign switch_compare_1 = psi_filt_uncorrected_out1 > 16'sb0011001001000100;

  assign Switch1_out1 = (switch_compare_1 == 1'b0 ? psi_filt_uncorrected_out1 :
              error_raw1_out1);

  assign Add2_add_cast = {psi_filt_uncorrected_out1[15], psi_filt_uncorrected_out1};
  assign Add2_add_cast_1 = {Constant4_out1[15], Constant4_out1};
  assign Add2_add_temp = Add2_add_cast + Add2_add_cast_1;
  assign Add2_out1 = ((Add2_add_temp[16] == 1'b0) && (Add2_add_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((Add2_add_temp[16] == 1'b1) && (Add2_add_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(Add2_add_temp[15:0])));

  assign Subtract_sub_cast = {error_raw_out1[15], error_raw_out1};
  assign Subtract_sub_cast_1 = {Constant2_out1[15], Constant2_out1};
  assign Subtract_sub_temp = Subtract_sub_cast - Subtract_sub_cast_1;
  assign Subtract_out1 = ((Subtract_sub_temp[16] == 1'b0) && (Subtract_sub_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((Subtract_sub_temp[16] == 1'b1) && (Subtract_sub_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(Subtract_sub_temp[15:0])));

  assign switch_compare_1_1 = error_raw_out1 > 16'sb0011001001000100;

  assign Switch_out1 = (switch_compare_1_1 == 1'b0 ? error_raw_out1 :
              Subtract_out1);

  assign Add1_add_cast = {error_raw_out1[15], error_raw_out1};
  assign Add1_add_cast_1 = {Constant3_out1[15], Constant3_out1};
  assign Add1_add_temp = Add1_add_cast + Add1_add_cast_1;
  assign Add1_out1 = ((Add1_add_temp[16] == 1'b0) && (Add1_add_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((Add1_add_temp[16] == 1'b1) && (Add1_add_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(Add1_add_temp[15:0])));

  assign psi_filt_prev_1 = (stateControl_2 == 1'b0 ? Unit_Delay1_out1 :
              psi_filt_prev);

  // 6. Updated: Unit_Delay1_process
  always @(posedge clk)
    begin : Unit_Delay1_process
      if (resetn == 1'b0) begin
        Unit_Delay1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Unit_Delay1_out1 <= psi_filt_prev_1;
        end
      end
    end

  assign Sum_add_cast = {Product_out1_2[15], Product_out1_2};
  assign Sum_add_cast_1 = {Unit_Delay1_out1[15], Unit_Delay1_out1};
  assign Sum_add_temp = Sum_add_cast + Sum_add_cast_1;
  assign psi_pred = ((Sum_add_temp[16] == 1'b0) && (Sum_add_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((Sum_add_temp[16] == 1'b1) && (Sum_add_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(Sum_add_temp[15:0])));

  assign error_raw_sub_cast = {mag_yaw_1[15], mag_yaw_1};
  assign error_raw_sub_cast_1 = {psi_pred[15], psi_pred};
  assign error_raw_sub_temp = error_raw_sub_cast - error_raw_sub_cast_1;
  assign error_raw_out1 = ((error_raw_sub_temp[16] == 1'b0) && (error_raw_sub_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((error_raw_sub_temp[16] == 1'b1) && (error_raw_sub_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(error_raw_sub_temp[15:0])));

  assign switch_compare_1_2 = error_raw_out1 >= 16'sb1100110110111100;

  assign e_wrap_out1 = (switch_compare_1_2 == 1'b0 ? Add1_out1 :
              Switch_out1);

  assign alpha1_alpha_cast = {{3{e_wrap_out1[15]}}, {e_wrap_out1, 13'b0000000000000}};
  assign alpha1_alpha_out1 = (((alpha1_alpha_cast[31] == 1'b0) && (alpha1_alpha_cast[30:29] != 2'b00)) || ((alpha1_alpha_cast[31] == 1'b0) && (alpha1_alpha_cast[29:14] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((alpha1_alpha_cast[31] == 1'b1) && (alpha1_alpha_cast[30:29] != 2'b11) ? 16'sb1000000000000000 :
              alpha1_alpha_cast[29:14] + $signed({1'b0, alpha1_alpha_cast[13]})));

  assign psi_filt_uncorrected_add_cast = {alpha1_alpha_out1[15], alpha1_alpha_out1};
  assign psi_filt_uncorrected_add_cast_1 = {psi_pred[15], psi_pred};
  assign psi_filt_uncorrected_add_temp = psi_filt_uncorrected_add_cast + psi_filt_uncorrected_add_cast_1;
  assign psi_filt_uncorrected_out1 = ((psi_filt_uncorrected_add_temp[16] == 1'b0) && (psi_filt_uncorrected_add_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((psi_filt_uncorrected_add_temp[16] == 1'b1) && (psi_filt_uncorrected_add_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(psi_filt_uncorrected_add_temp[15:0])));

  assign switch_compare_1_3 = psi_filt_uncorrected_out1 >= 16'sb1100110110111100;

  assign psi_filt_prev = (switch_compare_1_3 == 1'b0 ? Add2_out1 :
              Switch1_out1);

  assign psi_filt_prev_2 = psi_filt_prev;

  assign psi_filt = psi_filt_prev_2;

  assign r_filt = Add_out1_1;

  assign ce_out = clk_enable;

endmodule  // Yaw_filter