// -------------------------------------------------------------
// 
// File Name: C:\Users\Labhesh\OneDrive\Desktop\IIT Madras\Startup\FPGA\Attitude_Controller\Attitude_filter\hdlsrc\Attitude_filter\Complementary_filter.v
// Created: 2026-07-04 12:22:17
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.004
// Target subsystem base rate: 0.004
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.004
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// phi                           ce_out        0.004
// theta                         ce_out        0.004
// p_filt                        ce_out        0.004
// q_filt                        ce_out        0.004
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Complementary_filter
// Source Path: Attitude_filter/Complementary filter
// Hierarchy Level: 0
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Complementary_filter
          (clk,
           reset,
           clk_enable,
           gx,
           gy,
           ax,
           ay,
           az,
           dt,
           alpha_2,
           alpha1_alpha_2,
           ce_out,
           phi,
           theta,
           p_filt,
           q_filt);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] gx;  // sfix16_En10
  input   signed [15:0] gy;  // sfix16_En10
  input   signed [15:0] ax;  // sfix16_En11
  input   signed [15:0] ay;  // sfix16_En11
  input   signed [15:0] az;  // sfix16_En11
  input   [11:0] dt;  // ufix12_En12
  input   signed [15:0] alpha_2;  // sfix16_En14
  input   signed [15:0] alpha1_alpha_2;  // sfix16_En14
  output  ce_out;
  output  signed [15:0] phi;  // sfix16_En14
  output  signed [15:0] theta;  // sfix16_En14
  output  signed [15:0] p_filt;  // sfix16_En10
  output  signed [15:0] q_filt;  // sfix16_En10


  wire enb;
  wire signed [12:0] Product_cast;  // sfix13_En12
  wire signed [28:0] Product_mul_temp;  // sfix29_En22
  wire signed [27:0] Product_cast_1;  // sfix28_En22
  wire signed [23:0] Product_out1;  // sfix24_En16
  wire signed [15:0] phi_acc_out1;  // sfix16_En13
  wire signed [31:0] alpha1_alpha_mul_temp;  // sfix32_En27
  wire signed [15:0] alpha1_alpha_out1;  // sfix16_En14
  wire signed [15:0] Add_out1;  // sfix16_En14
  reg signed [15:0] Unit_Delay_out1;  // sfix16_En14
  wire signed [31:0] Sum_add_cast;  // sfix32_En16
  wire signed [31:0] Sum_add_cast_1;  // sfix32_En16
  wire signed [31:0] Sum_add_temp;  // sfix32_En16
  wire signed [15:0] Sum_out1;  // sfix16_En14
  wire signed [31:0] alpha_mul_temp;  // sfix32_En28
  wire signed [15:0] alpha_out1;  // sfix16_En14
  wire signed [16:0] Add_add_cast;  // sfix17_En14
  wire signed [16:0] Add_add_cast_1;  // sfix17_En14
  wire signed [16:0] Add_add_temp;  // sfix17_En14
  wire signed [31:0] multiplier_mul_temp;  // sfix32_En22
  wire signed [31:0] Math_Function1_out1;  // sfix32_En20
  wire signed [12:0] Product1_cast;  // sfix13_En12
  wire signed [28:0] Product1_mul_temp;  // sfix29_En22
  wire signed [27:0] Product1_cast_1;  // sfix28_En22
  wire signed [31:0] Product1_out1;  // sfix32_En22
  wire signed [16:0] Gain_cast;  // sfix17_En11
  wire signed [16:0] Gain_cast_1;  // sfix17_En11
  wire signed [31:0] Gain_cast_2;  // sfix32_En26
  wire signed [15:0] Gain_out1;  // sfix16_En11
  wire signed [31:0] multiplier1_mul_temp;  // sfix32_En22
  wire signed [31:0] Math_Function2_out1;  // sfix32_En20
  wire signed [15:0] Add2_add_cast;  // sfix16_En12
  wire signed [16:0] Add2_add_cast_1;  // sfix17_En12
  wire signed [15:0] Add2_add_cast_2;  // sfix16_En12
  wire signed [16:0] Add2_add_cast_3;  // sfix17_En12
  wire signed [16:0] Add2_add_temp;  // sfix17_En12
  wire signed [15:0] Add2_cast;  // sfix16_En12
  wire [15:0] Add2_out1;  // ufix16_En12
  wire signed [15:0] Sqrt_out1;  // sfix16_En11
  wire signed [15:0] theta_acc_out1;  // sfix16_En13
  wire signed [31:0] alpha1_alpha1_mul_temp;  // sfix32_En27
  wire signed [15:0] alpha1_alpha1_out1;  // sfix16_En14
  wire signed [15:0] Add1_out1;  // sfix16_En14
  reg signed [15:0] Unit_Delay1_out1;  // sfix16_En14
  wire signed [31:0] Sum1_add_cast;  // sfix32_En14
  wire signed [31:0] Sum1_add_cast_1;  // sfix32_En14
  wire signed [31:0] Sum1_add_temp;  // sfix32_En14
  wire signed [15:0] Sum1_out1;  // sfix16_En14
  wire signed [31:0] alpha1_mul_temp;  // sfix32_En28
  wire signed [15:0] alpha1_out1;  // sfix16_En14
  wire signed [31:0] Add1_add_cast;  // sfix32_En14
  wire signed [31:0] Add1_add_cast_1;  // sfix32_En14
  wire signed [31:0] Add1_add_temp;  // sfix32_En14
  wire signed [31:0] Product2_mul_temp;  // sfix32_En24
  wire signed [15:0] Product2_out1;  // sfix16_En10
  wire signed [15:0] Add3_out1;  // sfix16_En10
  reg signed [15:0] Unit_Delay2_out1;  // sfix16_En10
  wire signed [31:0] Product3_mul_temp;  // sfix32_En24
  wire signed [15:0] Product3_out1;  // sfix16_En10
  wire signed [16:0] Add3_add_cast;  // sfix17_En10
  wire signed [16:0] Add3_add_cast_1;  // sfix17_En10
  wire signed [16:0] Add3_add_temp;  // sfix17_En10
  wire signed [31:0] alpha3_cast;  // sfix32_En24
  wire signed [15:0] alpha3_out1;  // sfix16_En14
  wire signed [15:0] Add4_out1;  // sfix16_En10
  reg signed [15:0] Unit_Delay3_out1;  // sfix16_En10
  wire signed [31:0] alpha1_alpha3_cast;  // sfix32_En24
  wire signed [15:0] alpha1_alpha3_out1;  // sfix16_En14
  wire signed [15:0] Add4_add_cast;  // sfix16_En10
  wire signed [15:0] Add4_add_cast_1;  // sfix16_En10


  assign enb = clk_enable;

  assign Product_cast = {1'b0, dt};
  assign Product_mul_temp = gx * Product_cast;
  assign Product_cast_1 = Product_mul_temp[27:0];
  assign Product_out1 = {{2{Product_cast_1[27]}}, Product_cast_1[27:6]};

  phi_acc u_phi_acc (.y_in(ay),  // sfix16_En11
                     .x_in(az),  // sfix16_En11
                     .angle(phi_acc_out1)  // sfix16_En13
                     );

  assign alpha1_alpha_mul_temp = 16'sb0000000010000011 * phi_acc_out1;
  assign alpha1_alpha_out1 = (((alpha1_alpha_mul_temp[31] == 1'b0) && (alpha1_alpha_mul_temp[30:28] != 3'b000)) || ((alpha1_alpha_mul_temp[31] == 1'b0) && (alpha1_alpha_mul_temp[28:13] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((alpha1_alpha_mul_temp[31] == 1'b1) && (alpha1_alpha_mul_temp[30:28] != 3'b111) ? 16'sb1000000000000000 :
              alpha1_alpha_mul_temp[28:13] + $signed({1'b0, alpha1_alpha_mul_temp[12]})));

  always @(posedge clk or posedge reset)
    begin : Unit_Delay_process
      if (reset == 1'b1) begin
        Unit_Delay_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Unit_Delay_out1 <= Add_out1;
        end
      end
    end

  assign Sum_add_cast = {{14{Unit_Delay_out1[15]}}, {Unit_Delay_out1, 2'b00}};
  assign Sum_add_cast_1 = {{8{Product_out1[23]}}, Product_out1};
  assign Sum_add_temp = Sum_add_cast + Sum_add_cast_1;
  assign Sum_out1 = (((Sum_add_temp[31] == 1'b0) && (Sum_add_temp[30:17] != 14'b00000000000000)) || ((Sum_add_temp[31] == 1'b0) && (Sum_add_temp[17:2] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((Sum_add_temp[31] == 1'b1) && (Sum_add_temp[30:17] != 14'b11111111111111) ? 16'sb1000000000000000 :
              Sum_add_temp[17:2] + $signed({1'b0, Sum_add_temp[1]})));

  assign alpha_mul_temp = 16'sb0011111101111101 * Sum_out1;
  assign alpha_out1 = (((alpha_mul_temp[31] == 1'b0) && (alpha_mul_temp[30:29] != 2'b00)) || ((alpha_mul_temp[31] == 1'b0) && (alpha_mul_temp[29:14] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((alpha_mul_temp[31] == 1'b1) && (alpha_mul_temp[30:29] != 2'b11) ? 16'sb1000000000000000 :
              alpha_mul_temp[29:14] + $signed({1'b0, alpha_mul_temp[13]})));

  assign Add_add_cast = {alpha_out1[15], alpha_out1};
  assign Add_add_cast_1 = {alpha1_alpha_out1[15], alpha1_alpha_out1};
  assign Add_add_temp = Add_add_cast + Add_add_cast_1;
  assign Add_out1 = ((Add_add_temp[16] == 1'b0) && (Add_add_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((Add_add_temp[16] == 1'b1) && (Add_add_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(Add_add_temp[15:0])));

  assign phi = Add_out1;

  assign multiplier_mul_temp = az * az;
  assign Math_Function1_out1 = ({{2{multiplier_mul_temp[31]}}, multiplier_mul_temp[31:2]}) + $signed({1'b0, multiplier_mul_temp[1]});

  assign Product1_cast = {1'b0, dt};
  assign Product1_mul_temp = Product1_cast * gy;
  assign Product1_cast_1 = Product1_mul_temp[27:0];
  assign Product1_out1 = {{4{Product1_cast_1[27]}}, Product1_cast_1};

  assign Gain_cast = {ax[15], ax};
  assign Gain_cast_1 =  - (Gain_cast);
  assign Gain_cast_2 = {Gain_cast_1, 15'b000000000000000};
  assign Gain_out1 = (((Gain_cast_2[31] == 1'b0) && (Gain_cast_2[30] != 1'b0)) || ((Gain_cast_2[31] == 1'b0) && (Gain_cast_2[30:15] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((Gain_cast_2[31] == 1'b1) && (Gain_cast_2[30] != 1'b1) ? 16'sb1000000000000000 :
              Gain_cast_2[30:15] + $signed({1'b0, Gain_cast_2[14]})));

  assign multiplier1_mul_temp = ay * ay;
  assign Math_Function2_out1 = ({{2{multiplier1_mul_temp[31]}}, multiplier1_mul_temp[31:2]}) + $signed({1'b0, multiplier1_mul_temp[1]});

  assign Add2_add_cast = (((Math_Function1_out1[31] == 1'b0) && (Math_Function1_out1[30:23] != 8'b00000000)) || ((Math_Function1_out1[31] == 1'b0) && (Math_Function1_out1[23:8] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((Math_Function1_out1[31] == 1'b1) && (Math_Function1_out1[30:23] != 8'b11111111) ? 16'sb1000000000000000 :
              Math_Function1_out1[23:8] + $signed({1'b0, Math_Function1_out1[7]})));
  assign Add2_add_cast_1 = {Add2_add_cast[15], Add2_add_cast};
  assign Add2_add_cast_2 = (((Math_Function2_out1[31] == 1'b0) && (Math_Function2_out1[30:23] != 8'b00000000)) || ((Math_Function2_out1[31] == 1'b0) && (Math_Function2_out1[23:8] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((Math_Function2_out1[31] == 1'b1) && (Math_Function2_out1[30:23] != 8'b11111111) ? 16'sb1000000000000000 :
              Math_Function2_out1[23:8] + $signed({1'b0, Math_Function2_out1[7]})));
  assign Add2_add_cast_3 = {Add2_add_cast_2[15], Add2_add_cast_2};
  assign Add2_add_temp = Add2_add_cast_1 + Add2_add_cast_3;
  assign Add2_cast = ((Add2_add_temp[16] == 1'b0) && (Add2_add_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((Add2_add_temp[16] == 1'b1) && (Add2_add_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(Add2_add_temp[15:0])));
  assign Add2_out1 = (Add2_cast[15] == 1'b1 ? 16'b0000000000000000 :
              Add2_cast);

  Sqrt u_Sqrt (.din(Add2_out1),  // ufix16_En12
               .dout(Sqrt_out1)  // sfix16_En11
               );

  theta_acc u_theta_acc (.y_in(Gain_out1),  // sfix16_En11
                         .x_in(Sqrt_out1),  // sfix16_En11
                         .angle(theta_acc_out1)  // sfix16_En13
                         );

  assign alpha1_alpha1_mul_temp = 16'sb0000000010000011 * theta_acc_out1;
  assign alpha1_alpha1_out1 = (((alpha1_alpha1_mul_temp[31] == 1'b0) && (alpha1_alpha1_mul_temp[30:28] != 3'b000)) || ((alpha1_alpha1_mul_temp[31] == 1'b0) && (alpha1_alpha1_mul_temp[28:13] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((alpha1_alpha1_mul_temp[31] == 1'b1) && (alpha1_alpha1_mul_temp[30:28] != 3'b111) ? 16'sb1000000000000000 :
              alpha1_alpha1_mul_temp[28:13] + $signed({1'b0, alpha1_alpha1_mul_temp[12]})));

  always @(posedge clk or posedge reset)
    begin : Unit_Delay1_process
      if (reset == 1'b1) begin
        Unit_Delay1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Unit_Delay1_out1 <= Add1_out1;
        end
      end
    end

  assign Sum1_add_cast = {{16{Unit_Delay1_out1[15]}}, Unit_Delay1_out1};
  assign Sum1_add_cast_1 = ({{8{Product1_out1[31]}}, Product1_out1[31:8]}) + $signed({1'b0, Product1_out1[7]});
  assign Sum1_add_temp = Sum1_add_cast + Sum1_add_cast_1;
  assign Sum1_out1 = ((Sum1_add_temp[31] == 1'b0) && (Sum1_add_temp[30:15] != 16'b0000000000000000) ? 16'sb0111111111111111 :
              ((Sum1_add_temp[31] == 1'b1) && (Sum1_add_temp[30:15] != 16'b1111111111111111) ? 16'sb1000000000000000 :
              $signed(Sum1_add_temp[15:0])));

  assign alpha1_mul_temp = 16'sb0011111101111101 * Sum1_out1;
  assign alpha1_out1 = (((alpha1_mul_temp[31] == 1'b0) && (alpha1_mul_temp[30:29] != 2'b00)) || ((alpha1_mul_temp[31] == 1'b0) && (alpha1_mul_temp[29:14] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((alpha1_mul_temp[31] == 1'b1) && (alpha1_mul_temp[30:29] != 2'b11) ? 16'sb1000000000000000 :
              alpha1_mul_temp[29:14] + $signed({1'b0, alpha1_mul_temp[13]})));

  assign Add1_add_cast = {{16{alpha1_out1[15]}}, alpha1_out1};
  assign Add1_add_cast_1 = {{16{alpha1_alpha1_out1[15]}}, alpha1_alpha1_out1};
  assign Add1_add_temp = Add1_add_cast + Add1_add_cast_1;
  assign Add1_out1 = Add1_add_temp[15:0];

  assign theta = Add1_out1;

  assign Product2_mul_temp = alpha_2 * gx;
  assign Product2_out1 = (((Product2_mul_temp[31] == 1'b0) && (Product2_mul_temp[30:29] != 2'b00)) || ((Product2_mul_temp[31] == 1'b0) && (Product2_mul_temp[29:14] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((Product2_mul_temp[31] == 1'b1) && (Product2_mul_temp[30:29] != 2'b11) ? 16'sb1000000000000000 :
              Product2_mul_temp[29:14] + $signed({1'b0, Product2_mul_temp[13]})));

  always @(posedge clk or posedge reset)
    begin : Unit_Delay2_process
      if (reset == 1'b1) begin
        Unit_Delay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Unit_Delay2_out1 <= Add3_out1;
        end
      end
    end

  assign Product3_mul_temp = Unit_Delay2_out1 * alpha1_alpha_2;
  assign Product3_out1 = (((Product3_mul_temp[31] == 1'b0) && (Product3_mul_temp[30:29] != 2'b00)) || ((Product3_mul_temp[31] == 1'b0) && (Product3_mul_temp[29:14] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((Product3_mul_temp[31] == 1'b1) && (Product3_mul_temp[30:29] != 2'b11) ? 16'sb1000000000000000 :
              Product3_mul_temp[29:14] + $signed({1'b0, Product3_mul_temp[13]})));

  assign Add3_add_cast = {Product2_out1[15], Product2_out1};
  assign Add3_add_cast_1 = {Product3_out1[15], Product3_out1};
  assign Add3_add_temp = Add3_add_cast + Add3_add_cast_1;
  assign Add3_out1 = ((Add3_add_temp[16] == 1'b0) && (Add3_add_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((Add3_add_temp[16] == 1'b1) && (Add3_add_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(Add3_add_temp[15:0])));

  assign p_filt = Add3_out1;

  assign alpha3_cast = {{3{gy[15]}}, {gy, 13'b0000000000000}};
  assign alpha3_out1 = (((alpha3_cast[31] == 1'b0) && (alpha3_cast[30:25] != 6'b000000)) || ((alpha3_cast[31] == 1'b0) && (alpha3_cast[25:10] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((alpha3_cast[31] == 1'b1) && (alpha3_cast[30:25] != 6'b111111) ? 16'sb1000000000000000 :
              alpha3_cast[25:10] + $signed({1'b0, alpha3_cast[9]})));

  always @(posedge clk or posedge reset)
    begin : Unit_Delay3_process
      if (reset == 1'b1) begin
        Unit_Delay3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Unit_Delay3_out1 <= Add4_out1;
        end
      end
    end

  assign alpha1_alpha3_cast = {{3{Unit_Delay3_out1[15]}}, {Unit_Delay3_out1, 13'b0000000000000}};
  assign alpha1_alpha3_out1 = (((alpha1_alpha3_cast[31] == 1'b0) && (alpha1_alpha3_cast[30:25] != 6'b000000)) || ((alpha1_alpha3_cast[31] == 1'b0) && (alpha1_alpha3_cast[25:10] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((alpha1_alpha3_cast[31] == 1'b1) && (alpha1_alpha3_cast[30:25] != 6'b111111) ? 16'sb1000000000000000 :
              alpha1_alpha3_cast[25:10] + $signed({1'b0, alpha1_alpha3_cast[9]})));

  assign Add4_add_cast = ({{4{alpha3_out1[15]}}, alpha3_out1[15:4]}) + $signed({1'b0, alpha3_out1[3]});
  assign Add4_add_cast_1 = ({{4{alpha1_alpha3_out1[15]}}, alpha1_alpha3_out1[15:4]}) + $signed({1'b0, alpha1_alpha3_out1[3]});
  assign Add4_out1 = Add4_add_cast + Add4_add_cast_1;

  assign q_filt = Add4_out1;

  assign ce_out = clk_enable;

endmodule  // Complementary_filter
