// -------------------------------------------------------------
// 
// File Name: C:\Users\Labhesh\OneDrive\Desktop\IIT Madras\Startup\FPGA\Attitude_Controller\Attitude_filter\hdlsrc\Attitude_filter\phi_acc.v
// Created: 2026-07-04 12:22:17
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: phi_acc
// Source Path: Attitude_filter/Complementary filter/phi_acc
// Hierarchy Level: 1
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module phi_acc
          (y_in,
           x_in,
           angle);


  input   signed [15:0] y_in;  // sfix16_En11
  input   signed [15:0] x_in;  // sfix16_En11
  output  signed [15:0] angle;  // sfix16_En13


  wire signed [17:0] y_in_ext;  // sfix18_En11
  wire y_in_msb;  // ufix1
  wire switch_compare_1;
  wire comp_zero;  // ufix1
  wire y_non_zero;  // ufix1
  wire signed [17:0] x_in_ext;  // sfix18_En11
  wire x_in_msb;  // ufix1
  wire [2:0] x_y_adjust;  // ufix3
  wire signed [15:0] zero;  // sfix16_En13
  wire signed [15:0] onePi_1;  // sfix16_En13
  wire switch_compare_1_1;
  wire signed [18:0] y_in_reg_neg_cast;  // sfix19_En11
  wire signed [18:0] y_in_reg_neg_cast_1;  // sfix19_En11
  wire signed [17:0] y_in_reg_neg_1;  // sfix18_En11
  wire signed [17:0] y_pre_quadcorr_out;  // sfix18_En11
  wire y0_p_msb;  // ufix1
  wire switch_compare_1_2;
  wire switch_compare_1_3;
  wire signed [18:0] x_in_reg_neg_cast;  // sfix19_En11
  wire signed [18:0] x_in_reg_neg_cast_1;  // sfix19_En11
  wire signed [17:0] x_in_reg_neg_1;  // sfix18_En11
  wire signed [17:0] x_pre_quadcorr_out;  // sfix18_En11
  wire signed [17:0] y_temp1;  // sfix18_En11
  wire signed [17:0] y_temp_0_1_1;  // sfix18_En11
  wire signed [17:0] y1;  // sfix18_En11
  wire y1_p_msb;  // ufix1
  wire switch_compare_1_4;
  wire switch_compare_1_5;
  wire signed [17:0] x_temp1;  // sfix18_En11
  wire signed [17:0] x_temp_0_1_1;  // sfix18_En11
  wire signed [17:0] x1;  // sfix18_En11
  wire signed [17:0] x_shift2;  // sfix18_En11
  wire signed [17:0] y_temp2;  // sfix18_En11
  wire signed [17:0] y_temp_0_2_1;  // sfix18_En11
  wire signed [17:0] y2;  // sfix18_En11
  wire y2_p_msb;  // ufix1
  wire switch_compare_1_6;
  wire switch_compare_1_7;
  wire signed [17:0] y_shift2;  // sfix18_En11
  wire signed [17:0] x_temp2;  // sfix18_En11
  wire signed [17:0] x_temp_0_2_1;  // sfix18_En11
  wire signed [17:0] x2;  // sfix18_En11
  wire signed [17:0] x_shift3;  // sfix18_En11
  wire signed [17:0] y_temp3;  // sfix18_En11
  wire signed [17:0] y_temp_0_3_1;  // sfix18_En11
  wire signed [17:0] y3;  // sfix18_En11
  wire y3_p_msb;  // ufix1
  wire switch_compare_1_8;
  wire switch_compare_1_9;
  wire signed [17:0] y_shift3;  // sfix18_En11
  wire signed [17:0] x_temp3;  // sfix18_En11
  wire signed [17:0] x_temp_0_3_1;  // sfix18_En11
  wire signed [17:0] x3;  // sfix18_En11
  wire signed [17:0] x_shift4;  // sfix18_En11
  wire signed [17:0] y_temp4;  // sfix18_En11
  wire signed [17:0] y_temp_0_4_1;  // sfix18_En11
  wire signed [17:0] y4;  // sfix18_En11
  wire y4_p_msb;  // ufix1
  wire switch_compare_1_10;
  wire switch_compare_1_11;
  wire signed [17:0] y_shift4;  // sfix18_En11
  wire signed [17:0] x_temp4;  // sfix18_En11
  wire signed [17:0] x_temp_0_4_1;  // sfix18_En11
  wire signed [17:0] x4;  // sfix18_En11
  wire signed [17:0] x_shift5;  // sfix18_En11
  wire signed [17:0] y_temp5;  // sfix18_En11
  wire signed [17:0] y_temp_0_5_1;  // sfix18_En11
  wire signed [17:0] y5;  // sfix18_En11
  wire y5_p_msb;  // ufix1
  wire switch_compare_1_12;
  wire switch_compare_1_13;
  wire signed [17:0] y_shift5;  // sfix18_En11
  wire signed [17:0] x_temp5;  // sfix18_En11
  wire signed [17:0] x_temp_0_5_1;  // sfix18_En11
  wire signed [17:0] x5;  // sfix18_En11
  wire signed [17:0] x_shift6;  // sfix18_En11
  wire signed [17:0] y_temp6;  // sfix18_En11
  wire signed [17:0] y_temp_0_6_1;  // sfix18_En11
  wire signed [17:0] y6;  // sfix18_En11
  wire y6_p_msb;  // ufix1
  wire switch_compare_1_14;
  wire switch_compare_1_15;
  wire signed [17:0] y_shift6;  // sfix18_En11
  wire signed [17:0] x_temp6;  // sfix18_En11
  wire signed [17:0] x_temp_0_6_1;  // sfix18_En11
  wire signed [17:0] x6;  // sfix18_En11
  wire signed [17:0] x_shift7;  // sfix18_En11
  wire signed [17:0] y_temp7;  // sfix18_En11
  wire signed [17:0] y_temp_0_7_1;  // sfix18_En11
  wire signed [17:0] y7;  // sfix18_En11
  wire y7_p_msb;  // ufix1
  wire switch_compare_1_16;
  wire switch_compare_1_17;
  wire signed [17:0] y_shift7;  // sfix18_En11
  wire signed [17:0] x_temp7;  // sfix18_En11
  wire signed [17:0] x_temp_0_7_1;  // sfix18_En11
  wire signed [17:0] x7;  // sfix18_En11
  wire signed [17:0] x_shift8;  // sfix18_En11
  wire signed [17:0] y_temp8;  // sfix18_En11
  wire signed [17:0] y_temp_0_8_1;  // sfix18_En11
  wire signed [17:0] y8;  // sfix18_En11
  wire y8_p_msb;  // ufix1
  wire switch_compare_1_18;
  wire switch_compare_1_19;
  wire signed [17:0] y_shift8;  // sfix18_En11
  wire signed [17:0] x_temp8;  // sfix18_En11
  wire signed [17:0] x_temp_0_8_1;  // sfix18_En11
  wire signed [17:0] x8;  // sfix18_En11
  wire signed [17:0] x_shift9;  // sfix18_En11
  wire signed [17:0] y_temp9;  // sfix18_En11
  wire signed [17:0] y_temp_0_9_1;  // sfix18_En11
  wire signed [17:0] y9;  // sfix18_En11
  wire y9_p_msb;  // ufix1
  wire switch_compare_1_20;
  wire switch_compare_1_21;
  wire signed [17:0] y_shift9;  // sfix18_En11
  wire signed [17:0] x_temp9;  // sfix18_En11
  wire signed [17:0] x_temp_0_9_1;  // sfix18_En11
  wire signed [17:0] x9;  // sfix18_En11
  wire signed [17:0] x_shift10;  // sfix18_En11
  wire signed [17:0] y_temp10;  // sfix18_En11
  wire signed [17:0] y_temp_0_10_1;  // sfix18_En11
  wire signed [17:0] y10;  // sfix18_En11
  wire y10_p_msb;  // ufix1
  wire switch_compare_1_22;
  wire switch_compare_1_23;
  wire switch_compare_1_24;
  wire switch_compare_1_25;
  wire switch_compare_1_26;
  wire switch_compare_1_27;
  wire switch_compare_1_28;
  wire switch_compare_1_29;
  wire switch_compare_1_30;
  wire switch_compare_1_31;
  wire switch_compare_1_32;
  wire signed [17:0] z0;  // sfix18_En13
  wire signed [17:0] lut_value_s1;  // sfix18_En13
  wire signed [17:0] lut_value_temp1;  // sfix18_En13
  wire signed [17:0] y_temp_0_1_2;  // sfix18_En13
  wire signed [17:0] z1;  // sfix18_En13
  wire signed [17:0] lut_value_s2;  // sfix18_En13
  wire signed [17:0] lut_value_temp2;  // sfix18_En13
  wire signed [17:0] y_temp_0_2_2;  // sfix18_En13
  wire signed [17:0] z2;  // sfix18_En13
  wire signed [17:0] lut_value_s3;  // sfix18_En13
  wire signed [17:0] lut_value_temp3;  // sfix18_En13
  wire signed [17:0] y_temp_0_3_2;  // sfix18_En13
  wire signed [17:0] z3;  // sfix18_En13
  wire signed [17:0] lut_value_s4;  // sfix18_En13
  wire signed [17:0] lut_value_temp4;  // sfix18_En13
  wire signed [17:0] y_temp_0_4_2;  // sfix18_En13
  wire signed [17:0] z4;  // sfix18_En13
  wire signed [17:0] lut_value_s5;  // sfix18_En13
  wire signed [17:0] lut_value_temp5;  // sfix18_En13
  wire signed [17:0] y_temp_0_5_2;  // sfix18_En13
  wire signed [17:0] z5;  // sfix18_En13
  wire signed [17:0] lut_value_s6;  // sfix18_En13
  wire signed [17:0] lut_value_temp6;  // sfix18_En13
  wire signed [17:0] y_temp_0_6_2;  // sfix18_En13
  wire signed [17:0] z6;  // sfix18_En13
  wire signed [17:0] lut_value_s7;  // sfix18_En13
  wire signed [17:0] lut_value_temp7;  // sfix18_En13
  wire signed [17:0] y_temp_0_7_2;  // sfix18_En13
  wire signed [17:0] z7;  // sfix18_En13
  wire signed [17:0] lut_value_s8;  // sfix18_En13
  wire signed [17:0] lut_value_temp8;  // sfix18_En13
  wire signed [17:0] y_temp_0_8_2;  // sfix18_En13
  wire signed [17:0] z8;  // sfix18_En13
  wire signed [17:0] lut_value_s9;  // sfix18_En13
  wire signed [17:0] lut_value_temp9;  // sfix18_En13
  wire signed [17:0] y_temp_0_9_2;  // sfix18_En13
  wire signed [17:0] z9;  // sfix18_En13
  wire signed [17:0] lut_value_s10;  // sfix18_En13
  wire signed [17:0] lut_value_temp10;  // sfix18_En13
  wire signed [17:0] y_temp_0_10_2;  // sfix18_En13
  wire signed [17:0] z10;  // sfix18_En13
  wire signed [17:0] lut_value_s11;  // sfix18_En13
  wire signed [17:0] lut_value_temp11;  // sfix18_En13
  wire signed [17:0] y_temp_0_11;  // sfix18_En13
  wire signed [17:0] z11;  // sfix18_En13
  wire signed [15:0] z_out;  // sfix16_En13
  wire signed [16:0] z_temp3_cast;  // sfix17_En13
  wire signed [16:0] z_temp3_cast_1;  // sfix17_En13
  wire signed [15:0] z_temp3_1;  // sfix16_En13
  wire signed [15:0] z_temp2_1;  // sfix16_En13
  wire signed [15:0] z_temp1_1;  // sfix16_En13
  reg signed [15:0] z_out_adjust;  // sfix16_En13


  assign y_in_ext = {{2{y_in[15]}}, y_in};

  assign y_in_msb = y_in_ext[17];

  assign switch_compare_1 = y_in_msb > 1'b0;

  assign comp_zero = y_in_ext > 18'sb000000000000000000;

  assign y_non_zero = (switch_compare_1 == 1'b0 ? comp_zero :
              y_in_msb);

  assign x_in_ext = {{2{x_in[15]}}, x_in};

  assign x_in_msb = x_in_ext[17];

  assign x_y_adjust = {y_non_zero, x_in_msb, y_in_msb};

  assign zero = 16'sb0000000000000000;

  assign onePi_1 = 16'sb0110010010001000;

  assign switch_compare_1_1 = y_in_msb > 1'b0;

  assign y_in_reg_neg_cast = {y_in_ext[17], y_in_ext};
  assign y_in_reg_neg_cast_1 =  - (y_in_reg_neg_cast);
  assign y_in_reg_neg_1 = y_in_reg_neg_cast_1[17:0];

  assign y_pre_quadcorr_out = (switch_compare_1_1 == 1'b0 ? y_in_ext :
              y_in_reg_neg_1);

  assign y0_p_msb = y_pre_quadcorr_out[17];

  assign switch_compare_1_2 = y0_p_msb > 1'b0;

  assign switch_compare_1_3 = x_in_msb > 1'b0;

  assign x_in_reg_neg_cast = {x_in_ext[17], x_in_ext};
  assign x_in_reg_neg_cast_1 =  - (x_in_reg_neg_cast);
  assign x_in_reg_neg_1 = x_in_reg_neg_cast_1[17:0];

  assign x_pre_quadcorr_out = (switch_compare_1_3 == 1'b0 ? x_in_ext :
              x_in_reg_neg_1);

  assign y_temp1 = y_pre_quadcorr_out - x_pre_quadcorr_out;

  assign y_temp_0_1_1 = y_pre_quadcorr_out + x_pre_quadcorr_out;

  assign y1 = (switch_compare_1_2 == 1'b0 ? y_temp1 :
              y_temp_0_1_1);

  assign y1_p_msb = y1[17];

  assign switch_compare_1_4 = y1_p_msb > 1'b0;

  assign switch_compare_1_5 = y0_p_msb > 1'b0;

  assign x_temp1 = x_pre_quadcorr_out + y_pre_quadcorr_out;

  assign x_temp_0_1_1 = x_pre_quadcorr_out - y_pre_quadcorr_out;

  assign x1 = (switch_compare_1_5 == 1'b0 ? x_temp1 :
              x_temp_0_1_1);

  assign x_shift2 = x1 >>> 8'd1;

  assign y_temp2 = y1 - x_shift2;

  assign y_temp_0_2_1 = y1 + x_shift2;

  assign y2 = (switch_compare_1_4 == 1'b0 ? y_temp2 :
              y_temp_0_2_1);

  assign y2_p_msb = y2[17];

  assign switch_compare_1_6 = y2_p_msb > 1'b0;

  assign switch_compare_1_7 = y1_p_msb > 1'b0;

  assign y_shift2 = y1 >>> 8'd1;

  assign x_temp2 = x1 + y_shift2;

  assign x_temp_0_2_1 = x1 - y_shift2;

  assign x2 = (switch_compare_1_7 == 1'b0 ? x_temp2 :
              x_temp_0_2_1);

  assign x_shift3 = x2 >>> 8'd2;

  assign y_temp3 = y2 - x_shift3;

  assign y_temp_0_3_1 = y2 + x_shift3;

  assign y3 = (switch_compare_1_6 == 1'b0 ? y_temp3 :
              y_temp_0_3_1);

  assign y3_p_msb = y3[17];

  assign switch_compare_1_8 = y3_p_msb > 1'b0;

  assign switch_compare_1_9 = y2_p_msb > 1'b0;

  assign y_shift3 = y2 >>> 8'd2;

  assign x_temp3 = x2 + y_shift3;

  assign x_temp_0_3_1 = x2 - y_shift3;

  assign x3 = (switch_compare_1_9 == 1'b0 ? x_temp3 :
              x_temp_0_3_1);

  assign x_shift4 = x3 >>> 8'd3;

  assign y_temp4 = y3 - x_shift4;

  assign y_temp_0_4_1 = y3 + x_shift4;

  assign y4 = (switch_compare_1_8 == 1'b0 ? y_temp4 :
              y_temp_0_4_1);

  assign y4_p_msb = y4[17];

  assign switch_compare_1_10 = y4_p_msb > 1'b0;

  assign switch_compare_1_11 = y3_p_msb > 1'b0;

  assign y_shift4 = y3 >>> 8'd3;

  assign x_temp4 = x3 + y_shift4;

  assign x_temp_0_4_1 = x3 - y_shift4;

  assign x4 = (switch_compare_1_11 == 1'b0 ? x_temp4 :
              x_temp_0_4_1);

  assign x_shift5 = x4 >>> 8'd4;

  assign y_temp5 = y4 - x_shift5;

  assign y_temp_0_5_1 = y4 + x_shift5;

  assign y5 = (switch_compare_1_10 == 1'b0 ? y_temp5 :
              y_temp_0_5_1);

  assign y5_p_msb = y5[17];

  assign switch_compare_1_12 = y5_p_msb > 1'b0;

  assign switch_compare_1_13 = y4_p_msb > 1'b0;

  assign y_shift5 = y4 >>> 8'd4;

  assign x_temp5 = x4 + y_shift5;

  assign x_temp_0_5_1 = x4 - y_shift5;

  assign x5 = (switch_compare_1_13 == 1'b0 ? x_temp5 :
              x_temp_0_5_1);

  assign x_shift6 = x5 >>> 8'd5;

  assign y_temp6 = y5 - x_shift6;

  assign y_temp_0_6_1 = y5 + x_shift6;

  assign y6 = (switch_compare_1_12 == 1'b0 ? y_temp6 :
              y_temp_0_6_1);

  assign y6_p_msb = y6[17];

  assign switch_compare_1_14 = y6_p_msb > 1'b0;

  assign switch_compare_1_15 = y5_p_msb > 1'b0;

  assign y_shift6 = y5 >>> 8'd5;

  assign x_temp6 = x5 + y_shift6;

  assign x_temp_0_6_1 = x5 - y_shift6;

  assign x6 = (switch_compare_1_15 == 1'b0 ? x_temp6 :
              x_temp_0_6_1);

  assign x_shift7 = x6 >>> 8'd6;

  assign y_temp7 = y6 - x_shift7;

  assign y_temp_0_7_1 = y6 + x_shift7;

  assign y7 = (switch_compare_1_14 == 1'b0 ? y_temp7 :
              y_temp_0_7_1);

  assign y7_p_msb = y7[17];

  assign switch_compare_1_16 = y7_p_msb > 1'b0;

  assign switch_compare_1_17 = y6_p_msb > 1'b0;

  assign y_shift7 = y6 >>> 8'd6;

  assign x_temp7 = x6 + y_shift7;

  assign x_temp_0_7_1 = x6 - y_shift7;

  assign x7 = (switch_compare_1_17 == 1'b0 ? x_temp7 :
              x_temp_0_7_1);

  assign x_shift8 = x7 >>> 8'd7;

  assign y_temp8 = y7 - x_shift8;

  assign y_temp_0_8_1 = y7 + x_shift8;

  assign y8 = (switch_compare_1_16 == 1'b0 ? y_temp8 :
              y_temp_0_8_1);

  assign y8_p_msb = y8[17];

  assign switch_compare_1_18 = y8_p_msb > 1'b0;

  assign switch_compare_1_19 = y7_p_msb > 1'b0;

  assign y_shift8 = y7 >>> 8'd7;

  assign x_temp8 = x7 + y_shift8;

  assign x_temp_0_8_1 = x7 - y_shift8;

  assign x8 = (switch_compare_1_19 == 1'b0 ? x_temp8 :
              x_temp_0_8_1);

  assign x_shift9 = x8 >>> 8'd8;

  assign y_temp9 = y8 - x_shift9;

  assign y_temp_0_9_1 = y8 + x_shift9;

  assign y9 = (switch_compare_1_18 == 1'b0 ? y_temp9 :
              y_temp_0_9_1);

  assign y9_p_msb = y9[17];

  assign switch_compare_1_20 = y9_p_msb > 1'b0;

  assign switch_compare_1_21 = y8_p_msb > 1'b0;

  assign y_shift9 = y8 >>> 8'd8;

  assign x_temp9 = x8 + y_shift9;

  assign x_temp_0_9_1 = x8 - y_shift9;

  assign x9 = (switch_compare_1_21 == 1'b0 ? x_temp9 :
              x_temp_0_9_1);

  assign x_shift10 = x9 >>> 8'd9;

  assign y_temp10 = y9 - x_shift10;

  assign y_temp_0_10_1 = y9 + x_shift10;

  assign y10 = (switch_compare_1_20 == 1'b0 ? y_temp10 :
              y_temp_0_10_1);

  assign y10_p_msb = y10[17];

  assign switch_compare_1_22 = y10_p_msb > 1'b0;

  assign switch_compare_1_23 = y9_p_msb > 1'b0;

  assign switch_compare_1_24 = y8_p_msb > 1'b0;

  assign switch_compare_1_25 = y7_p_msb > 1'b0;

  assign switch_compare_1_26 = y6_p_msb > 1'b0;

  assign switch_compare_1_27 = y5_p_msb > 1'b0;

  assign switch_compare_1_28 = y4_p_msb > 1'b0;

  assign switch_compare_1_29 = y3_p_msb > 1'b0;

  assign switch_compare_1_30 = y2_p_msb > 1'b0;

  assign switch_compare_1_31 = y1_p_msb > 1'b0;

  assign switch_compare_1_32 = y0_p_msb > 1'b0;

  assign z0 = 18'sb000000000000000000;

  assign lut_value_s1 = 18'sb000001100100100010;

  assign lut_value_temp1 = z0 + lut_value_s1;

  assign y_temp_0_1_2 = z0 - lut_value_s1;

  assign z1 = (switch_compare_1_32 == 1'b0 ? lut_value_temp1 :
              y_temp_0_1_2);

  assign lut_value_s2 = 18'sb000000111011010110;

  assign lut_value_temp2 = z1 + lut_value_s2;

  assign y_temp_0_2_2 = z1 - lut_value_s2;

  assign z2 = (switch_compare_1_31 == 1'b0 ? lut_value_temp2 :
              y_temp_0_2_2);

  assign lut_value_s3 = 18'sb000000011111010111;

  assign lut_value_temp3 = z2 + lut_value_s3;

  assign y_temp_0_3_2 = z2 - lut_value_s3;

  assign z3 = (switch_compare_1_30 == 1'b0 ? lut_value_temp3 :
              y_temp_0_3_2);

  assign lut_value_s4 = 18'sb000000001111111011;

  assign lut_value_temp4 = z3 + lut_value_s4;

  assign y_temp_0_4_2 = z3 - lut_value_s4;

  assign z4 = (switch_compare_1_29 == 1'b0 ? lut_value_temp4 :
              y_temp_0_4_2);

  assign lut_value_s5 = 18'sb000000000111111111;

  assign lut_value_temp5 = z4 + lut_value_s5;

  assign y_temp_0_5_2 = z4 - lut_value_s5;

  assign z5 = (switch_compare_1_28 == 1'b0 ? lut_value_temp5 :
              y_temp_0_5_2);

  assign lut_value_s6 = 18'sb000000000100000000;

  assign lut_value_temp6 = z5 + lut_value_s6;

  assign y_temp_0_6_2 = z5 - lut_value_s6;

  assign z6 = (switch_compare_1_27 == 1'b0 ? lut_value_temp6 :
              y_temp_0_6_2);

  assign lut_value_s7 = 18'sb000000000010000000;

  assign lut_value_temp7 = z6 + lut_value_s7;

  assign y_temp_0_7_2 = z6 - lut_value_s7;

  assign z7 = (switch_compare_1_26 == 1'b0 ? lut_value_temp7 :
              y_temp_0_7_2);

  assign lut_value_s8 = 18'sb000000000001000000;

  assign lut_value_temp8 = z7 + lut_value_s8;

  assign y_temp_0_8_2 = z7 - lut_value_s8;

  assign z8 = (switch_compare_1_25 == 1'b0 ? lut_value_temp8 :
              y_temp_0_8_2);

  assign lut_value_s9 = 18'sb000000000000100000;

  assign lut_value_temp9 = z8 + lut_value_s9;

  assign y_temp_0_9_2 = z8 - lut_value_s9;

  assign z9 = (switch_compare_1_24 == 1'b0 ? lut_value_temp9 :
              y_temp_0_9_2);

  assign lut_value_s10 = 18'sb000000000000010000;

  assign lut_value_temp10 = z9 + lut_value_s10;

  assign y_temp_0_10_2 = z9 - lut_value_s10;

  assign z10 = (switch_compare_1_23 == 1'b0 ? lut_value_temp10 :
              y_temp_0_10_2);

  assign lut_value_s11 = 18'sb000000000000001000;

  assign lut_value_temp11 = z10 + lut_value_s11;

  assign y_temp_0_11 = z10 - lut_value_s11;

  assign z11 = (switch_compare_1_22 == 1'b0 ? lut_value_temp11 :
              y_temp_0_11);

  assign z_out = z11[15:0];

  assign z_temp3_cast = {z_out[15], z_out};
  assign z_temp3_cast_1 =  - (z_temp3_cast);
  assign z_temp3_1 = z_temp3_cast_1[15:0];

  assign z_temp2_1 = onePi_1 - z_out;

  assign z_temp1_1 = z_out - onePi_1;

  always @(onePi_1, x_y_adjust, z_out, z_temp1_1, z_temp2_1, z_temp3_1, zero) begin
    case ( x_y_adjust)
      3'b000 :
        begin
          z_out_adjust = zero;
        end
      3'b001 :
        begin
          z_out_adjust = zero;
        end
      3'b010 :
        begin
          z_out_adjust = onePi_1;
        end
      3'b011 :
        begin
          z_out_adjust = onePi_1;
        end
      3'b100 :
        begin
          z_out_adjust = z_out;
        end
      3'b101 :
        begin
          z_out_adjust = z_temp3_1;
        end
      3'b110 :
        begin
          z_out_adjust = z_temp2_1;
        end
      default :
        begin
          z_out_adjust = z_temp1_1;
        end
    endcase
  end

  assign angle = z_out_adjust;

endmodule  // phi_acc
