// -------------------------------------------------------------
// 
// File Name: C:\Users\Labhesh\OneDrive\Desktop\IIT Madras\Startup\FPGA\Attitude_Controller\Attitude_filter\hdlsrc\Attitude_filter\Sqrt.v
// Created: 2026-07-04 12:22:17
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Sqrt
// Source Path: Attitude_filter/Complementary filter/Sqrt
// Hierarchy Level: 1
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Sqrt
          (din,
           dout);


  input   [15:0] din;  // ufix16_En12
  output  signed [15:0] dout;  // sfix16_En11


  wire [5:0] Root_Square2_temp1;  // ufix6
  wire [31:0] currentRoot_Square_temp_extend_2;  // ufix32
  wire [31:0] BitShift_out_2;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_2_2;  // ufix32_En22
  wire [31:0] relop_cast;  // ufix32_En22
  wire cmp0;  // ufix1
  wire [2:0] root_0_temp0;  // ufix3
  wire [2:0] root_0_temp1;  // ufix3
  wire [2:0] Root_0;  // ufix3
  wire [5:0] Root_Square2_temp0;  // ufix6
  wire [5:0] Root_Square0;  // ufix6
  wire [1:0] constant_01;  // ufix2
  wire [7:0] prevRoot_Square_extend1;  // ufix8
  wire [1:0] constant_01_1;  // ufix2
  wire [4:0] prevRoot_extend1;  // ufix5
  wire [8:0] adder_add_temp;  // ufix9
  wire [8:0] adder_1;  // ufix9
  wire [8:0] adder_2;  // ufix9
  wire [7:0] Root_Square3_temp1;  // ufix8
  wire [31:0] currentRoot_Square_temp_extend_3;  // ufix32
  wire [31:0] BitShift_out_3;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_3_2;  // ufix32_En22
  wire [31:0] relop_cast_1;  // ufix32_En22
  wire cmp1;  // ufix1
  wire [3:0] Root_1;  // ufix4
  wire [7:0] Root_Square3_temp0;  // ufix8
  wire [7:0] Root_Square1;  // ufix8
  wire [1:0] constant_02;  // ufix2
  wire [9:0] prevRoot_Square_extend2;  // ufix10
  wire [1:0] constant_02_1;  // ufix2
  wire [5:0] prevRoot_extend2;  // ufix6
  wire [10:0] adder_add_temp_1;  // ufix11
  wire [10:0] adder_4;  // ufix11
  wire [10:0] adder_5;  // ufix11
  wire [9:0] Root_Square4_temp1;  // ufix10
  wire [31:0] currentRoot_Square_temp_extend_4;  // ufix32
  wire [31:0] BitShift_out_4;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_4_2;  // ufix32_En22
  wire [31:0] relop_cast_2;  // ufix32_En22
  wire cmp2;  // ufix1
  wire [4:0] Root_2;  // ufix5
  wire [9:0] Root_Square4_temp0;  // ufix10
  wire [9:0] Root_Square2;  // ufix10
  wire [1:0] constant_03;  // ufix2
  wire [11:0] prevRoot_Square_extend3;  // ufix12
  wire [1:0] constant_03_1;  // ufix2
  wire [6:0] prevRoot_extend3;  // ufix7
  wire [12:0] adder_add_temp_2;  // ufix13
  wire [12:0] adder_7;  // ufix13
  wire [12:0] adder_8;  // ufix13
  wire [11:0] Root_Square5_temp1;  // ufix12
  wire [31:0] currentRoot_Square_temp_extend_5;  // ufix32
  wire [31:0] BitShift_out_5;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_5_2;  // ufix32_En22
  wire [31:0] relop_cast_3;  // ufix32_En22
  wire cmp3;  // ufix1
  wire [5:0] Root_3;  // ufix6
  wire [11:0] Root_Square5_temp0;  // ufix12
  wire [11:0] Root_Square3;  // ufix12
  wire [1:0] constant_04;  // ufix2
  wire [13:0] prevRoot_Square_extend4;  // ufix14
  wire [1:0] constant_04_1;  // ufix2
  wire [7:0] prevRoot_extend4;  // ufix8
  wire [14:0] adder_add_temp_3;  // ufix15
  wire [14:0] adder_10;  // ufix15
  wire [14:0] adder_11;  // ufix15
  wire [13:0] Root_Square6_temp1;  // ufix14
  wire [31:0] currentRoot_Square_temp_extend_6;  // ufix32
  wire [31:0] BitShift_out_6;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_6_2;  // ufix32_En22
  wire [31:0] relop_cast_4;  // ufix32_En22
  wire cmp4;  // ufix1
  wire [6:0] Root_4;  // ufix7
  wire [13:0] Root_Square6_temp0;  // ufix14
  wire [13:0] Root_Square4;  // ufix14
  wire [1:0] constant_05;  // ufix2
  wire [15:0] prevRoot_Square_extend5;  // ufix16
  wire [1:0] constant_05_1;  // ufix2
  wire [8:0] prevRoot_extend5;  // ufix9
  wire [16:0] adder_add_temp_4;  // ufix17
  wire [16:0] adder_13;  // ufix17
  wire [16:0] adder_14;  // ufix17
  wire [15:0] Root_Square7_temp1;  // ufix16
  wire [31:0] currentRoot_Square_temp_extend_7;  // ufix32
  wire [31:0] BitShift_out_7;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_7_2;  // ufix32_En22
  wire [31:0] relop_cast_5;  // ufix32_En22
  wire cmp5;  // ufix1
  wire [7:0] Root_5;  // ufix8
  wire [15:0] Root_Square7_temp0;  // ufix16
  wire [15:0] Root_Square5;  // ufix16
  wire [1:0] constant_06;  // ufix2
  wire [17:0] prevRoot_Square_extend6;  // ufix18
  wire [1:0] constant_06_1;  // ufix2
  wire [9:0] prevRoot_extend6;  // ufix10
  wire [18:0] adder_add_temp_5;  // ufix19
  wire [18:0] adder_16;  // ufix19
  wire [18:0] adder_17;  // ufix19
  wire [17:0] Root_Square8_temp1;  // ufix18
  wire [31:0] currentRoot_Square_temp_extend_8;  // ufix32
  wire [31:0] BitShift_out_8;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_8_2;  // ufix32_En22
  wire [31:0] relop_cast_6;  // ufix32_En22
  wire cmp6;  // ufix1
  wire [8:0] Root_6;  // ufix9
  wire [17:0] Root_Square8_temp0;  // ufix18
  wire [17:0] Root_Square6;  // ufix18
  wire [1:0] constant_07;  // ufix2
  wire [19:0] prevRoot_Square_extend7;  // ufix20
  wire [1:0] constant_07_1;  // ufix2
  wire [10:0] prevRoot_extend7;  // ufix11
  wire [20:0] adder_add_temp_6;  // ufix21
  wire [20:0] adder_19;  // ufix21
  wire [20:0] adder_20;  // ufix21
  wire [19:0] Root_Square9_temp1;  // ufix20
  wire [31:0] currentRoot_Square_temp_extend_9;  // ufix32
  wire [31:0] BitShift_out_9;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_9_2;  // ufix32_En22
  wire [31:0] relop_cast_7;  // ufix32_En22
  wire cmp7;  // ufix1
  wire [9:0] Root_7;  // ufix10
  wire [19:0] Root_Square9_temp0;  // ufix20
  wire [19:0] Root_Square7;  // ufix20
  wire [1:0] constant_08;  // ufix2
  wire [21:0] prevRoot_Square_extend8;  // ufix22
  wire [1:0] constant_08_1;  // ufix2
  wire [11:0] prevRoot_extend8;  // ufix12
  wire [22:0] adder_add_temp_7;  // ufix23
  wire [22:0] adder_22;  // ufix23
  wire [22:0] adder_23;  // ufix23
  wire [21:0] Root_Square10_temp1;  // ufix22
  wire [31:0] currentRoot_Square_temp_extend_10;  // ufix32
  wire [31:0] BitShift_out_10;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_10_2;  // ufix32_En22
  wire [31:0] relop_cast_8;  // ufix32_En22
  wire cmp8;  // ufix1
  wire [10:0] Root_8;  // ufix11
  wire [21:0] Root_Square10_temp0;  // ufix22
  wire [21:0] Root_Square8;  // ufix22
  wire [1:0] constant_09;  // ufix2
  wire [23:0] prevRoot_Square_extend9;  // ufix24
  wire [1:0] constant_09_1;  // ufix2
  wire [12:0] prevRoot_extend9;  // ufix13
  wire [24:0] adder_add_temp_8;  // ufix25
  wire [24:0] adder_25;  // ufix25
  wire [24:0] adder_26;  // ufix25
  wire [23:0] Root_Square11_temp1;  // ufix24
  wire [31:0] currentRoot_Square_temp_extend_11;  // ufix32
  wire [31:0] BitShift_out_11;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_11_2;  // ufix32_En22
  wire [31:0] relop_cast_9;  // ufix32_En22
  wire cmp9;  // ufix1
  wire [11:0] Root_9;  // ufix12
  wire [23:0] Root_Square11_temp0;  // ufix24
  wire [23:0] Root_Square9;  // ufix24
  wire [1:0] constant_010;  // ufix2
  wire [25:0] prevRoot_Square_extend10;  // ufix26
  wire [1:0] constant_010_1;  // ufix2
  wire [13:0] prevRoot_extend10;  // ufix14
  wire [26:0] adder_add_temp_9;  // ufix27
  wire [26:0] adder_28;  // ufix27
  wire [26:0] adder_29;  // ufix27
  wire [25:0] Root_Square12_temp1;  // ufix26
  wire [31:0] currentRoot_Square_temp_extend_12;  // ufix32
  wire [31:0] BitShift_out_12;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_12_2;  // ufix32_En22
  wire [31:0] relop_cast_10;  // ufix32_En22
  wire cmp10;  // ufix1
  wire [12:0] Root_10;  // ufix13
  wire [25:0] Root_Square12_temp0;  // ufix26
  wire [25:0] Root_Square10;  // ufix26
  wire [1:0] constant_011;  // ufix2
  wire [27:0] prevRoot_Square_extend11;  // ufix28
  wire [1:0] constant_011_1;  // ufix2
  wire [14:0] prevRoot_extend11;  // ufix15
  wire [28:0] adder_add_temp_10;  // ufix29
  wire [28:0] adder_31;  // ufix29
  wire [28:0] adder_32;  // ufix29
  wire [27:0] Root_Square13_temp1;  // ufix28
  wire [31:0] currentRoot_Square_temp_extend_13;  // ufix32
  wire [31:0] BitShift_out_13;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_13_2;  // ufix32_En22
  wire [31:0] relop_cast_11;  // ufix32_En22
  wire cmp11;  // ufix1
  wire [13:0] Root_11;  // ufix14
  wire [27:0] Root_Square13_temp0;  // ufix28
  wire [27:0] Root_Square11;  // ufix28
  wire [1:0] constant_012;  // ufix2
  wire [29:0] prevRoot_Square_extend12;  // ufix30
  wire [1:0] constant_012_1;  // ufix2
  wire [15:0] prevRoot_extend12;  // ufix16
  wire [30:0] adder_add_temp_11;  // ufix31
  wire [30:0] adder_34;  // ufix31
  wire [30:0] adder_35;  // ufix31
  wire [29:0] Root_Square14_temp1;  // ufix30
  wire [31:0] currentRoot_Square_temp_extend_14;  // ufix32
  wire [31:0] currentRoot_Square_temp_extend_14_2;  // ufix32_En22
  wire [31:0] relop_cast_12;  // ufix32_En22
  wire cmp12;  // ufix1
  wire [14:0] Root_12;  // ufix15
  wire [15:0] maxy;  // ufix16
  wire [29:0] Root_Square14_temp0;  // ufix30
  wire [29:0] Root_Square12;  // ufix30
  wire constant1_sig;  // ufix1
  wire [31:0] adder_37;  // ufix32
  wire [31:0] adder_38;  // ufix32
  wire [31:0] squaresum;  // ufix32
  wire [31:0] rootdtc;  // ufix32
  wire [31:0] shift2;  // ufix32
  wire [32:0] adder_add_temp_12;  // ufix33
  wire [32:0] adder_40;  // ufix33
  wire [32:0] adder_41;  // ufix33
  wire [31:0] yypluslsb;  // ufix32
  wire [31:0] yypluslsb_p_temp;  // ufix32_En22
  wire [32:0] subtractor_sub_cast;  // ufix33_En22
  wire [32:0] subtractor_sub_cast_1;  // ufix33_En22
  wire [32:0] subtractor_sub_temp;  // ufix33_En22
  wire [31:0] sub1;  // ufix32_En22
  wire [31:0] yytemp_p_temp;  // ufix32
  wire [31:0] yytemp_p_temp_1;  // ufix32_En22
  wire [15:0] relop_14;  // ufix16
  wire cmpmax;  // ufix1
  wire [32:0] subtractor_sub_cast_2;  // ufix33_En22
  wire [32:0] subtractor_sub_cast_3;  // ufix33_En22
  wire [32:0] subtractor_sub_temp_1;  // ufix33_En22
  wire [31:0] sub2;  // ufix32_En22
  wire outsel;  // ufix1
  wire switch_control;  // ufix1
  wire [15:0] Root_12_dtc;  // ufix16
  wire [15:0] lsby;  // ufix16
  wire [16:0] adder_add_temp_13;  // ufix17
  wire [16:0] adder_43;  // ufix17
  wire [16:0] adder_44;  // ufix17
  wire [15:0] rootpluslsb;  // ufix16
  wire [15:0] rootout;  // ufix16
  wire signed [15:0] outdata_1;  // sfix16_En11

  // Sqrt Implementation using Shift


  assign Root_Square2_temp1 = 6'b000001;

  assign currentRoot_Square_temp_extend_2 = {26'b0, Root_Square2_temp1};

  assign BitShift_out_2 = currentRoot_Square_temp_extend_2 <<< 8'd24;

  assign currentRoot_Square_temp_extend_2_2 = BitShift_out_2;

  assign relop_cast = {6'b0, {din, 10'b0000000000}};
  assign cmp0 = currentRoot_Square_temp_extend_2_2 <= relop_cast;

  assign root_0_temp0 = 3'b000;

  assign root_0_temp1 = 3'b001;

  assign Root_0 = (cmp0 == 1'b0 ? root_0_temp0 :
              root_0_temp1);

  assign Root_Square2_temp0 = 6'b000000;

  assign Root_Square0 = (cmp0 == 1'b0 ? Root_Square2_temp0 :
              Root_Square2_temp1);

  assign constant_01 = 2'b01;

  assign prevRoot_Square_extend1 = {Root_Square0, constant_01};

  assign constant_01_1 = 2'b00;

  assign prevRoot_extend1 = {Root_0, constant_01_1};

  assign adder_1 = {1'b0, prevRoot_Square_extend1};
  assign adder_2 = {4'b0, prevRoot_extend1};
  assign adder_add_temp = adder_1 + adder_2;
  assign Root_Square3_temp1 = (adder_add_temp[8] != 1'b0 ? 8'b11111111 :
              adder_add_temp[7:0]);

  assign currentRoot_Square_temp_extend_3 = {24'b0, Root_Square3_temp1};

  assign BitShift_out_3 = currentRoot_Square_temp_extend_3 <<< 8'd22;

  assign currentRoot_Square_temp_extend_3_2 = BitShift_out_3;

  assign relop_cast_1 = {6'b0, {din, 10'b0000000000}};
  assign cmp1 = currentRoot_Square_temp_extend_3_2 <= relop_cast_1;

  assign Root_1 = {Root_0, cmp1};

  assign Root_Square3_temp0 = {Root_Square0, constant_01_1};

  assign Root_Square1 = (cmp1 == 1'b0 ? Root_Square3_temp0 :
              Root_Square3_temp1);

  assign constant_02 = 2'b01;

  assign prevRoot_Square_extend2 = {Root_Square1, constant_02};

  assign constant_02_1 = 2'b00;

  assign prevRoot_extend2 = {Root_1, constant_02_1};

  assign adder_4 = {1'b0, prevRoot_Square_extend2};
  assign adder_5 = {5'b0, prevRoot_extend2};
  assign adder_add_temp_1 = adder_4 + adder_5;
  assign Root_Square4_temp1 = (adder_add_temp_1[10] != 1'b0 ? 10'b1111111111 :
              adder_add_temp_1[9:0]);

  assign currentRoot_Square_temp_extend_4 = {22'b0, Root_Square4_temp1};

  assign BitShift_out_4 = currentRoot_Square_temp_extend_4 <<< 8'd20;

  assign currentRoot_Square_temp_extend_4_2 = BitShift_out_4;

  assign relop_cast_2 = {6'b0, {din, 10'b0000000000}};
  assign cmp2 = currentRoot_Square_temp_extend_4_2 <= relop_cast_2;

  assign Root_2 = {Root_1, cmp2};

  assign Root_Square4_temp0 = {Root_Square1, constant_02_1};

  assign Root_Square2 = (cmp2 == 1'b0 ? Root_Square4_temp0 :
              Root_Square4_temp1);

  assign constant_03 = 2'b01;

  assign prevRoot_Square_extend3 = {Root_Square2, constant_03};

  assign constant_03_1 = 2'b00;

  assign prevRoot_extend3 = {Root_2, constant_03_1};

  assign adder_7 = {1'b0, prevRoot_Square_extend3};
  assign adder_8 = {6'b0, prevRoot_extend3};
  assign adder_add_temp_2 = adder_7 + adder_8;
  assign Root_Square5_temp1 = (adder_add_temp_2[12] != 1'b0 ? 12'b111111111111 :
              adder_add_temp_2[11:0]);

  assign currentRoot_Square_temp_extend_5 = {20'b0, Root_Square5_temp1};

  assign BitShift_out_5 = currentRoot_Square_temp_extend_5 <<< 8'd18;

  assign currentRoot_Square_temp_extend_5_2 = BitShift_out_5;

  assign relop_cast_3 = {6'b0, {din, 10'b0000000000}};
  assign cmp3 = currentRoot_Square_temp_extend_5_2 <= relop_cast_3;

  assign Root_3 = {Root_2, cmp3};

  assign Root_Square5_temp0 = {Root_Square2, constant_03_1};

  assign Root_Square3 = (cmp3 == 1'b0 ? Root_Square5_temp0 :
              Root_Square5_temp1);

  assign constant_04 = 2'b01;

  assign prevRoot_Square_extend4 = {Root_Square3, constant_04};

  assign constant_04_1 = 2'b00;

  assign prevRoot_extend4 = {Root_3, constant_04_1};

  assign adder_10 = {1'b0, prevRoot_Square_extend4};
  assign adder_11 = {7'b0, prevRoot_extend4};
  assign adder_add_temp_3 = adder_10 + adder_11;
  assign Root_Square6_temp1 = (adder_add_temp_3[14] != 1'b0 ? 14'b11111111111111 :
              adder_add_temp_3[13:0]);

  assign currentRoot_Square_temp_extend_6 = {18'b0, Root_Square6_temp1};

  assign BitShift_out_6 = currentRoot_Square_temp_extend_6 <<< 8'd16;

  assign currentRoot_Square_temp_extend_6_2 = BitShift_out_6;

  assign relop_cast_4 = {6'b0, {din, 10'b0000000000}};
  assign cmp4 = currentRoot_Square_temp_extend_6_2 <= relop_cast_4;

  assign Root_4 = {Root_3, cmp4};

  assign Root_Square6_temp0 = {Root_Square3, constant_04_1};

  assign Root_Square4 = (cmp4 == 1'b0 ? Root_Square6_temp0 :
              Root_Square6_temp1);

  assign constant_05 = 2'b01;

  assign prevRoot_Square_extend5 = {Root_Square4, constant_05};

  assign constant_05_1 = 2'b00;

  assign prevRoot_extend5 = {Root_4, constant_05_1};

  assign adder_13 = {1'b0, prevRoot_Square_extend5};
  assign adder_14 = {8'b0, prevRoot_extend5};
  assign adder_add_temp_4 = adder_13 + adder_14;
  assign Root_Square7_temp1 = (adder_add_temp_4[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_4[15:0]);

  assign currentRoot_Square_temp_extend_7 = {16'b0, Root_Square7_temp1};

  assign BitShift_out_7 = currentRoot_Square_temp_extend_7 <<< 8'd14;

  assign currentRoot_Square_temp_extend_7_2 = BitShift_out_7;

  assign relop_cast_5 = {6'b0, {din, 10'b0000000000}};
  assign cmp5 = currentRoot_Square_temp_extend_7_2 <= relop_cast_5;

  assign Root_5 = {Root_4, cmp5};

  assign Root_Square7_temp0 = {Root_Square4, constant_05_1};

  assign Root_Square5 = (cmp5 == 1'b0 ? Root_Square7_temp0 :
              Root_Square7_temp1);

  assign constant_06 = 2'b01;

  assign prevRoot_Square_extend6 = {Root_Square5, constant_06};

  assign constant_06_1 = 2'b00;

  assign prevRoot_extend6 = {Root_5, constant_06_1};

  assign adder_16 = {1'b0, prevRoot_Square_extend6};
  assign adder_17 = {9'b0, prevRoot_extend6};
  assign adder_add_temp_5 = adder_16 + adder_17;
  assign Root_Square8_temp1 = (adder_add_temp_5[18] != 1'b0 ? 18'b111111111111111111 :
              adder_add_temp_5[17:0]);

  assign currentRoot_Square_temp_extend_8 = {14'b0, Root_Square8_temp1};

  assign BitShift_out_8 = currentRoot_Square_temp_extend_8 <<< 8'd12;

  assign currentRoot_Square_temp_extend_8_2 = BitShift_out_8;

  assign relop_cast_6 = {6'b0, {din, 10'b0000000000}};
  assign cmp6 = currentRoot_Square_temp_extend_8_2 <= relop_cast_6;

  assign Root_6 = {Root_5, cmp6};

  assign Root_Square8_temp0 = {Root_Square5, constant_06_1};

  assign Root_Square6 = (cmp6 == 1'b0 ? Root_Square8_temp0 :
              Root_Square8_temp1);

  assign constant_07 = 2'b01;

  assign prevRoot_Square_extend7 = {Root_Square6, constant_07};

  assign constant_07_1 = 2'b00;

  assign prevRoot_extend7 = {Root_6, constant_07_1};

  assign adder_19 = {1'b0, prevRoot_Square_extend7};
  assign adder_20 = {10'b0, prevRoot_extend7};
  assign adder_add_temp_6 = adder_19 + adder_20;
  assign Root_Square9_temp1 = (adder_add_temp_6[20] != 1'b0 ? 20'b11111111111111111111 :
              adder_add_temp_6[19:0]);

  assign currentRoot_Square_temp_extend_9 = {12'b0, Root_Square9_temp1};

  assign BitShift_out_9 = currentRoot_Square_temp_extend_9 <<< 8'd10;

  assign currentRoot_Square_temp_extend_9_2 = BitShift_out_9;

  assign relop_cast_7 = {6'b0, {din, 10'b0000000000}};
  assign cmp7 = currentRoot_Square_temp_extend_9_2 <= relop_cast_7;

  assign Root_7 = {Root_6, cmp7};

  assign Root_Square9_temp0 = {Root_Square6, constant_07_1};

  assign Root_Square7 = (cmp7 == 1'b0 ? Root_Square9_temp0 :
              Root_Square9_temp1);

  assign constant_08 = 2'b01;

  assign prevRoot_Square_extend8 = {Root_Square7, constant_08};

  assign constant_08_1 = 2'b00;

  assign prevRoot_extend8 = {Root_7, constant_08_1};

  assign adder_22 = {1'b0, prevRoot_Square_extend8};
  assign adder_23 = {11'b0, prevRoot_extend8};
  assign adder_add_temp_7 = adder_22 + adder_23;
  assign Root_Square10_temp1 = (adder_add_temp_7[22] != 1'b0 ? 22'b1111111111111111111111 :
              adder_add_temp_7[21:0]);

  assign currentRoot_Square_temp_extend_10 = {10'b0, Root_Square10_temp1};

  assign BitShift_out_10 = currentRoot_Square_temp_extend_10 <<< 8'd8;

  assign currentRoot_Square_temp_extend_10_2 = BitShift_out_10;

  assign relop_cast_8 = {6'b0, {din, 10'b0000000000}};
  assign cmp8 = currentRoot_Square_temp_extend_10_2 <= relop_cast_8;

  assign Root_8 = {Root_7, cmp8};

  assign Root_Square10_temp0 = {Root_Square7, constant_08_1};

  assign Root_Square8 = (cmp8 == 1'b0 ? Root_Square10_temp0 :
              Root_Square10_temp1);

  assign constant_09 = 2'b01;

  assign prevRoot_Square_extend9 = {Root_Square8, constant_09};

  assign constant_09_1 = 2'b00;

  assign prevRoot_extend9 = {Root_8, constant_09_1};

  assign adder_25 = {1'b0, prevRoot_Square_extend9};
  assign adder_26 = {12'b0, prevRoot_extend9};
  assign adder_add_temp_8 = adder_25 + adder_26;
  assign Root_Square11_temp1 = (adder_add_temp_8[24] != 1'b0 ? 24'b111111111111111111111111 :
              adder_add_temp_8[23:0]);

  assign currentRoot_Square_temp_extend_11 = {8'b0, Root_Square11_temp1};

  assign BitShift_out_11 = currentRoot_Square_temp_extend_11 <<< 8'd6;

  assign currentRoot_Square_temp_extend_11_2 = BitShift_out_11;

  assign relop_cast_9 = {6'b0, {din, 10'b0000000000}};
  assign cmp9 = currentRoot_Square_temp_extend_11_2 <= relop_cast_9;

  assign Root_9 = {Root_8, cmp9};

  assign Root_Square11_temp0 = {Root_Square8, constant_09_1};

  assign Root_Square9 = (cmp9 == 1'b0 ? Root_Square11_temp0 :
              Root_Square11_temp1);

  assign constant_010 = 2'b01;

  assign prevRoot_Square_extend10 = {Root_Square9, constant_010};

  assign constant_010_1 = 2'b00;

  assign prevRoot_extend10 = {Root_9, constant_010_1};

  assign adder_28 = {1'b0, prevRoot_Square_extend10};
  assign adder_29 = {13'b0, prevRoot_extend10};
  assign adder_add_temp_9 = adder_28 + adder_29;
  assign Root_Square12_temp1 = (adder_add_temp_9[26] != 1'b0 ? 26'b11111111111111111111111111 :
              adder_add_temp_9[25:0]);

  assign currentRoot_Square_temp_extend_12 = {6'b0, Root_Square12_temp1};

  assign BitShift_out_12 = currentRoot_Square_temp_extend_12 <<< 8'd4;

  assign currentRoot_Square_temp_extend_12_2 = BitShift_out_12;

  assign relop_cast_10 = {6'b0, {din, 10'b0000000000}};
  assign cmp10 = currentRoot_Square_temp_extend_12_2 <= relop_cast_10;

  assign Root_10 = {Root_9, cmp10};

  assign Root_Square12_temp0 = {Root_Square9, constant_010_1};

  assign Root_Square10 = (cmp10 == 1'b0 ? Root_Square12_temp0 :
              Root_Square12_temp1);

  assign constant_011 = 2'b01;

  assign prevRoot_Square_extend11 = {Root_Square10, constant_011};

  assign constant_011_1 = 2'b00;

  assign prevRoot_extend11 = {Root_10, constant_011_1};

  assign adder_31 = {1'b0, prevRoot_Square_extend11};
  assign adder_32 = {14'b0, prevRoot_extend11};
  assign adder_add_temp_10 = adder_31 + adder_32;
  assign Root_Square13_temp1 = (adder_add_temp_10[28] != 1'b0 ? 28'b1111111111111111111111111111 :
              adder_add_temp_10[27:0]);

  assign currentRoot_Square_temp_extend_13 = {4'b0, Root_Square13_temp1};

  assign BitShift_out_13 = currentRoot_Square_temp_extend_13 <<< 8'd2;

  assign currentRoot_Square_temp_extend_13_2 = BitShift_out_13;

  assign relop_cast_11 = {6'b0, {din, 10'b0000000000}};
  assign cmp11 = currentRoot_Square_temp_extend_13_2 <= relop_cast_11;

  assign Root_11 = {Root_10, cmp11};

  assign Root_Square13_temp0 = {Root_Square10, constant_011_1};

  assign Root_Square11 = (cmp11 == 1'b0 ? Root_Square13_temp0 :
              Root_Square13_temp1);

  assign constant_012 = 2'b01;

  assign prevRoot_Square_extend12 = {Root_Square11, constant_012};

  assign constant_012_1 = 2'b00;

  assign prevRoot_extend12 = {Root_11, constant_012_1};

  assign adder_34 = {1'b0, prevRoot_Square_extend12};
  assign adder_35 = {15'b0, prevRoot_extend12};
  assign adder_add_temp_11 = adder_34 + adder_35;
  assign Root_Square14_temp1 = (adder_add_temp_11[30] != 1'b0 ? 30'b111111111111111111111111111111 :
              adder_add_temp_11[29:0]);

  assign currentRoot_Square_temp_extend_14 = {2'b0, Root_Square14_temp1};

  assign currentRoot_Square_temp_extend_14_2 = currentRoot_Square_temp_extend_14;

  assign relop_cast_12 = {6'b0, {din, 10'b0000000000}};
  assign cmp12 = currentRoot_Square_temp_extend_14_2 <= relop_cast_12;

  assign Root_12 = {Root_11, cmp12};

  assign maxy = 16'b1111111111111111;

  assign Root_Square14_temp0 = {Root_Square11, constant_012_1};

  assign Root_Square12 = (cmp12 == 1'b0 ? Root_Square14_temp0 :
              Root_Square14_temp1);

  assign constant1_sig = 1'b1;

  assign adder_37 = {2'b0, Root_Square12};
  assign adder_38 = {31'b0, constant1_sig};
  assign squaresum = adder_37 + adder_38;

  assign rootdtc = {17'b0, Root_12};

  assign shift2 = rootdtc <<< 8'd1;

  assign adder_40 = {1'b0, squaresum};
  assign adder_41 = {1'b0, shift2};
  assign adder_add_temp_12 = adder_40 + adder_41;
  assign yypluslsb = (adder_add_temp_12[32] != 1'b0 ? 32'b11111111111111111111111111111111 :
              adder_add_temp_12[31:0]);

  assign yypluslsb_p_temp = yypluslsb;

  assign subtractor_sub_cast = {1'b0, yypluslsb_p_temp};
  assign subtractor_sub_cast_1 = {7'b0, {din, 10'b0000000000}};
  assign subtractor_sub_temp = subtractor_sub_cast - subtractor_sub_cast_1;
  assign sub1 = (subtractor_sub_temp[32] != 1'b0 ? 32'b11111111111111111111111111111111 :
              subtractor_sub_temp[31:0]);

  assign yytemp_p_temp = {2'b0, Root_Square12};

  assign yytemp_p_temp_1 = yytemp_p_temp;

  // Add a LSB when roundmode is Nearest
  assign relop_14 = {1'b0, Root_12};
  assign cmpmax = relop_14 < maxy;

  assign subtractor_sub_cast_2 = {7'b0, {din, 10'b0000000000}};
  assign subtractor_sub_cast_3 = {1'b0, yytemp_p_temp_1};
  assign subtractor_sub_temp_1 = subtractor_sub_cast_2 - subtractor_sub_cast_3;
  assign sub2 = (subtractor_sub_temp_1[32] != 1'b0 ? 32'b11111111111111111111111111111111 :
              subtractor_sub_temp_1[31:0]);

  assign outsel = sub1 < sub2;

  assign switch_control = cmpmax & outsel;

  assign Root_12_dtc = {1'b0, Root_12};

  assign lsby = 16'b0000000000000001;

  assign adder_43 = {1'b0, lsby};
  assign adder_44 = {2'b0, Root_12};
  assign adder_add_temp_13 = adder_43 + adder_44;
  assign rootpluslsb = (adder_add_temp_13[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_13[15:0]);

  assign rootout = (switch_control == 1'b0 ? Root_12_dtc :
              rootpluslsb);

  assign outdata_1 = (rootout[15] != 1'b0 ? 16'sb0111111111111111 :
              rootout);

  assign dout = outdata_1;

endmodule  // Sqrt
