// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\Controller\Attitude_Roll_Controller_2.v
// Created: 2026-05-28 12:01:26
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.004
// Target subsystem base rate: 0.004
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.004
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// U2                            ce_out        0.004
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Attitude_Roll_Controller_2
// Source Path: Controller/Attitude Roll Controller 2
// Hierarchy Level: 0
// Model version: 4.76
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Attitude_Roll_Controller_2
          (clk,
           reset,
           clk_enable,
           phi_raw_req,
           phi_meas,
           p_meas,
           K_ang,
           Kp_rate,
           Ki_rate,
           Kd_rate,
           ready,
           ce_out,
           U2);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [23:0] phi_raw_req;  // sfix24_En16
  input   signed [23:0] phi_meas;  // sfix24_En16
  input   signed [23:0] p_meas;  // sfix24_En16
  input   signed [23:0] K_ang; //sfix24En18
  input   signed [31:0] Kp_rate; //sfix32En20
  input   signed [23:0] Ki_rate; //sfix24En18
  input   signed [23:0] Kd_rate; //sfix24En18
  input   ready; // high only after zynq PS tells to PL that IMU calibration is done , you can start now
  output  ce_out;
  output  signed [23:0] U2;  // sfix24_En16


  wire enb;
  wire stateControl_1;
  reg  [2:0] delayMatch6_reg;  // ufix1 [3]
  wire stateControl_2;
  wire signed [23:0] Constant2_out1;  // sfix24_En18
  wire signed [23:0] kconst;  // sfix24_En14
  reg signed [23:0] kconst_1;  // sfix24_En14
  wire signed [23:0] kconst_2;  // sfix24_En18
  reg signed [23:0] HwModeRegister8_reg [0:1];  // sfix24 [2]
  wire signed [23:0] HwModeRegister8_reg_next [0:1];  // sfix24_En18 [2]
  wire signed [23:0] kconst_3;  // sfix24_En18
  reg signed [23:0] p_ff_x_reg;  // sfix24_En16
  wire signed [47:0] alpha2_zeta_wn_out1;  // sfix48_En34
  reg signed [47:0] alpha2_zeta_wn_out1_1;  // sfix48_En34
  wire signed [23:0] Unit_Delay3_out1;  // sfix24_En16
  wire signed [23:0] p_ff_x_reg_1;  // sfix24_En16
  wire signed [23:0] phi_cmd_indtc;  // sfix24
  wire signed [39:0] gain1_mul_temp;  // sfix40_En22
  wire signed [38:0] phi_cmd_u_gain;  // sfix39_En22
  wire signed [23:0] phi_cmd_u_gain_1;  // sfix24
  wire signed [23:0] phi_cmd_u_dtc;  // sfix24_En16
  reg signed [23:0] theta_cmd;  // sfix24_En16
  wire signed [24:0] adder1_add_cast;  // sfix25_En16
  wire signed [24:0] adder1_add_cast_1;  // sfix25_En16
  wire signed [24:0] adder1_add_temp;  // sfix25_En16
  wire signed [23:0] theta_cmd_1;  // sfix24_En16
  wire signed [24:0] phi_raw_phi_cmd_sub_cast;  // sfix25_En16
  wire signed [24:0] phi_raw_phi_cmd_sub_cast_1;  // sfix25_En16
  wire signed [24:0] phi_raw_phi_cmd_sub_temp;  // sfix25_En16
  wire signed [23:0] phi_raw_phi_cmd_out1;  // sfix24_En16
  reg signed [23:0] phi_raw_phi_cmd_out1_1;  // sfix24_En16
  wire signed [47:0] alpha_wn_2_phi_raw_phi_cmd_out1;  // sfix48_En30
  reg signed [47:0] alpha_wn_2_phi_raw_phi_cmd_out1_1;  // sfix48_En30
  wire signed [23:0] alpha_wn_2_phi_raw_phi_cmd_out1_2;  // sfix24_En16
  wire signed [24:0] Sum1_sub_cast;  // sfix25_En16
  wire signed [24:0] Sum1_sub_cast_1;  // sfix25_En16
  wire signed [24:0] Sum1_sub_temp;  // sfix25_En16
  wire signed [23:0] Sum1_out1;  // sfix24_En16
  wire signed [23:0] p_ff_indtc;  // sfix24
  wire signed [39:0] gain_mul_temp;  // sfix40_En22
  wire signed [38:0] p_ff_u_gain;  // sfix39_En22
  wire signed [23:0] p_ff_u_gain_1;  // sfix24
  wire signed [23:0] p_ff_u_dtc;  // sfix24_En16
  wire signed [24:0] adder_add_cast;  // sfix25_En16
  wire signed [24:0] adder_add_cast_1;  // sfix25_En16
  wire signed [24:0] adder_add_temp;  // sfix25_En16
  wire signed [23:0] kconst_4;  // sfix24_En18
  reg signed [23:0] kconst_5;  // sfix24_En18
  wire signed [23:0] theta_cmd_2;  // sfix24_En16
  wire signed [24:0] phi_error_sub_cast;  // sfix25_En16
  wire signed [24:0] phi_error_sub_cast_1;  // sfix25_En16
  wire signed [24:0] phi_error_sub_temp;  // sfix25_En16
  wire signed [23:0] phi_error_out1;  // sfix24_En16
  reg signed [23:0] phi_error_out1_1;  // sfix24_En16
  wire signed [47:0] Gain_out1;  // sfix48_En34
  reg signed [47:0] Gain_out1_1;  // sfix48_En34
  wire signed [23:0] Gain_out1_2;  // sfix24_En16
  wire signed [24:0] p_ref_add_cast;  // sfix25_En16
  wire signed [24:0] p_ref_add_cast_1;  // sfix25_En16
  wire signed [24:0] p_ref_add_temp;  // sfix25_En16
  wire signed [23:0] qref_before_delay;  // sfix24_En16
  wire signed [23:0] qref_after_delay;  // sfix24_En16
  reg signed [23:0] p_meas_1;  // sfix24_En16
  wire signed [24:0] p_error_sub_cast;  // sfix25_En16
  wire signed [24:0] p_error_sub_cast_1;  // sfix25_En16
  wire signed [24:0] p_error_sub_temp;  // sfix25_En16
  wire signed [23:0] p_error_out1;  // sfix24_En16
  wire signed [23:0] Constant1_out1;  // sfix24_En18
  wire signed [25:0] Relational_Operator3_cast;  // sfix26_En18
  wire signed [25:0] Relational_Operator3_cast_1;  // sfix26_En18
  wire Relational_Operator3_out1;
  wire signed [23:0] Constant_out1;  // sfix24_En18
  wire signed [25:0] Relational_Operator1_cast;  // sfix26_En18
  wire signed [25:0] Relational_Operator1_cast_1;  // sfix26_En18
  wire Relational_Operator1_out1;
  wire signed [31:0] kconst_6;  // sfix32_En20
  reg signed [31:0] kconst_7;  // sfix32_En20
  reg signed [23:0] p_error_out1_1;  // sfix24_En16
  wire signed [55:0] Inner_I_out1;  // sfix56_En36
  reg  [1:0] delayMatch5_reg;  // ufix1 [2]
  wire Relational_Operator3_out1_1;
  reg  [1:0] delayMatch4_reg;  // ufix1 [2]
  wire Relational_Operator1_out1_1;
  reg signed [55:0] Inner_I_out1_1;  // sfix56_En36
  wire signed [23:0] Inner_I_out1_2;  // sfix24_En16
  wire signed [23:0] Constant1_out1_dtc;  // sfix24_En16
  wire signed [23:0] kconst_8;  // sfix24_En18
  reg signed [23:0] kconst_9;  // sfix24_En18
  wire signed [47:0] Inner_P_out1;  // sfix48_En34
  reg signed [47:0] Inner_P_out1_1;  // sfix48_En34
  wire signed [23:0] Inner_P_out1_2;  // sfix24_En16
  reg signed [23:0] Inner_P_out1_3;  // sfix24_En16
  wire signed [23:0] kconst_10;  // sfix24_En18
  reg signed [23:0] kconst_11;  // sfix24_En18
  wire signed [24:0] Sum_sub_cast;  // sfix25_En16
  wire signed [24:0] Sum_sub_cast_1;  // sfix25_En16
  wire signed [24:0] Sum_sub_temp;  // sfix25_En16
  wire signed [23:0] Sum_out1;  // sfix24_En16
  reg signed [23:0] Sum_out1_1;  // sfix24_En16
  wire signed [47:0] Inner_D_out1;  // sfix48_En34
  reg signed [47:0] Inner_D_out1_1;  // sfix48_En34
  wire signed [23:0] Inner_D_out1_2;  // sfix24_En16
  reg signed [23:0] Inner_D_out1_3;  // sfix24_En16
  wire signed [23:0] U2_before_sat;  // sfix24_En16
  wire signed [25:0] Relational_Operator_cast;  // sfix26_En18
  wire signed [25:0] Relational_Operator_cast_1;  // sfix26_En18
  wire Relational_Operator_out1;
  wire Logical_Operator_out1;
  wire signed [25:0] Relational_Operator2_cast;  // sfix26_En18
  wire signed [25:0] Relational_Operator2_cast_1;  // sfix26_En18
  wire Relational_Operator2_out1;
  wire Logical_Operator1_out1;
  wire Logical_Operator2_out1;
  wire switch_compare_1;
  wire signed [23:0] Switch_out1;  // sfix24_En16
  wire signed [23:0] Discrete_Time_Integrator_indtc;  // sfix24
  wire signed [39:0] gain2_mul_temp;  // sfix40_En22
  wire signed [38:0] Discrete_Time_Integrator_u_gain;  // sfix39_En22
  wire signed [23:0] Discrete_Time_Integrator_u_gain_1;  // sfix24
  wire signed [23:0] Discrete_Time_Integrator_u_dtc;  // sfix24_En16
  reg signed [23:0] Discrete_Time_Integrator_x_reg;  // sfix24_En16
  wire signed [24:0] adder2_add_cast;  // sfix25_En16
  wire signed [24:0] adder2_add_cast_1;  // sfix25_En16
  wire signed [24:0] adder2_add_temp;  // sfix25_En16
  wire signed [23:0] Discrete_Time_Integrator_u_add;  // sfix24_En16
  wire signed [23:0] Discrete_Time_Integrator_u_sat;  // sfix24_En16
  wire signed [23:0] Discrete_Time_Integrator_u_sat_1;  // sfix24_En16
  wire signed [24:0] Sum2_stage2_sub_cast;  // sfix25_En16
  wire signed [24:0] Sum2_stage2_sub_cast_1;  // sfix25_En16
  wire signed [24:0] Sum2_stage2_sub_temp;  // sfix25_En16
  wire signed [23:0] Sum2_stage2_cast;  // sfix24_En16
  wire signed [24:0] Sum2_op_stage1;  // sfix25_En16
  wire signed [23:0] Sum2_stage3_sub_cast;  // sfix24_En16
  wire signed [24:0] Sum2_stage3_sub_cast_1;  // sfix25_En16
  wire signed [24:0] Sum2_stage3_sub_cast_2;  // sfix25_En16
  wire signed [24:0] Sum2_stage3_sub_temp;  // sfix25_En16
  wire signed [23:0] U2_before_sat_1;  // sfix24_En16
  wire signed [23:0] Saturation_out1;  // sfix24_En16
  reg signed [31:0] HwModeRegister8_t_0_0;  // int32
  reg signed [31:0] HwModeRegister8_t_1;  // int32


  assign stateControl_1 = 1'b1;

  assign enb = clk_enable&ready;

  always @(posedge clk or posedge reset)
    begin : delayMatch6_process
      if (reset == 1'b1) begin
        delayMatch6_reg <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch6_reg[0] <= stateControl_1;
          delayMatch6_reg[32'sd2:32'sd1] <= delayMatch6_reg[32'sd1:32'sd0];
        end
      end
    end

  assign stateControl_2 = delayMatch6_reg[2];

  assign Constant2_out1 = 24'sb111110110101101011100110;

  assign kconst = 24'sb001010100100000000000000;

  always @(posedge clk or posedge reset)
    begin : HwModeRegister10_process
      if (reset == 1'b1) begin
        kconst_1 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          kconst_1 <= kconst;
        end
      end
    end

  assign kconst_2 = 24'sb010100110011001100110011;

  always @(posedge clk or posedge reset)
    begin : HwModeRegister8_process
      if (reset == 1'b1) begin
        for(HwModeRegister8_t_1 = 32'sd0; HwModeRegister8_t_1 <= 32'sd1; HwModeRegister8_t_1 = HwModeRegister8_t_1 + 32'sd1) begin
          HwModeRegister8_reg[HwModeRegister8_t_1] <= 24'sb000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(HwModeRegister8_t_0_0 = 32'sd0; HwModeRegister8_t_0_0 <= 32'sd1; HwModeRegister8_t_0_0 = HwModeRegister8_t_0_0 + 32'sd1) begin
            HwModeRegister8_reg[HwModeRegister8_t_0_0] <= HwModeRegister8_reg_next[HwModeRegister8_t_0_0];
          end
        end
      end
    end

  assign kconst_3 = HwModeRegister8_reg[1];
  assign HwModeRegister8_reg_next[0] = kconst_2;
  assign HwModeRegister8_reg_next[1] = HwModeRegister8_reg[0];

  assign alpha2_zeta_wn_out1 = kconst_3 * p_ff_x_reg;

  always @(posedge clk or posedge reset)
    begin : PipelineRegister4_process
      if (reset == 1'b1) begin
        alpha2_zeta_wn_out1_1 <= 48'sh000000000000;
      end
      else begin
        if (enb) begin
          alpha2_zeta_wn_out1_1 <= alpha2_zeta_wn_out1;
        end
      end
    end

  assign Unit_Delay3_out1 = (((alpha2_zeta_wn_out1_1[47] == 1'b0) && (alpha2_zeta_wn_out1_1[46:41] != 6'b000000)) || ((alpha2_zeta_wn_out1_1[47] == 1'b0) && (alpha2_zeta_wn_out1_1[41:18] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((alpha2_zeta_wn_out1_1[47] == 1'b1) && (alpha2_zeta_wn_out1_1[46:41] != 6'b111111) ? 24'sb100000000000000000000000 :
              alpha2_zeta_wn_out1_1[41:18] + $signed({1'b0, alpha2_zeta_wn_out1_1[17]})));

  assign phi_cmd_indtc = p_ff_x_reg_1;

  assign gain1_mul_temp = 16'sb0100000110001001 * phi_cmd_indtc;
  assign phi_cmd_u_gain = gain1_mul_temp[38:0];

  assign phi_cmd_u_gain_1 = ({{7{phi_cmd_u_gain[38]}}, phi_cmd_u_gain[38:22]}) + $signed({1'b0, phi_cmd_u_gain[21]});

  assign phi_cmd_u_dtc = phi_cmd_u_gain_1;

  assign adder1_add_cast = {theta_cmd[23], theta_cmd};
  assign adder1_add_cast_1 = {phi_cmd_u_dtc[23], phi_cmd_u_dtc};
  assign adder1_add_temp = adder1_add_cast + adder1_add_cast_1;
  assign theta_cmd_1 = ((adder1_add_temp[24] == 1'b0) && (adder1_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((adder1_add_temp[24] == 1'b1) && (adder1_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(adder1_add_temp[23:0])));

  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        theta_cmd <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          theta_cmd <= theta_cmd_1;
        end
      end
    end

  assign phi_raw_phi_cmd_sub_cast = {phi_raw_req[23], phi_raw_req};
  assign phi_raw_phi_cmd_sub_cast_1 = {theta_cmd[23], theta_cmd};
  assign phi_raw_phi_cmd_sub_temp = phi_raw_phi_cmd_sub_cast - phi_raw_phi_cmd_sub_cast_1;
  assign phi_raw_phi_cmd_out1 = ((phi_raw_phi_cmd_sub_temp[24] == 1'b0) && (phi_raw_phi_cmd_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((phi_raw_phi_cmd_sub_temp[24] == 1'b1) && (phi_raw_phi_cmd_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(phi_raw_phi_cmd_sub_temp[23:0])));

  always @(posedge clk or posedge reset)
    begin : HwModeRegister11_process
      if (reset == 1'b1) begin
        phi_raw_phi_cmd_out1_1 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          phi_raw_phi_cmd_out1_1 <= phi_raw_phi_cmd_out1;
        end
      end
    end

  assign alpha_wn_2_phi_raw_phi_cmd_out1 = kconst_1 * phi_raw_phi_cmd_out1_1;

  always @(posedge clk or posedge reset)
    begin : PipelineRegister5_process
      if (reset == 1'b1) begin
        alpha_wn_2_phi_raw_phi_cmd_out1_1 <= 48'sh000000000000;
      end
      else begin
        if (enb) begin
          alpha_wn_2_phi_raw_phi_cmd_out1_1 <= alpha_wn_2_phi_raw_phi_cmd_out1;
        end
      end
    end

  assign alpha_wn_2_phi_raw_phi_cmd_out1_2 = (((alpha_wn_2_phi_raw_phi_cmd_out1_1[47] == 1'b0) && (alpha_wn_2_phi_raw_phi_cmd_out1_1[46:37] != 10'b0000000000)) || ((alpha_wn_2_phi_raw_phi_cmd_out1_1[47] == 1'b0) && (alpha_wn_2_phi_raw_phi_cmd_out1_1[37:14] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((alpha_wn_2_phi_raw_phi_cmd_out1_1[47] == 1'b1) && (alpha_wn_2_phi_raw_phi_cmd_out1_1[46:37] != 10'b1111111111) ? 24'sb100000000000000000000000 :
              alpha_wn_2_phi_raw_phi_cmd_out1_1[37:14] + $signed({1'b0, alpha_wn_2_phi_raw_phi_cmd_out1_1[13]})));

  assign Sum1_sub_cast = {alpha_wn_2_phi_raw_phi_cmd_out1_2[23], alpha_wn_2_phi_raw_phi_cmd_out1_2};
  assign Sum1_sub_cast_1 = {Unit_Delay3_out1[23], Unit_Delay3_out1};
  assign Sum1_sub_temp = Sum1_sub_cast - Sum1_sub_cast_1;
  assign Sum1_out1 = ((Sum1_sub_temp[24] == 1'b0) && (Sum1_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((Sum1_sub_temp[24] == 1'b1) && (Sum1_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(Sum1_sub_temp[23:0])));

  assign p_ff_indtc = Sum1_out1;

  assign gain_mul_temp = 16'sb0100000110001001 * p_ff_indtc;
  assign p_ff_u_gain = gain_mul_temp[38:0];

  assign p_ff_u_gain_1 = ({{7{p_ff_u_gain[38]}}, p_ff_u_gain[38:22]}) + $signed({1'b0, p_ff_u_gain[21]});

  assign p_ff_u_dtc = p_ff_u_gain_1;

  assign adder_add_cast = {p_ff_x_reg[23], p_ff_x_reg};
  assign adder_add_cast_1 = {p_ff_u_dtc[23], p_ff_u_dtc};
  assign adder_add_temp = adder_add_cast + adder_add_cast_1;
  assign p_ff_x_reg_1 = ((adder_add_temp[24] == 1'b0) && (adder_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((adder_add_temp[24] == 1'b1) && (adder_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(adder_add_temp[23:0])));

  always @(posedge clk or posedge reset)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        p_ff_x_reg <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          p_ff_x_reg <= p_ff_x_reg_1;
        end
      end
    end

  assign kconst_4 = K_ang;

  always @(posedge clk or posedge reset)
    begin : HwModeRegister_process
      if (reset == 1'b1) begin
        kconst_5 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          kconst_5 <= kconst_4;
        end
      end
    end

  assign theta_cmd_2 = theta_cmd_1;

  assign phi_error_sub_cast = {theta_cmd_2[23], theta_cmd_2};
  assign phi_error_sub_cast_1 = {phi_meas[23], phi_meas};
  assign phi_error_sub_temp = phi_error_sub_cast - phi_error_sub_cast_1;
  assign phi_error_out1 = ((phi_error_sub_temp[24] == 1'b0) && (phi_error_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((phi_error_sub_temp[24] == 1'b1) && (phi_error_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(phi_error_sub_temp[23:0])));

  always @(posedge clk or posedge reset)
    begin : HwModeRegister1_process
      if (reset == 1'b1) begin
        phi_error_out1_1 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          phi_error_out1_1 <= phi_error_out1;
        end
      end
    end

  assign Gain_out1 = kconst_5 * phi_error_out1_1;

  always @(posedge clk or posedge reset)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Gain_out1_1 <= 48'sh000000000000;
      end
      else begin
        if (enb) begin
          Gain_out1_1 <= Gain_out1;
        end
      end
    end

  assign Gain_out1_2 = (((Gain_out1_1[47] == 1'b0) && (Gain_out1_1[46:41] != 6'b000000)) || ((Gain_out1_1[47] == 1'b0) && (Gain_out1_1[41:18] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Gain_out1_1[47] == 1'b1) && (Gain_out1_1[46:41] != 6'b111111) ? 24'sb100000000000000000000000 :
              Gain_out1_1[41:18] + $signed({1'b0, Gain_out1_1[17]})));

  assign p_ref_add_cast = {p_ff_x_reg[23], p_ff_x_reg};
  assign p_ref_add_cast_1 = {Gain_out1_2[23], Gain_out1_2};
  assign p_ref_add_temp = p_ref_add_cast + p_ref_add_cast_1;
  assign qref_before_delay = ((p_ref_add_temp[24] == 1'b0) && (p_ref_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((p_ref_add_temp[24] == 1'b1) && (p_ref_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(p_ref_add_temp[23:0])));

  assign qref_after_delay = qref_before_delay;

  always @(posedge clk or posedge reset)
    begin : reduced_2_process
      if (reset == 1'b1) begin
        p_meas_1 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          p_meas_1 <= p_meas;
        end
      end
    end

  assign p_error_sub_cast = {qref_after_delay[23], qref_after_delay};
  assign p_error_sub_cast_1 = {p_meas_1[23], p_meas_1};
  assign p_error_sub_temp = p_error_sub_cast - p_error_sub_cast_1;
  assign p_error_out1 = ((p_error_sub_temp[24] == 1'b0) && (p_error_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((p_error_sub_temp[24] == 1'b1) && (p_error_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(p_error_sub_temp[23:0])));

  assign Constant1_out1 = 24'sb000000000000000000000000;

  assign Relational_Operator3_cast = {p_error_out1, 2'b00};
  assign Relational_Operator3_cast_1 = {{2{Constant1_out1[23]}}, Constant1_out1};
  assign Relational_Operator3_out1 = Relational_Operator3_cast < Relational_Operator3_cast_1;

  assign Constant_out1 = 24'sb000001001010010100011010;

  assign Relational_Operator1_cast = {p_error_out1, 2'b00};
  assign Relational_Operator1_cast_1 = {{2{Constant1_out1[23]}}, Constant1_out1};
  assign Relational_Operator1_out1 = Relational_Operator1_cast > Relational_Operator1_cast_1;

  assign kconst_6 = Ki_rate;

  always @(posedge clk or posedge reset)
    begin : HwModeRegister4_process
      if (reset == 1'b1) begin
        kconst_7 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          kconst_7 <= kconst_6;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : HwModeRegister5_process
      if (reset == 1'b1) begin
        p_error_out1_1 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          p_error_out1_1 <= p_error_out1;
        end
      end
    end

  assign Inner_I_out1 = kconst_7 * p_error_out1_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch5_process
      if (reset == 1'b1) begin
        delayMatch5_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch5_reg[0] <= Relational_Operator3_out1;
          delayMatch5_reg[1] <= delayMatch5_reg[0];
        end
      end
    end

  assign Relational_Operator3_out1_1 = delayMatch5_reg[1];

  always @(posedge clk or posedge reset)
    begin : delayMatch4_process
      if (reset == 1'b1) begin
        delayMatch4_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch4_reg[0] <= Relational_Operator1_out1;
          delayMatch4_reg[1] <= delayMatch4_reg[0];
        end
      end
    end

  assign Relational_Operator1_out1_1 = delayMatch4_reg[1];

  always @(posedge clk or posedge reset)
    begin : PipelineRegister2_process
      if (reset == 1'b1) begin
        Inner_I_out1_1 <= 56'sh00000000000000;
      end
      else begin
        if (enb) begin
          Inner_I_out1_1 <= Inner_I_out1;
        end
      end
    end

  assign Inner_I_out1_2 = (((Inner_I_out1_1[55] == 1'b0) && (Inner_I_out1_1[54:43] != 12'b000000000000)) || ((Inner_I_out1_1[55] == 1'b0) && (Inner_I_out1_1[43:20] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Inner_I_out1_1[55] == 1'b1) && (Inner_I_out1_1[54:43] != 12'b111111111111) ? 24'sb100000000000000000000000 :
              Inner_I_out1_1[43:20] + $signed({1'b0, Inner_I_out1_1[19]})));

  assign Constant1_out1_dtc = ({{2{Constant1_out1[23]}}, Constant1_out1[23:2]}) + $signed({1'b0, Constant1_out1[1]});

  assign kconst_8 = Kp_rate; 

  always @(posedge clk or posedge reset)
    begin : HwModeRegister6_process
      if (reset == 1'b1) begin
        kconst_9 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          kconst_9 <= kconst_8;
        end
      end
    end

  assign Inner_P_out1 = kconst_9 * p_meas_1;

  always @(posedge clk or posedge reset)
    begin : PipelineRegister3_process
      if (reset == 1'b1) begin
        Inner_P_out1_1 <= 48'sh000000000000;
      end
      else begin
        if (enb) begin
          Inner_P_out1_1 <= Inner_P_out1;
        end
      end
    end

  assign Inner_P_out1_2 = (((Inner_P_out1_1[47] == 1'b0) && (Inner_P_out1_1[46:41] != 6'b000000)) || ((Inner_P_out1_1[47] == 1'b0) && (Inner_P_out1_1[41:18] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Inner_P_out1_1[47] == 1'b1) && (Inner_P_out1_1[46:41] != 6'b111111) ? 24'sb100000000000000000000000 :
              Inner_P_out1_1[41:18] + $signed({1'b0, Inner_P_out1_1[17]})));

  always @(posedge clk or posedge reset)
    begin : delayMatch7_process
      if (reset == 1'b1) begin
        Inner_P_out1_3 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          Inner_P_out1_3 <= Inner_P_out1_2;
        end
      end
    end

  assign kconst_10 = Kd_rate; 

  always @(posedge clk or posedge reset)
    begin : HwModeRegister2_process
      if (reset == 1'b1) begin
        kconst_11 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          kconst_11 <= kconst_10;
        end
      end
    end

  assign Sum_sub_cast = {p_meas[23], p_meas};
  assign Sum_sub_cast_1 = {p_meas_1[23], p_meas_1};
  assign Sum_sub_temp = Sum_sub_cast - Sum_sub_cast_1;
  assign Sum_out1 = ((Sum_sub_temp[24] == 1'b0) && (Sum_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((Sum_sub_temp[24] == 1'b1) && (Sum_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(Sum_sub_temp[23:0])));

  always @(posedge clk or posedge reset)
    begin : HwModeRegister3_process
      if (reset == 1'b1) begin
        Sum_out1_1 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          Sum_out1_1 <= Sum_out1;
        end
      end
    end

  assign Inner_D_out1 = kconst_11 * Sum_out1_1;

  always @(posedge clk or posedge reset)
    begin : PipelineRegister1_process
      if (reset == 1'b1) begin
        Inner_D_out1_1 <= 48'sh000000000000;
      end
      else begin
        if (enb) begin
          Inner_D_out1_1 <= Inner_D_out1;
        end
      end
    end

  assign Inner_D_out1_2 = (((Inner_D_out1_1[47] == 1'b0) && (Inner_D_out1_1[46:41] != 6'b000000)) || ((Inner_D_out1_1[47] == 1'b0) && (Inner_D_out1_1[41:18] == 24'sb011111111111111111111111)) ? 24'sb011111111111111111111111 :
              ((Inner_D_out1_1[47] == 1'b1) && (Inner_D_out1_1[46:41] != 6'b111111) ? 24'sb100000000000000000000000 :
              Inner_D_out1_1[41:18] + $signed({1'b0, Inner_D_out1_1[17]})));

  always @(posedge clk or posedge reset)
    begin : delayMatch8_process
      if (reset == 1'b1) begin
        Inner_D_out1_3 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          Inner_D_out1_3 <= Inner_D_out1_2;
        end
      end
    end

  assign Relational_Operator_cast = {U2_before_sat, 2'b00};
  assign Relational_Operator_cast_1 = {{2{Constant_out1[23]}}, Constant_out1};
  assign Relational_Operator_out1 = Relational_Operator_cast >= Relational_Operator_cast_1;

  assign Logical_Operator_out1 = Relational_Operator_out1 & Relational_Operator1_out1_1;

  assign Relational_Operator2_cast = {U2_before_sat, 2'b00};
  assign Relational_Operator2_cast_1 = {{2{Constant2_out1[23]}}, Constant2_out1};
  assign Relational_Operator2_out1 = Relational_Operator2_cast <= Relational_Operator2_cast_1;

  assign Logical_Operator1_out1 = Relational_Operator2_out1 & Relational_Operator3_out1_1;

  assign Logical_Operator2_out1 = Logical_Operator1_out1 | Logical_Operator_out1;

  assign switch_compare_1 = Logical_Operator2_out1 > 1'b0;

  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Inner_I_out1_2 :
              Constant1_out1_dtc);

  assign Discrete_Time_Integrator_indtc = Switch_out1;

  assign gain2_mul_temp = 16'sb0100000110001001 * Discrete_Time_Integrator_indtc;
  assign Discrete_Time_Integrator_u_gain = gain2_mul_temp[38:0];

  assign Discrete_Time_Integrator_u_gain_1 = ({{7{Discrete_Time_Integrator_u_gain[38]}}, Discrete_Time_Integrator_u_gain[38:22]}) + $signed({1'b0, Discrete_Time_Integrator_u_gain[21]});

  assign Discrete_Time_Integrator_u_dtc = Discrete_Time_Integrator_u_gain_1;

  assign adder2_add_cast = {Discrete_Time_Integrator_x_reg[23], Discrete_Time_Integrator_x_reg};
  assign adder2_add_cast_1 = {Discrete_Time_Integrator_u_dtc[23], Discrete_Time_Integrator_u_dtc};
  assign adder2_add_temp = adder2_add_cast + adder2_add_cast_1;
  assign Discrete_Time_Integrator_u_add = ((adder2_add_temp[24] == 1'b0) && (adder2_add_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((adder2_add_temp[24] == 1'b1) && (adder2_add_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(adder2_add_temp[23:0])));

  assign Discrete_Time_Integrator_u_sat = (Discrete_Time_Integrator_u_add > 24'sb000000010010100101000111 ? 24'sb000000010010100101000111 :
              (Discrete_Time_Integrator_u_add < 24'sb111111101101011010111001 ? 24'sb111111101101011010111001 :
              Discrete_Time_Integrator_u_add));

  assign Discrete_Time_Integrator_u_sat_1 = (stateControl_2 == 1'b0 ? Discrete_Time_Integrator_x_reg :
              Discrete_Time_Integrator_u_sat);

  always @(posedge clk or posedge reset)
    begin : Discrete_Time_Integrator_reg_process
      if (reset == 1'b1) begin
        Discrete_Time_Integrator_x_reg <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          Discrete_Time_Integrator_x_reg <= Discrete_Time_Integrator_u_sat_1;
        end
      end
    end

  assign Sum2_stage2_sub_cast = {Discrete_Time_Integrator_x_reg[23], Discrete_Time_Integrator_x_reg};
  assign Sum2_stage2_sub_cast_1 = {Inner_P_out1_3[23], Inner_P_out1_3};
  assign Sum2_stage2_sub_temp = Sum2_stage2_sub_cast - Sum2_stage2_sub_cast_1;
  assign Sum2_stage2_cast = ((Sum2_stage2_sub_temp[24] == 1'b0) && (Sum2_stage2_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((Sum2_stage2_sub_temp[24] == 1'b1) && (Sum2_stage2_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(Sum2_stage2_sub_temp[23:0])));
  assign Sum2_op_stage1 = {Sum2_stage2_cast[23], Sum2_stage2_cast};

  assign Sum2_stage3_sub_cast = ((Sum2_op_stage1[24] == 1'b0) && (Sum2_op_stage1[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((Sum2_op_stage1[24] == 1'b1) && (Sum2_op_stage1[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(Sum2_op_stage1[23:0])));
  assign Sum2_stage3_sub_cast_1 = {Sum2_stage3_sub_cast[23], Sum2_stage3_sub_cast};
  assign Sum2_stage3_sub_cast_2 = {Inner_D_out1_3[23], Inner_D_out1_3};
  assign Sum2_stage3_sub_temp = Sum2_stage3_sub_cast_1 - Sum2_stage3_sub_cast_2;
  assign U2_before_sat = ((Sum2_stage3_sub_temp[24] == 1'b0) && (Sum2_stage3_sub_temp[23] != 1'b0) ? 24'sb011111111111111111111111 :
              ((Sum2_stage3_sub_temp[24] == 1'b1) && (Sum2_stage3_sub_temp[23] != 1'b1) ? 24'sb100000000000000000000000 :
              $signed(Sum2_stage3_sub_temp[23:0])));

  assign U2_before_sat_1 = U2_before_sat;

  assign Saturation_out1 = (U2_before_sat_1 > 24'sb000000010010100101000111 ? 24'sb000000010010100101000111 :
              (U2_before_sat_1 < 24'sb111111101101011010111001 ? 24'sb111111101101011010111001 :
              U2_before_sat_1));

  assign U2 = Saturation_out1;

  assign ce_out = clk_enable;

endmodule  // Attitude_Roll_Controller_2


