// -------------------------------------------------------------
// 
// File Name: C:\Users\Labhesh\OneDrive\Desktop\IIT Madras\Startup\FPGA\Yaw_Control_loop\Yaw_controller\yaw_controller.v
// Created: 2026-06-08 23:03:13
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.004
// Target subsystem base rate: 0.004
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.004
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// U4                            ce_out        0.004
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: yaw_controller
// Source Path: Yaw_controller/yaw_controller
// Hierarchy Level: 0
// Model version: 1.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module yaw_controller
          (clk,
           resetn,        // Changed to active-low reset for Block Diagram compliance
           clk_enable,
           kconst,
           kconst_2,
           k_int,
           ready,
           yaw_req,
           current_yaw,
           current_yaw_rate,
           ce_out,
           U4,
           U4_unclamped_out1_dbg);


  input   clk;
  input   resetn;         // Changed to active-low reset
  input   clk_enable;
  input   signed [15:0] yaw_req;  // sfix16_En12
  input   signed [15:0] current_yaw;  // sfix16_En12
  input   signed [15:0] current_yaw_rate;  // sfix16_En11
  input signed [15:0] kconst;  // sfix16_En12
  input signed [15:0] kconst_2;  // sfix16_En14
  input signed [15:0] k_int;  // sfix16_En12
  input ready;
  output  ce_out;
  output  signed [15:0] U4;  // sfix16_En14
  output signed  [15:0] U4_unclamped_out1_dbg; // // sfix16_En12
    
  wire enb;
  wire signed [15:0] kconst;  // sfix16_En12
  reg signed [15:0] kconst_1;  // sfix16_En12
  wire signed [16:0] error_sub_cast;  // sfix17_En12
  wire signed [16:0] error_sub_cast_1;  // sfix17_En12
  wire signed [16:0] error_sub_temp;  // sfix17_En12
  wire signed [15:0] error_out1;  // sfix16_En12
  wire signed [15:0] Constant_out1;  // sfix16_En12
  wire Relational_Operator_out1;
  wire signed [15:0] Constant1_out1;  // sfix16_En12
  wire signed [16:0] error1_sub_cast;  // sfix17_En12
  wire signed [16:0] error1_sub_cast_1;  // sfix17_En12
  wire signed [16:0] error1_sub_temp;  // sfix17_En12
  wire signed [15:0] error1_out1;  // sfix16_En12
  wire signed [15:0] Switch_out1;  // sfix16_En12
  wire signed [15:0] Constant2_out1;  // sfix16_En12
  wire Relational_Operator1_out1;
  wire signed [15:0] Constant3_out1;  // sfix16_En12
  wire signed [31:0] Add_add_cast;  // sfix32_En12
  wire signed [31:0] Add_add_cast_1;  // sfix32_En12
  wire signed [31:0] Add_add_temp;  // sfix32_En12
  wire signed [15:0] Add_out1;  // sfix16_En12
  wire signed [15:0] final_psi_error_out1;  // sfix16_En12
  reg signed [15:0] final_psi_error_out1_1;  // sfix16_En12
  wire signed [31:0] P_term;  // sfix32_En24
  reg signed [15:0] kconst_3;  // sfix16_En14
  reg signed [15:0] current_yaw_rate_1;  // sfix16_En11
  wire signed [31:0] D_term;  // sfix32_En25
  reg signed [31:0] P_term_1;  // sfix32_En24
  wire signed [15:0] P_term_2;  // sfix16_En12
  reg signed [31:0] D_term_1;  // sfix32_En25
  wire signed [15:0] D_term_2;  // sfix16_En12
  wire signed [31:0] U4_unclamped_stage2_sub_cast;  // sfix32_En12
  wire signed [31:0] U4_unclamped_stage2_sub_cast_1;  // sfix32_En12
  wire signed [31:0] U4_unclamped_stage2_sub_temp;  // sfix32_En12
  wire signed [16:0] U4_unclamped_op_stage1;  // sfix17_En12
  wire stateControl_1;
  reg  [1:0] delayMatch2_reg;  // ufix1 [2]
  wire stateControl_2;
  wire Constant5_out1;  // ufix1
  wire signed [15:0] Relational_Operator3_cast;  // sfix16_En12
  wire Relational_Operator3_out1;
  reg  [1:0] delayMatch1_reg;  // ufix1 [2]
  wire Relational_Operator3_out1_1;
  wire signed [1:0] Constant4_out1;  // sfix2_En1
  wire signed [1:0] Constant6_out1;  // sfix2_En1
  wire Constant7_out1;  // ufix1
  wire signed [15:0] Relational_Operator5_cast;  // sfix16_En12
  wire Relational_Operator5_out1;
  reg  [1:0] delayMatch_reg;  // ufix1 [2]
  wire Relational_Operator5_out1_1;
  wire signed [15:0] kconst_4;  // sfix16_En14
  reg signed [15:0] kconst_5;  // sfix16_En14
  wire signed [31:0] dt_out1;  // sfix32_En26
  reg signed [31:0] dt_out1_1;  // sfix32_En26
  wire signed [15:0] dt_out1_2;  // sfix16_En12
  reg signed [15:0] int_yaw_out1;  // sfix16_En12
  wire signed [31:0] new_yaw_int_add_cast;  // sfix32_En12
  wire signed [31:0] new_yaw_int_add_cast_1;  // sfix32_En12
  wire signed [31:0] new_yaw_int_add_temp;  // sfix32_En12
  wire signed [15:0] new_yaw_int_out1;  // sfix16_En12
  wire signed [15:0] U4_unclamped_out1;  // sfix16_En12
  wire signed [15:0] Relational_Operator4_cast;  // sfix16_En12
  wire Relational_Operator4_out1;
  wire Logical_Operator1_out1;
  wire signed [15:0] Saturation_out1;  // sfix16_En14
  wire signed [15:0] Relational_Operator2_cast;  // sfix16_En14
  wire Relational_Operator2_out1;
  wire Logical_Operator_out1;
  wire Logical_Operator2_out1;
  wire signed [15:0] final_out1;  // sfix16_En12
  wire signed [15:0] final_out1_1;  // sfix16_En12
  wire signed [31:0] I_term;  // sfix32_En24
  wire signed [15:0] I_term_1;  // sfix16_En12
  wire signed [31:0] U4_unclamped_stage3_add_cast;  // sfix32_En12
  wire signed [31:0] U4_unclamped_stage3_add_cast_1;  // sfix32_En12
  wire signed [31:0] U4_unclamped_stage3_add_temp;  // sfix32_En12
  wire signed [15:0] dtc_out;  // sfix16_En14

  // Debug probes
  assign final_psi_error_out1_dbg = final_psi_error_out1;   // sfix16_En12
  assign P_term_2_dbg = P_term_2;                           // sfix16_En12
  assign D_term_2_dbg = D_term_2;                           // sfix16_En12
  assign int_yaw_out1_dbg = int_yaw_out1;                   // sfix16_En12
  assign I_term_1_dbg = I_term_1;                           // sfix16_En12
  assign U4_unclamped_out1_dbg = U4_unclamped_out1;         // sfix16_En12

//  assign kconst = 16'sb0001101111100011;  // no longer needed ; coming from PS

  assign enb = clk_enable&ready;

  // Updated to fully synchronous active-low reset
  always @(posedge clk)
    begin : HwModeRegister2_process
      if (resetn == 1'b0) begin
        kconst_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          kconst_1 <= kconst;
        end
      end
    end

  assign error_sub_cast = {yaw_req[15], yaw_req};
  assign error_sub_cast_1 = {current_yaw[15], current_yaw};
  assign error_sub_temp = error_sub_cast - error_sub_cast_1;
  assign error_out1 = ((error_sub_temp[16] == 1'b0) && (error_sub_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((error_sub_temp[16] == 1'b1) && (error_sub_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(error_sub_temp[15:0])));

  assign Constant_out1 = 16'sb0011001001000100;

  assign Relational_Operator_out1 = error_out1 > Constant_out1;

  assign Constant1_out1 = 16'sb0110010010001000;

  assign error1_sub_cast = {error_out1[15], error_out1};
  assign error1_sub_cast_1 = {Constant1_out1[15], Constant1_out1};
  assign error1_sub_temp = error1_sub_cast - error1_sub_cast_1;
  assign error1_out1 = ((error1_sub_temp[16] == 1'b0) && (error1_sub_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((error1_sub_temp[16] == 1'b1) && (error1_sub_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(error1_sub_temp[15:0])));

  assign Switch_out1 = (Relational_Operator_out1 == 1'b0 ? error_out1 :
              error1_out1);

  assign Constant2_out1 = 16'sb1100110110111100;

  assign Relational_Operator1_out1 = Switch_out1 < Constant2_out1;

  assign Constant3_out1 = 16'sb0110010010001000;

  assign Add_add_cast = {{16{Switch_out1[15]}}, Switch_out1};
  assign Add_add_cast_1 = {{16{Constant3_out1[15]}}, Constant3_out1};
  assign Add_add_temp = Add_add_cast + Add_add_cast_1;
  assign Add_out1 = Add_add_temp[15:0];

  assign final_psi_error_out1 = (Relational_Operator1_out1 == 1'b0 ? Switch_out1 :
              Add_out1);

  // Updated to fully synchronous active-low reset
  always @(posedge clk)
    begin : reduced_process
      if (resetn == 1'b0) begin
        final_psi_error_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          final_psi_error_out1_1 <= final_psi_error_out1;
        end
      end
    end

  assign P_term = kconst_1 * final_psi_error_out1_1;

//  assign kconst_2 = 16'sb0000110111001100;    // coming from PS

  // Updated to fully synchronous active-low reset
  always @(posedge clk)
    begin : HwModeRegister_process
      if (resetn == 1'b0) begin
        kconst_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          kconst_3 <= kconst_2;
        end
      end
    end

  // Updated to fully synchronous active-low reset
  always @(posedge clk)
    begin : HwModeRegister1_process
      if (resetn == 1'b0) begin
        current_yaw_rate_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          current_yaw_rate_1 <= current_yaw_rate;
        end
      end
    end

  assign D_term = kconst_3 * current_yaw_rate_1;

  // Updated to fully synchronous active-low reset
  always @(posedge clk)
    begin : PipelineRegister1_process
      if (resetn == 1'b0) begin
        P_term_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          P_term_1 <= P_term;
        end
      end
    end

  assign P_term_2 = (((P_term_1[31] == 1'b0) && (P_term_1[30:27] != 4'b0000)) || ((P_term_1[31] == 1'b0) && (P_term_1[27:12] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((P_term_1[31] == 1'b1) && (P_term_1[30:27] != 4'b1111) ? 16'sb1000000000000000 :
              P_term_1[27:12] + $signed({1'b0, P_term_1[11]})));

  // Updated to fully synchronous active-low reset
  always @(posedge clk)
    begin : PipelineRegister_process
      if (resetn == 1'b0) begin
        D_term_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          D_term_1 <= D_term;
        end
      end
    end

  assign D_term_2 = (((D_term_1[31] == 1'b0) && (D_term_1[30:28] != 3'b000)) || ((D_term_1[31] == 1'b0) && (D_term_1[28:13] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((D_term_1[31] == 1'b1) && (D_term_1[30:28] != 3'b111) ? 16'sb1000000000000000 :
              D_term_1[28:13] + $signed({1'b0, D_term_1[12]})));

  assign U4_unclamped_stage2_sub_cast = {{16{P_term_2[15]}}, P_term_2};
  assign U4_unclamped_stage2_sub_cast_1 = {{16{D_term_2[15]}}, D_term_2};
  assign U4_unclamped_stage2_sub_temp = U4_unclamped_stage2_sub_cast - U4_unclamped_stage2_sub_cast_1;
  assign U4_unclamped_op_stage1 = U4_unclamped_stage2_sub_temp[16:0];

  assign stateControl_1 = 1'b1;

  // Updated to fully synchronous active-low reset
  always @(posedge clk)
    begin : delayMatch2_process
      if (resetn == 1'b0) begin
        delayMatch2_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch2_reg[0] <= stateControl_1;
          delayMatch2_reg[1] <= delayMatch2_reg[0];
        end
      end
    end

  assign stateControl_2 = delayMatch2_reg[1];

  assign Constant5_out1 = 1'b0;

  assign Relational_Operator3_cast = {3'b0, {Constant5_out1, 12'b000000000000}};
  assign Relational_Operator3_out1 = final_psi_error_out1 >= Relational_Operator3_cast;

  // Updated to fully synchronous active-low reset
  always @(posedge clk)
    begin : delayMatch1_process
      if (resetn == 1'b0) begin
        delayMatch1_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch1_reg[0] <= Relational_Operator3_out1;
          delayMatch1_reg[1] <= delayMatch1_reg[0];
        end
      end
    end

  assign Relational_Operator3_out1_1 = delayMatch1_reg[1];

  assign Constant4_out1 = 2'sb01;

  assign Constant6_out1 = 2'sb11;

  assign Constant7_out1 = 1'b0;

  assign Relational_Operator5_cast = {3'b0, {Constant7_out1, 12'b000000000000}};
  assign Relational_Operator5_out1 = final_psi_error_out1 <= Relational_Operator5_cast;

  // Updated to fully synchronous active-low reset
  always @(posedge clk)
    begin : delayMatch_process
      if (resetn == 1'b0) begin
        delayMatch_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= Relational_Operator5_out1;
          delayMatch_reg[1] <= delayMatch_reg[0];
        end
      end
    end

  assign Relational_Operator5_out1_1 = delayMatch_reg[1];

  assign kconst_4 = 16'sb0000000001000010;

  // Updated to fully synchronous active-low reset
  always @(posedge clk)
    begin : HwModeRegister4_process
      if (resetn == 1'b0) begin
        kconst_5 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          kconst_5 <= kconst_4;
        end
      end
    end

  assign dt_out1 = kconst_5 * final_psi_error_out1_1;

  // Updated to fully synchronous active-low reset
  always @(posedge clk)
    begin : PipelineRegister2_process
      if (resetn == 1'b0) begin
        dt_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          dt_out1_1 <= dt_out1;
        end
      end
    end

  assign dt_out1_2 = (((dt_out1_1[31] == 1'b0) && (dt_out1_1[30:29] != 2'b00)) || ((dt_out1_1[31] == 1'b0) && (dt_out1_1[29:14] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((dt_out1_1[31] == 1'b1) && (dt_out1_1[30:29] != 2'b11) ? 16'sb1000000000000000 :
              dt_out1_1[29:14] + $signed({1'b0, dt_out1_1[13]})));

  assign new_yaw_int_add_cast = {{16{dt_out1_2[15]}}, dt_out1_2};
  assign new_yaw_int_add_cast_1 = {{16{int_yaw_out1[15]}}, int_yaw_out1};
  assign new_yaw_int_add_temp = new_yaw_int_add_cast + new_yaw_int_add_cast_1;
  assign new_yaw_int_out1 = new_yaw_int_add_temp[15:0];

  assign Relational_Operator4_cast = {{3{Constant6_out1[1]}}, {Constant6_out1, 11'b00000000000}};
  assign Relational_Operator4_out1 = U4_unclamped_out1 < Relational_Operator4_cast;

  assign Logical_Operator1_out1 = Relational_Operator4_out1 & Relational_Operator5_out1_1;

  assign Relational_Operator2_cast = {Constant4_out1[1], {Constant4_out1, 13'b0000000000000}};
  assign Relational_Operator2_out1 = Saturation_out1 > Relational_Operator2_cast;

  assign Logical_Operator_out1 = Relational_Operator3_out1_1 & Relational_Operator2_out1;

  assign Logical_Operator2_out1 = Logical_Operator_out1 | Logical_Operator1_out1;

  assign final_out1 = (Logical_Operator2_out1 == 1'b0 ? new_yaw_int_out1 :
              int_yaw_out1);

  assign final_out1_1 = (stateControl_2 == 1'b0 ? int_yaw_out1 :
              final_out1);

  // Updated to fully synchronous active-low reset
  always @(posedge clk)
    begin : int_yaw_process
      if (resetn == 1'b0) begin
        int_yaw_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          int_yaw_out1 <= final_out1_1;
        end
      end
    end

  assign I_term = k_int * int_yaw_out1;
//  assign I_term = 16'sb0001010000101001 * int_yaw_out1;

  assign I_term_1 = (((I_term[31] == 1'b0) && (I_term[30:27] != 4'b0000)) || ((I_term[31] == 1'b0) && (I_term[27:12] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((I_term[31] == 1'b1) && (I_term[30:27] != 4'b1111) ? 16'sb1000000000000000 :
              I_term[27:12] + $signed({1'b0, I_term[11]})));

  assign U4_unclamped_stage3_add_cast = {{15{U4_unclamped_op_stage1[16]}}, U4_unclamped_op_stage1};
  assign U4_unclamped_stage3_add_cast_1 = {{16{I_term_1[15]}}, I_term_1};
  assign U4_unclamped_stage3_add_temp = U4_unclamped_stage3_add_cast + U4_unclamped_stage3_add_cast_1;
  assign U4_unclamped_out1 = U4_unclamped_stage3_add_temp[15:0];

  assign dtc_out = ((U4_unclamped_out1[15] == 1'b0) && (U4_unclamped_out1[14:13] != 2'b00) ? 16'sb0111111111111111 :
              ((U4_unclamped_out1[15] == 1'b1) && (U4_unclamped_out1[14:13] != 2'b11) ? 16'sb1000000000000000 :
              {U4_unclamped_out1[13:0], 2'b00}));

  assign Saturation_out1 = (dtc_out > 16'sb0010000000000000 ? 16'sb0010000000000000 :
              (dtc_out < 16'sb1110000000000000 ? 16'sb1110000000000000 :
              dtc_out));

  assign U4 = Saturation_out1;

  assign ce_out = clk_enable;

endmodule  // yaw_controller